<?php include __DIR__ . "/../layout/header.phtml"; ?>
<div class="col-sm-12">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <form class="form-horizontal" id="frm">

                <div class="form-group">
                    <label class="col-sm-3 control-label">标题：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="标题" class="form-control" id="title" name="title"
                               value="<?= $data['title'] ?? ''; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">描述：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="描述" class="form-control" id="description" name="description"
                               value="<?= $data['description'] ?? ''; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">图片：</label>

                    <div class="col-sm-8">
                        <input type="file" placeholder="图片" class="form-control" id="img_url" name="img_url"
                               value="<?= $data['img_url']; ?>">
                        <?php if($data['img_url']){ ?>
                            <img onclick="show_img('<?= $data['img_url'] ?>')" src="<?= $data['img_url']; ?>" style="width: 80px ;height: 60px;">
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">跳转类型：</label>
                    <div class="col-sm-8">
                    <select  id="type" name="type">
                        <?php foreach (AdsModel::ADS_TYPE as $k=>$v){ ?>
                            <option value="<?=$k?>" <?php if($data['type'] == $k):?> selected <?php endif;?> ><?=$v?></option>
                        <?php } ?>
                    </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">广告地址：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="广告地址" class="form-control" name="url" value="<?= $data['url'] ?? ''; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">视频地址：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="m3u8视频地址,如果有的话" class="form-control" name="mv_m3u8" value="<?= $data['mv_m3u8'] ?? ''; ?>">
                    </div>
                </div>
               <div class="form-group">
                    <label class="col-sm-3 control-label">广告位置：</label>
                   <div class="col-sm-8">
                    <select id="apply_type" name="position">
                        <?php foreach ($position as $key => $item) { ?>
                        <option value="<?php echo $key; ?>" <?php if($data['position']== $key):?> selected <?php endif;?> ><?= $item ?></option>
                        <?php } ?>
                    </select>
                   </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">状态：</label>

                    <div class="col-sm-8">
                        <select name="status" id="status">
                            <option value="0" <?php if($data['status']??-1 == 0):?> selected <?php endif;?> >禁用</option>
                            <option value="1" <?php if($data['status']??-1 == 1):?> selected <?php endif;?> >启用</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">渠道标识：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="渠道标识，一般不需要设置和修改" class="form-control" name="channel" value="<?= $data['channel'] ?? ''; ?>">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-danger" type="button" onclick="handleEdit()">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    var index = parent.layer.getFrameIndex(window.name);
    var transFile = 0;
    $('#img_url').click(
        function () {
            transFile = 1;
        }
    );
    function handleEdit() {
        var formData = new FormData($( "#frm" )[0]);
        formData.append('transFile',transFile);
        formData.append('id',"<?=$_GET['id']?>");
        $.ajax({
            url: '/d.php?mod=ads&code=doEdit',
            data: formData,
            type: 'POST',
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            success: function (res) {
                if (res.status == 1) {
                    parent.reload(res.data)
                    parent.layer.close(index)

                } else {
                    layer.msg(res.data, {icon: 5})
                }
            }
        })
    }
</script>
<?php include __DIR__ . "/../layout/footer.phtml"; ?>
