<?php include __DIR__ . "/../layout/header.phtml";?>

<form action="./d.php?mod=manager" method="post">
    <table cellspacing="1" width="100%" align="center" class="tableborder">
        <tbody>
        <tr class="header">
            <td class="altbg1">
                <input type="text" name="flag" placeholder="管理员名字" style="width: 200px" value="<?=$flag;?>">
                <input class="button lf" type="submit" name="setting_submit" id="setting_submit" value="搜索">
                <a href="d.php?mod=manager&code=editManager"><input class="button lf" type="button" value="新增"></a>
            </td>
        </tr>
        </tbody>
    </table>
</form>
<style>
    td{
        width: 25%;
    }
    img{
        max-width: 100%;
        max-height: 100%;
    }
</style>
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tableborder">
    <tr class="header">
        <td>管理员ID</td>
        <td>用户名</td>
        <td>角色</td>
        <td>操作</td>
    </tr>
    <?php if($topic):?>
    <?php foreach ($topic as $k=>$v) :?>
    <tr>
        <td><?=$v['uid'];?></td>
        <td><?=$v['username'];?></td>
        <td><?=$v['role_name'];?></td>
        <td>
            <a href="javascript:void(0);" class="reset-pass" data-href="d.php?mod=manager&code=resetManagerPass&uid=<?=$v['uid'];?>">重置密码</a> |
            <a href="d.php?mod=manager&code=editManager&uid=<?=$v['uid'];?>">编辑</a> |
            <a href="javascript:void(0)" class="del" data-href="d.php?mod=manager&code=delManager&id=<?=$v['uid'];?>" >删除</a>
        </td>
    </tr>
    <?php endforeach;?>
    <?php else:?>
        <tr>
            <td colspan="15">暂无数据</td>
        </tr>
    <?php endif;?>
</table>
<br>
<div class="pagination"><?= $page_arr['html'] ?></div>
<br>
<br>
<script type="text/javascript" src="/static/admin/js/layer/layer.js"></script>
<script>
    $(function () {
        $(document).on('click','.reset-pass',function () {
            var reset_url = $(this).attr('data-href');
            layer.confirm('您确定要重置该管理员密码为123456吗?', {
                btn: ['确定', '取消'], //按钮
                title:'提示'
            }, function () {
                window.location.href = reset_url;
            })
        });
        $(document).on('click','.del',function () {
            var reset_url = $(this).attr('data-href');
            layer.confirm('您确定要删除该管理员吗?', {
                btn: ['确定', '取消'], //按钮
                title:'提示'
            }, function () {
                window.location.href = reset_url;
            })
        });
    })
</script>
<?php include __DIR__ . "/../layout/footer.phtml";?>

