<?php include __DIR__ . "/../layout/header.phtml";?>

<form action="./d.php?mod=manager&code=roleList" method="post">
    <table cellspacing="1" width="100%" align="center" class="tableborder">
        <tbody>
        <tr class="header">
            <td class="altbg1">
                <input type="text" name="flag" placeholder="角色名字" style="width: 200px" value="<?=$flag;?>">
                <input class="button lf" type="submit" name="setting_submit" id="setting_submit" value="搜索">
                <a href="d.php?mod=manager&code=editRole"><input class="button lf" type="button" value="新增"></a>
            </td>
        </tr>
        </tbody>
    </table>
</form>
<style>
    td{
        width: 25%;
    }
    img{
        max-width: 100%;
        max-height: 100%;
    }
</style>
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tableborder">
    <tr class="header">
        <td>角色ID</td>
        <td>角色名</td>
        <td>角色权限(未命名则显示'控制器/方法')</td>
        <td>操作</td>
    </tr>
    <?php if($topic):?>
    <?php foreach ($topic as $v):?>
    <tr>
        <td><?=$v['role_id'];?></td>
        <td><?=$v['role_name'];?></td>
        <td><?=$v['permissions'];?></td>
        <td>
            <a href="d.php?mod=manager&code=editRole&role_id=<?=$v['role_id'];?>">编辑</a> |
            <a href="javascript:if(confirm('确实要删除吗?'))location='d.php?mod=manager&code=delRole&id=<?=$v['role_id'];?>'" >删除</a>
        </td>
    </tr>
        <?php endforeach;?>
    <?php else:?>
    <tr>
        <td colspan="15">暂无数据</td>
    </tr>
    <?php endif;?>
</table>
<br>
<?=$page_arr['html'];?>
<br>
<br>
<?php include __DIR__ . "/../layout/footer.phtml";?>

