<?php importView("header.phtml"); ?>
<style>
    .layui-form.user-edit-dialog .layui-input-block {
        margin-right: 30px
    }
</style>
<div class="layui-card layadmin-header">
    <div class="layui-breadcrumb" lay-filter="breadcrumb">
        <a lay-href="">主页</a>
        <a><cite>组件</cite></a>
        <a><cite>数据表格</cite></a>
        <a><cite>开启头部工具栏</cite></a>
    </div>
</div>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">菜单名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[name]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <!-- <button class="layui-btn layui-btn-sm" lay-event="delSelect" lay-form="user-edit-dialog"
                                     data-pk="id">
                                 删除选择
                             </button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" id="user-edit-dialog" data-h="680" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'保存菜单',closeBtn:false,shadeClose:true,anim:3,full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item" style="width: 600px;">
            <div class="layui-inline">
                <label class="layui-form-label">菜单名称：</label>
                <div class="layui-input-inline">
                    <input placeholder="菜单名称" name="name" value="{{=d.name }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item" style="width: 600px;">
            <div class="layui-inline">
                <label class="layui-form-label">图标：</label>
                <div class="layui-input-inline">
                    <input placeholder="菜单名称" name="icon" value="{{=d.icon }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item" style="width: 600px;">
            <div class="layui-inline">
                <label class="layui-form-label">控制器：</label>
                <div class="layui-input-inline">
                    <input placeholder="控制器" name="controller" value="{{=d.controller }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item" style="width: 600px;">
            <div class="layui-inline">
                <label class="layui-form-label">方法：</label>
                <div class="layui-input-inline">
                    <input placeholder="方法" name="action" value="{{=d.action }}" class="layui-input">
                </div>
            </div>
        </div>
        <!--        <div class="layui-form-item" style="width: 600px;">-->
        <!--            <label class="layui-form-label">路径：</label>-->
        <!--            <div class="layui-input-block">-->
        <!--                <input placeholder="路径" name="value" value="{{=d.value }}" class="layui-input">-->
        <!--            </div>-->
        <!--        </div>-->
        <div class="layui-form-item" style="width: 600px;">
            <label class="layui-form-label">上级分类：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('pid', AdminMenuModel::getTreeArrayData(0), ['data-value' => '{{=d.pid }}']) ?>
            </div>
        </div>
        <div class="layui-form-item" style="width: 600px;">
            <div class="layui-inline">
                <label class="layui-form-label">排序：</label>
                <div class="layui-input-inline">
                    <input placeholder="排序" name="sort" value="{{=d.sort }}" class="layui-input">
                </div>
            </div>
        </div>
        <!--<div class="layui-form-item" style="width: 600px;">
            <label class="layui-form-label">按钮：</label>
            <div class="layui-input-block">
                <input name="button" lay-filter="event-dialog" type="radio" value="0" title="不是按钮">
                <input name="button" lay-filter="event-dialog" type="radio" value="1" title="表格头部">
                <input name="button" lay-filter="event-dialog" type="radio" value="2" title="表格操作">
            </div>
        </div>
        <div class="layui-form-item" style="width: 800px;display: none" id="event-dialog">
            <div class="layui-inline">
                <label class="layui-form-label">event：</label>
                <div class="layui-input-inline">
                    <input name="event" type="text" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">dialog：</label>
                <div class="layui-input-inline">
                    <input name="dialog" type="text" value="" class="layui-input">
                </div>
            </div>
        </div>-->
        <div class="layui-form-item" style="width: 600px;">
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::radioMulti('status', ['yes' => 'yes', 'no' => 'no']) ?>
                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script type="text/javascript" src="<?php echo LAY_UI_STATIC ?>data-list.js"></script>
<?php importView("fooler.phtml"); ?>


<script>
    function eventDialogSow() {
        console.log(111);
        $('#event-dialog').show();
    }

    function eventDialogHide() {
        $('#event-dialog').hide();
    }

    layui.config({
        base: '<?php echo LAY_UI_STATIC ?>layuiadmin/', //静态资源所在路径
        limit: xx.config('limit', 500)
    }).extend({
        index: 'lib/index' //主入口模块
    });
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        updateUrl: "",
        title: '数据表',
        cols: [[
            //{type: 'checkbox', fixed: 'left'},
            {field: 'id', title: 'ID'},
            {
                field: 'name', title: '菜单名称', edit: true, templet: function (v) {
                    if (v.level === 1) {
                        return v.name;
                    } else if (v.level === 2) {
                        return "<span style='padding-left: 30px'>" + v.name + "</span>";
                    }
                }
            }
            , {field: 'controller', title: '控制器', edit: true}
            , {field: 'action', title: '方法', edit: true}
            // , {field: 'level', title: '等级',templet:function (d) {
            //         return d.level == 1 ? '顶级' : d.level ;
            //     }}
            // , {field: 'pid', title: '上级'}
            , {field: 'sort', title: '排序', edit: true}
            , {field: 'status', title: '状态', type: "switch", 'edit': true, text: "YES|NO", value: "yes|no"}
            , {field: 'created_at', title: '创建时'}
            , {fixed: 'right', width: 165, align: 'center', title: '操作', toolbar: '#operate-toolbar'}
        ]]
        //event.operate->edit
        , event: {
            toolbar: {
                addUser: function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn();
                    form.on('radio(event-dialog)', function (data) {
                        if (data.value > 0) {
                            $('#event-dialog').show();
                        } else {
                            $('#event-dialog').hide();
                        }
                    });
                }
            },
            operate: {
                edit: function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn();
                    Util.renderSelect(event.data, $, form);
                    form.on('radio(event-dialog)', function (data) {
                        if (data.value > 0) {
                            $('#event-dialog').show();
                        } else {
                            $('#event-dialog').hide();
                        }
                    });
                }
            }
        }

    });
</script>
