<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">合集标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">用户uid</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态：</label>
                            <div class="layui-input-inline">
                                <?php echo Layui::select('where[status]' , merge_array(['' => '请选择'], TopicModel::STAT)) ?>
                            </div>
                        </div>


                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                                                        <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                                            添加
                                                        </button>
                            <button class="layui-btn layui-btn-sm" lay-event="refresh">更新视频数</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <!--                        <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>-->
                                                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                                                    <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">合集标题：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="合集标题" name="title"
                           value="{{=d.title }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">合集介绍：</label>
                <div class="layui-input-inline">

                    <textarea name="desp" class="layui-textarea"
                              style="height: 100px">{{=d.desp }}</textarea>
                </div>
            </div>
        </div>

        <div class="layui-form-item">

            <label class="layui-form-label">合集图片：</label>
            <div class="layui-input-block">

                <img src="{{d.image_url }}" id="img-img_url" width="50" height="50">
                <button type="button" class="but-upload-img layui-btn" data-json="{position:'ads'}"
                        data-img="#img-img_url" data-input="#input-img_url"><i class="layui-icon">&#xe67c;</i>上传
                </button>
                <input type="hidden" name="image" id="input-img_url" value="{{=d.image }}">
            </div>

        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">点赞数量：</label>
                <div class="layui-input-inline">

                    <input  placeholder="点赞数量" name="like_count"
                           value="{{=d.like_count }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">视频id：</label>
                <div class="layui-input-inline">

                    <input  placeholder="视频id" name="mv_id_str"
                           value="{{=d.mv_id_str }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('status' , TopicModel::STAT , ['data-value' => '{{=d.status}}']) ?>
                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户uid：</label>
                <div class="layui-input-inline">

                    <input  placeholder="用户uid" name="uid"
                           value="{{=d.uid }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">视频数量：</label>
                <div class="layui-input-inline">

                    <input placeholder="视频数量" name="video_count"
                           value="{{=d.video_count }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">实际金币：</label>
                <div class="layui-input-inline">

                    <input placeholder="实际金币" name="coins"
                           value="{{=d.coins }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">原始价格：</label>
                <div class="layui-input-inline">

                    <input placeholder="原始价格" name="origin_coins"
                           value="{{=d.origin_coins}}" class="layui-input">

                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">实际价格：</label>
                <div class="layui-input-inline">

                    <input placeholder="实际价格" value="{{=d.total_coins}}" class="layui-input">

                </div>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" id="cover-img">
    <img  src="{{d.image_url}}" onclick="url_cover_show('{{=d.image_url}}')"/>
</script>
<script type="text/html" id="topic-price">
    实际金币：{{d.coins}}<br/>
    原始金币：{{d.origin_coins}}
</script>
<script type="text/html" id="topic-info">
    标题：{{d.title}}<br/>
    数量：{{d.video_count}}<br/>
    描述：{{d.desp}}
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        //delALlUrl: '<?php //echo url_backend("delAll") ?>//',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id',width: 60}
            , {field: 'image', title: '合集图片',templet:"#cover-img"}
            , {field: 'uid', title: '用户uid'}
            , {field: 'coins', title: '价格',templet:"#topic-price",width: 120}
            , {field: 'title', title: '合集信息',templet:"#topic-info",width: 150}
            , {field: 'like_count', title: '点赞量',sort: true}
            , {field: 'play_count', title: '播放量',sort: true}
            , {field: 'refresh_at', title: '更新时间',sort:true,templet: function (d) {
                    return d.refresh_at_str
                }}
            , {field: 'status_str', title: '状态'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event:{
            "toolbar": {
                "refresh": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    layer.confirm('确认需要更新?', function (index) {
                        layer.close(index);
                        ajax.post("<?php echo url_backend('refresh')?>")
                            .then(function (json) {
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, Util.reload);
                                }
                            })
                    });
                },
            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>