<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理<span
                            style="color:palevioletred;font-weight: bold">排序按降序排列</span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]',
                                    merge_array(['' => '全选'], OriginalModel::STATUS_TIPS)) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">资源id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[source_id]" placeholder="请输入" autocomplete="source_id"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <!--  <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <!--  <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>-->
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <label class="layui-form-label">标题：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="标题" name="title" value="{{=d.title }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">演员：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="演员" name="actors" value="{{=d.actors }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">封面：</label>
            <?php echo Layui::uploadPos('cover_full', 'cover', 40, 40) ?>
        </div>

        <div class="layui-form-item">

                <label class="layui-form-label">简介：</label>
                <div class="layui-input-block">
                    <input placeholder="简介" name="desc"
                           value="{{=d.desc }}" class="layui-input">

                </div>

        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            // {type: 'checkbox', fixed: 'left'}
            {field: 'id', title: 'id', sort: true, width: 90}
            , {field: 'title', title: '标题',width: 120}
            , {field: 'desc', title: '简介',width: 120}
            , {title: '属性', templet:"#info-list",width: 120}
            , {
                field: 'cover', width: 120, title: '图片', align: 'center', templet: function (d) {
                    if (d.cover_full) {
                        return '<div onclick="show_img(\'' + d.cover_full + '\')" ><img width="50" src="' + d.cover_full + '" /></div>';
                    }
                    return '';
                }
            }
            , {field: 'category', title: '分类'}
            , {field: 'tags', title: '标签'}
            , {field: 'like_count', title: '点赞数', sort: true, edit: true, width: 70}
            , {field: 'play_count', title: '播放数', sort: true, edit: true, width: 70}
            , {field: 'com_count', title: '评论数', sort: true, edit: true, width: 70}
            , {field: 'pay_count', title: '购买数', sort: true, edit: true, width: 70}
            , {field: 'status', title: '状态', type: "switch", value: "1|0", edit: true, width: 120}
            , {field: 'created_at', title: '创建时间'}
            , {field: 'source_id', title: '资源id'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<script type="text/html" id="info-list">
    系列:{{ d.is_series_str}}<br/>
    集数:{{ d.video_num}}<br/>
    演员:{{ d.actors}}<br/>
    导演:{{ d.directors}}<br/>
    国家:{{ d.country}}<br/>
    语言:{{ d.langs}}<br/>
    上映年:{{ d.year_released}}<br/>
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>