<?php

use traits\AjaxResponseTrait;
use traits\DefaultActionTrait;
use traits\RBACVerifyTrait;
use traits\ActionAopTrait;

/**
 * 后台基础控制器
 * Class BaseController
 * @author xiongba
 * @date 2019-11-09 18:00:51
 */
abstract class BackendBaseController extends AdminController
{
    use ActionAopTrait,
        AjaxResponseTrait,
        DefaultActionTrait;

    /**
     * @author xiongba
     * @date 2020-02-26 14:17:23
     */
    public function init()
    {
        if ('product' == APP_ENVIRON && MODULE_NAME == 'admin' && !in_array(md5(USER_IP), checkWhiteList())) {
            header("Status: 503 Service Unavailable");
            exit(0);
        }
        defined('IS_FAKE_CLIENT') or define('IS_FAKE_CLIENT', false);
        parent::init();
        //IP 登陆白名单
        define('VIEW_PATH', config('application.directory') . '/modules/Admin/views');
        $this->callAopBefore();
    }

    public function __destruct()
    {
        $this->callAopAfter();
    }

    protected function display($tpl = null, array $parameters = null)
    {
        if (is_array($tpl)) {
            $parameters = $tpl;
            $tpl = null;
        }
        if ($tpl == null) {
            $tpl = sprintf("%s/%s", $this->getRequest()->controller, $this->getRequest()->action);
        }
        if (false === strpos($tpl, '.')) {
            $tpl .= '.phtml';
        }
        $tpl = strtolower($tpl);
        return $this->getView()->display($tpl, $parameters);
    }

    public function getView()
    {
        $view = parent::getView(); // TODO: Change the autogenerated stub
        return $view;
    }

    private $addFunction = false;

    protected function render($tpl, array $parameters = null)
    {
        return $this->getView()->render($tpl, $parameters);
    }

    protected function xssDecode($fields = [])
    {
        if (empty($fields)){
            $_GET = xss_decode($_GET);
            $_POST = xss_decode($_POST);
            $_COOKIE = xss_decode($_COOKIE);
            $_REQUEST = xss_decode($_REQUEST);
        }
        foreach ($fields as $field) {
            if (isset($_GET[$field])) {
                $_GET[$field] = xss_decode($_GET[$field]);
            }
            if (isset($_POST[$field])) {
                $_POST[$field] = xss_decode($_POST[$field]);
            }
            if (isset($_COOKIE[$field])) {
                $_COOKIE[$field] = xss_decode($_COOKIE[$field]);
            }
            if (isset($_REQUEST[$field])) {
                $_REQUEST[$field] = xss_decode($_REQUEST[$field]);
            }
        }
    }

}