<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">操作账号</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[username]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">操作动作</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[action]' , AdminLogModel::ACTION) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">操作IP</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[ip]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <!-- <div class="layui-btn-container">
                             <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                 添加
                             </button>
                             <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                         </div>-->
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>
                        <!--<a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>-->
                        <!--<a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>-->
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" class="data-dialog" id="user-data-dialog" data-h="780" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息详细</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">

            <label class="layui-form-label">ID：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.id }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">操作则账号：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.username }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">操作动作：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.action }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">操作IP：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.ip }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">操作详情：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.log }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">操作url来源：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.referrer }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">操作http：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.context }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">操作时间：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.created_at }}" class="layui-input">
            </div>

        </div>
    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        //saveUrl: '<?php echo url_backend("save") ?>',
        //delUrl: '<?php echo url_backend("del") ?>',
        //delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            //{type: 'checkbox', fixed: 'left'}
            {field: 'id', title: 'ID', width: 100}
            , {field: 'username', title: '操作则账号', width: 100}
            , {field: 'action', title: '操作动作', width: 100}
            , {field: 'ip', title: '操作ip', width: 150}
            , {field: 'log', title: '操作详情'}
            /*, {field: 'referrer', title: '操作url来源'}*/
            /* , {field: 'context', title: '操作http上下文,含有cookie,post,get'}*/
            , {field: 'created_at', title: '操作时间', width: 180}
            , {fixed: 'right', width: 100, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<script type="text/javascript" src="<?php echo LAY_UI_STATIC ?>/data-list.js"></script>
<?php importView("fooler.phtml"); ?>