<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">uid</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[status]', MvSubmitModel::STAT) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <div class="operate-toolbar">
                            <a lay-event="edit" lay-form="user-add-dialog">修改</a>
                            {{# if (d.status==0) { }}
                            | <a lay-event="pass" data-pk="{{d.id}}">通过</a> |
                            <a lay-event="reject" data-pk="{{=d.id}}" lay-form="user-refuse-dialog">拒绝</a>
                            {{# } }}

                        </div>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" class="data-dialog" id="user-refuse-dialog" data-h="480" data-w="700" layer-dialog="确认,取消"
        data-option="{title:'拒绝申请',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">选择拒绝的理由：</label>
            <div class="layui-input-block">
                <select name="refused" class="refused layui-select" id="refused" data-id="{{d.id}}">
                    <option value="">选择拒绝理由</option>
                    <option value="您上传的视频含有水印，语音，道具植入等广告或联系方式。">1.您上传的视频含有水印，语音，道具植入等广告或联系方式。</option>
                    <option value="您上传的视频可能是重复的，如果是原创请加上手势或小卡片再次上传">2.您上传的视频可能是重复的，如果是原创请加上手势或小卡片再次上传。</option>
                    <option value="您上传的视频质量、清晰度还不够好，建议在丰富一下内容再次上传">3.您上传的视频质量、清晰度还不够好，建议在丰富一下内容再次上传</option>
                    <option value="您上传的视频过短，看不到内容/没有声音/主题，请上传新的内容。">4.您上传的视频过短，看不到内容或者没有声音或者是主题，请上传新的内容。</option>
                    <option value="您上传的视频的内容标题和主题不符，请修改后上传。">5.您上传的视频的内容标题和主题不符，请修改后上传。</option>
                    <option value="您上传的视频不适用成人搜同片，请更换内容重新上传">6.您上传的视频不适用成人搜同片，请更换内容重新上传</option>
                    <option value="您上传的视频,标签与视频内容不符">7.您上传的视频,标签与视频内容不符</option>
                    <option value="您上传的内容与定价不符，请调整定价后重新上传">8.您上传的内容与定价不符，请调整定价后重新上传</option>
                    <option value="您上传的封面图质量、清晰度还不够好">9.您上传的封面图质量、清晰度还不够好</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <input type="hidden" name="status" value="<?php echo MvModel::STAT_REFUSE ?>">
            <button class="layui-btn submit" lay-submit="" lay-filter="refuseUserUpload"></button>
        </div>
    </form>
</script>
<script type="text/html" class="data-dialog" id="user-add-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <label class="layui-form-label">影片标题：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="影片标题" name="title"
                       value="{{=d.title }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户id：</label>
                <div class="layui-input-inline">
                    <input placeholder="用户id" name="uid" value="{{d.uid||4888000 }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">影片标签：</label>
            <div class="layui-input-block">
                <div id="adminrole_div" class="xtree_contianer" style="margin-bottom: 10px"></div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">竖版封面：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('y_cover_url', 'y_cover', 40, 40, 'xiao') ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面小图：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('cover_thumb_url', 'cover_thumb', 40, 40, 'xiao') ?>
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面宽：</label>
                <div class="layui-input-inline">
                    <input placeholder="封面宽" name="thumb_width" value="{{d.thumb_width||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">封面高：</label>
                <div class="layui-input-inline">
                    <input placeholder="封面高" name="thumb_height" value="{{d.thumb_height||0 }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面动图：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('img_gif_thumb', 'gif_thumb', 40, 40, 'xiao') ?>
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">动图宽：</label>
                <div class="layui-input-inline">
                    <input placeholder="动图宽" name="thumb_width" value="{{d.gif_width||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">动图高：</label>
                <div class="layui-input-inline">
                    <input placeholder="动图高" name="thumb_height" value="{{d.gif_height||0 }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">影片资源：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadFile(url_backend('upload/uploadMp4'), 'm3u8') ?>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">完整视频资源：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadFile(url_backend('upload/uploadMp4'), 'full_m3u8') ?>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">影片时长：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="时长，秒" name="duration" value="{{=d.duration }}"
                           class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">定价：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="定价" name="coins" value="{{d.coins||0 }}"
                           class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">会员价：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="定价" name="vip_coins" value="{{d.vip_coins||-1 }}"
                           class="layui-input">
                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">评论数：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="评论数" name="comment" value="{{d.comment||0 }}"
                           class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">喜欢数：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="喜欢点击数" name="like" value="{{d.like||0 }}"
                           class="layui-input">
                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">是否限免：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="是否限免 0 收费 1 限免" name="is_free"
                           value="{{d.is_free||1 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">隐藏：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="0显示1隐藏" name="is_hide" value="{{d.is_hide||0 }}"
                           class="layui-input">
                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">点击数：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="总历史点击数" name="rating" value="{{d.rating||0 }}"
                           class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('status', MvSubmitModel::STAT, ['data-value' => '{{=d.status}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">精彩时长：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="精彩时长：秒" name="thumb_duration"
                           value="{{d.thumb_duration||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">开始时间：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="精彩片段开始时间" name="thumb_start_time"
                           value="{{d.thumb_start_time||0 }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<style>
    .layui-table-cell {
        height: 50px;
        line-height: 50px
    }


    .layui-xtree-item {
        display: inline-block;
        width: 80px;
    }
</style>
<script src="<?php echo LAY_UI_STATIC ?>layuiadmin/layui-xtree.js"></script>
<script id="bbbb" type="text/html">
<p>总审核:&nbsp;{{d.video_count}}</p>
<p>被拒绝:&nbsp;{{=d.refuse_rate}}</p>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>&where[status]=0',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', width: 120, title: 'id'}
            , {
                field: 'uid', title: 'uid', width: 160, templet: function (d) {
                    return d.nickname + '[' + d.uid + ']';
                }
            }
            , { field: 'uid', title: '比例', width: 110, templet: '#bbbb' }
            , {field: 'coins', width: 80, title: '金币', edit: true}
            , {
                field: 'cover_thumb', title: '封面小图', width: 80, templet: function (d) {
                    return '<img src="' + d.cover_thumb_url + '" style="width: 40px;height: 40px;" onclick="show_img(\'' + d.cover_thumb_url + '\')">';
                }
            }
            , {
                field: 'cover_thumb', width: 100, title: '播放源', templet: function (d) {
                    return "<a class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.href + "')\"><i class='layui-icon layui-icon-play'></i>MP4</a>"
                }
            }
            , {field: 'status', title: '状态', 'type': 'enum', 'value': <?php echo json_encode(MvModel::STAT)  ?>}
            , {
                field: 'title', title: '影片', templet: function (d) {
                    return "<p style='color: #0e9aef'>标题: " + d.title + "</p><p style='color: #2a6496'>标签: " + d.tags + "</p>";
                }
            }
            , {field: 'created_str', width: 150, title: '提交时间'}
            , {fixed: 'right', width: 140, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "done": function (table, data, from, ajax, tpl, $) {
            ajax.get("<?php echo url_backend('mv/tagsList')?>")
                .then(function (json) {
                    return json.data;
                })
                .then(function (data) {
                    xx.use({"menu": data})
                })
        }
        , event: {

            "operate": {
                edit: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                },
                pass: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('确定要通过吗?', function (index2) {
                        ajax.post("<?php echo url_backend('pass')?>", {"_pk": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index2);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, function () {
                                        obj.del();
                                    });
                                }
                            })
                    });
                },
                reject: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn(undefined, function (layerIndex) {
                        Util.formSubmit("<?php echo url_backend('refuseUserUpload')?>", form, ajax, 'refuseUserUpload', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    obj.del();
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                }
            }
            , "renderTree": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                console.log("renderTree");
                console.log(obj.data);

                let ruleArray = [], menudata = xx.config('menu'), treeJson = [];
                console.log("menudata");
                console.log(menudata);
                if (typeof (obj.data) !== "undefined") {
                    ruleArray = obj.data.tags_list
                }
                $.each(menudata, function (i, item, data) {
                    data = {
                        "inputname": 'tags[]',
                        "title": item,
                        "value": item,
                        "checked": in_array(item, ruleArray),
                        "data": [],
                    };
                    treeJson.push(data);
                });
                nextFn();
                Util.renderSelect(obj.data, $, form);
                new layuiXtree({
                    elem: 'adminrole_div'
                    , form: form
                    , data: treeJson
                });
            }
        }
    })
    ;
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>