#!/usr/bin/env php

<?php
use Yaf\Request\Simple;

set_time_limit(0);
ini_set('memory_limit', '-1');
define('IN_APP', true);
define('MODULE_NAME_TEST', '');
define('MODULE_NAME', '');
define("APP_PATH", realpath(__DIR__)); // public 上级目录

date_default_timezone_set('Asia/Shanghai');


try {
    $file = APP_PATH . "/conf/app.ini";
    $app = new Yaf\Application($file);
    $app->bootstrap()
        ->getDispatcher()
        ->dispatch(new Simple('cli', null, 'Console', 'main', $argv));
} catch (\Throwable $e) {
    throw $e;
}
