<?php include __DIR__ . "/../layout/header.phtml"; ?>
<style>
    .max40 {
        width: 100px;
        max-width: 200px;
        word-wrap: break-word;

    }
</style>
<script>
    function layerOpen(url, title) {
        layer.open({
            type: 2,
            title: title,
            closeBtn: 1,
            shadeClose: true,
            shade: [0.5],
            area: ['600px', '600px'],
            content: url
        })
    }

    function layerOpenRt(url, title) {
        layer.open({
            type: 2,
            title: title,
            closeBtn: 1,
            shadeClose: true,
            anim: 3, offset: 'rt',
            shade: [0.5],
            area: ['1200px', '800px'],
            content: url
        })
    }

    function doReportEdit(id) {
        var url = "/d.php?mod=reports&code=reply&id=" + id;
        layerOpen(url, '工单回复')
    }


    function doSetStatus(id) {
        $.ajax({
            url: '/d.php?mod=reports&code=setstatus&id=' + id,
            type: 'GET',
            success: function (res) {
                if (res.status == 1) {
                    layer.msg(res.data, {icon: 1})
                    $('#trd-' + id).css('display', 'none');
                } else {
                    layer.msg(res.data, {icon: 5})
                }

            }
        })
    }

</script>

<div class="wrap">
    <form class="well form-search" method="get" action="/d.php">
        <input type="hidden" name="mod" value="reports">
        <input type="hidden" name="code" value="index">
        状态：
        <select class="select_2" name="status">
            <option value="">全部</option>
            <option value="0" <?php if ($formget['status'] == '0'): ?> selected<?php endif; ?> >处理中</option>
            <option value="1" <?php if ($formget['status'] == '1'): ?> selected<?php endif; ?> >已处理</option>
        </select>
        提交时间：
        <input type="text" class="input-sm form-control input-s-sm inline" readonly id="start_time" name="start_time"
               value="<?= $formget['start_time'] ?? ''; ?>" style="width: 150px;" autocomplete="off">-
        <input type="text" class="input-sm form-control input-s-sm inline" readonly id="end_time" name="end_time"
               value="<?= $formget['end_time'] ?? ''; ?>" style="width: 150px;" autocomplete="off"> &nbsp; &nbsp;
        UID:
        <input type="text" name="uid" style="width: 200px;" value="<?= $formget['uid'] ?? ''; ?>" placeholder="uid">
        UUID:
        <input type="text" name="uuid" style="width: 200px;" value="<?= $formget['uuid'] ?? ''; ?>" placeholder="uuid">
        关键字
        <input type="text" name="keyword" style="width: 200px;" value="<?= $formget['keyword'] ?? ''; ?>"
               placeholder="请输入会员姓名、手机">
        <input type="submit" class="btn btn-primary" value="搜索">
    </form>
    <form method="post" class="js-ajax-form">


        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th align="center">ID</th>
                <th>会员</th>
                <th>UUID</th>
                <!--	<th>手机型号</th>-->
                <th class="max40">反馈信息</th>
                <th>图片</th>
                <th class="max40">回复信息</th>
                <th>状态</th>
                <th>提交时间</th>
                <th>处理时间</th>
                <th align="center">操作</th>
            </tr>
            </thead>
            <tbody>
            <?php $status = ["0" => "处理中", "1" => "已处理", "2" => "审核失败"]; ?>
            <?php foreach ($data as $vo): ?>
                <tr id="trd-<?= $vo->id; ?>">
                    <td align="center"><?= $vo->id; ?></td>
                    <td><?php if ($vo->withMember): ?><?= $vo->withMember->username ?> (<?= $vo->withMember->uid; ?> )<?php else: ?> 用户不存在<?php endif; ?></td>
                    <td><?php if ($vo->withMember): ?>
                            <?= $vo->withMember->uuid ?>
                            (<a href="javascript:;" onclick="layerOpenRt('/d.php?mod=product&code=listOrders&uuid=<?= $vo->withMember->uuid ?>&page=1','<?= $vo->withMember->uuid ?>的订单')">订单</a>&nbsp;|&nbsp;<a href="javascript:;" onclick="layerOpenRt('/d.php?mod=members&code=indexInfo&where[uid]=<?= $vo->withMember->uid ?>','<?= $vo->withMember->uuid ?>的信息')">用户</a>)

                        <?php endif; ?></td>
                    <!--	<td><? /*=$vo['oauth_type']*/ ?></td>-->
                    <td class="max40"><?= nl2br(htmlspecialchars($vo['content'])); ?></td>
                    <td>
                        <?php if (!empty($vo['thumb'])): ?>
                            <img onclick="show_img('<?= url_live($vo['thumb']); ?>')"
                                 src="<?= url_live($vo['thumb']); ?>" style="max-width:100px;max-height:100px;">
                        <?php endif; ?>
                    </td>
                    <td><?php if ($vo->withReply): ?><?= $vo->withReply->content ?> (<?= $vo->withReply->uid; ?> )<?php else: ?> 未回复<?php endif; ?></td>
                    <td><?= $status[$vo['status']] ?></td>
                    <td><?= date("Y-m-d H:i:s", $vo['addtime']); ?></td>
                    <td>
                        <?php if ($vo['status'] = '0'): ?>
                            处理中
                        <?php else: ?>
                            <?= $vo['uptime'] ? date("Y-m-d H:i:s", $vo['uptime']) : ''; ?>
                        <?php endif; ?>
                    </td>

                    <td align="center">
                        <if condition="$vo['status'] eq '0'">
                            <a onclick="doSetStatus('<?= $vo['id'] ?>')">标记处理</a> |
                        </if>
                        <if condition="$vo['status'] eq '0'">

                            <a onclick="doReportEdit('<?= $vo['id'] ?>')">回复</a> |
                        </if>
                        <a href="/d.php?mod=Reports&del&id=<?= $vo['id'] ?>" class="js-ajax-dialog-btn"
                           data-msg="您确定要删除吗？">删除</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class="pagination"><?= $page_arr['html'] ?></div>

    </form>
</div>
<script type="text/javascript">

    $(function () {

        layui.laydate.render({
            elem: '#end_time',
            event: 'click', //触发事件
            format: 'yyyy-MM-dd', //日期格式
            istime: true, //是否开启时间选择
            type: 'date'
        });
        layui.laydate.render({
            elem: '#start_time',
            event: 'click', //触发事件
            format: 'yyyy-MM-dd', //日期格式
            istime: true, //是否开启时间选择
            type: 'date'
        });


    })

</script>
