<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理 <span id="total-id" style="color: red"></span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">用户ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>


                        <div class="layui-inline">
                            <label class="layui-form-label">平台</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[platform]', merge_array(['' => '请选着'], FeedbackModel::PLAT)) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]', merge_array(['' => '请选着'], FeedbackModel::STATUS)) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                             <button class="layui-btn layui-btn-sm" lay-event="batch_reply">
                                 批量回复
                             </button>
                            <!--<button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">批量回复</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <div class="operate-toolbar">
                            <a style="color: orangered" lay-event="recoveryUser" data-pk="{{d.uid}}">恢复sg</a>  |
                            <a onclick="doReportEdit('{{=d.id}}')">回复</a> |
                            <a lay-event="setstatus" data-pk="{{d.id}}">
                                标记处理
                            </a>
                            {{# if(d.user_uuid) { }}
                            <br>
                            <a lay-event="addVip" lay-form="user-vip-dialog">加vip</a> |
                            <a href="javascript:;"
                               onclick="layerOpenRt('/d.php?mod=orders&code=index&uuid={{d.user_uuid}}&page=1','{{d.user_uuid}}的订单')">订单</a>&nbsp;|&nbsp;
                            <a href="javascript:;"
                               onclick="layerOpenRt('/d.php?mod=members&code=indexInfo&where[uid]={{d.uid}}','{{d.user_uuid}}的信息')">用户</a>&nbsp;|&nbsp;
                            <a lay-event="clearCached" data-pk="{{d.uid}}">缓存</a>
                            {{# } }}

                        </div>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户ID：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="用户ID" name="uid"
                           value="{{=d.uid }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">标题：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="标题" name="title"
                           value="{{=d.title }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">系统版本号：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="系统版本号" name="version"
                           value="{{=d.version }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">设备：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="设备" name="model"
                           value="{{=d.model }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">内容：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="内容" name="content"
                           value="{{=d.content }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">提交时间：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="提交时间" name="addtime"
                           value="{{=d.addtime }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="状态" name="status"
                           value="{{=d.status }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">更新时间：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="更新时间" name="uptime"
                           value="{{=d.uptime }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">图片：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="图片" name="thumb"
                           value="{{=d.thumb }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户ID：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.uid }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">标题：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.title }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">系统版本号：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.version }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">设备：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.model }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">内容：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.content }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">提交时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.addtime }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.status }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">更新时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.uptime }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">图片：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.thumb }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>

<script type="text/html" id="thumb-url">

</script>
<script type="text/html" id="user-info">
    <span style="color: green">#{{d.uid}}</span>,{{# if(!d.user_uuid.length) { }}
    <span style="color: red"> 用户已注销</span>
    {{# } else { }}
    {{d.user_nickname.length ? d.user_nickname : d.user_uuid}}
    {{# } }}<br>
    {{d.user_uuid}}
</script>
<script type="text/html" id="user-content">
    <div>
        {{# if(d.thumb) { }}
        <img onclick="show_img('{{d.thumb}}')" src="{{d.thumb}}" style="margin-right:10px;max-width:80px;max-height:80px;display: block;float:left;">
        {{# } }}
        {{# if(d.content) { }}
        <span>Q： {{=d.content}}</span><br>
        {{# } }}
        {{# if(d.reply) { }}
        <span>A： {{d.reply}}</span>
        {{# } }}
    </div>

    <br>
</script>


<script type="text/html" class="data-dialog" id="user-vip-dialog" data-h="520" data-w="600" layer-dialog="确认,取消"
        data-option="{closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">用户id：</label>
            <div class="layui-input-inline">
                <input disabled value="{{=d.uid }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">VIP类型：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('vip_level', MemberModel::USER_VIP_TYPE,
                    ['data-value' => '{{=d.vip_level}}']) ?>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">添加天数：</label>
            <div class="layui-input-block">
                <input type="text" name="expired_at" value="{{=d.expired_at}}" placeholder="添加天数，格式：30" autocomplete="off"  class="layui-input x-date">
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.uid}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" id="user-time">
    提交：{{=d.addtime_str}}<br>
    处理：{{# if(0!=d.reply.length) { }}{{=d.replyat_str}}{{# } else { }}<span style="color: red">未处理</span>{{# } }}
</script>

<script>
    function doReportEdit(id) {
        var url = "/d.php?mod=reports&code=reply&id=" + id;
        layer.open({
            type: 2,
            title: '工单回复',
            closeBtn: 1,
            shadeClose: true,
            shade: [0.5],
            area: ['700px', '700px'],
            content: url
        })
    }


    function layerOpenRt(url, title) {
        layer.open({
            type: 2,
            title: title,
            closeBtn: 1,
            shadeClose: true,
            anim: 3, offset: 'rt',
            shade: [0.5],
            area: ['1200px', '800px'],
            content: url
        })
    }

    post_coins = function (uid, type) {
        uid = parseInt(uid);

        if (!uid || typeof (uid) !== "number") {
            Util.msgErr('用户不存在');
            return;
        }
        $.post("/d.php?mod=chargeAdmin&code=post_edit", {
            "uid": uid,
            "type": type,
            "number": "<?php echo $coins_uint?>",
            "des": "客服工单上下分",
        })
            .then(function (json) {
                if (json.code) {
                    Util.msgErr('操作失败');
                } else {
                    Util.msgOk('操作成功');
                }
            })
    }

    function up_coins(uid) {
        layer.confirm('对用户加【<?php echo $coins_uint?>】金币?', function (index) {
            layer.close(index);
            post_coins(uid, 1);
        });
    }

    function down_coins(uid) {
        layer.confirm('对用户减【<?php echo $coins_uint?>】金币?', function (index) {
            layer.close(index);
            post_coins(uid, 2);
        });
    }

    xx.use({
        url: '<?php echo url_backend("listAjax") ?>&where[status]=0',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id', width: 80}
            , {field: 'uid', title: '用户', templet: '#user-info', width: 280}
            // , {field: 'thumb', title: '图片', templet: '#thumb-url', width: 120}
            , {field: 'content', title: '反馈', templet: '#user-content'}
            , {
                field: 'platform',
                title: '平台',
                width: 80,
                type: 'enum',
                'value':<?php echo json_encode(FeedbackModel::PLAT)?>}
            , {field: 'addtime_str', title: '提交时间', width: 160, templet: '#user-time'}
            //, {field: 'replyat_str', title: '处理时间', width: 110}
            , {
                field: 'status',
                title: '状态',
                width: 80,
                type: 'enum',
                'value':<?php echo json_encode(FeedbackModel::STATUS)?>}
            // , {field: 'uptime', title: '更新时间'}

            , {fixed: 'right', width: 180, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "done": function (table, _id, form, HTTPUtil, laytpl, $,res) {
            window.$ = $;
            $('span#total-id').text(res.desp)
        },
        event: {
            "toolbar": {
                "batch_reply": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(event.config.id), pkValAry = checkStatus.data.map(function (vv){
                        return vv.id
                    });
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    var index = layer.prompt({"title": "回复的内容", formType: 2, area: ['250px', '80px']}, function (val) {
                        layer.close(index);
                        ajax.post("<?php echo url_backend('batch_reply')?>", {"ids": pkValAry.join(',') , 'body':val})
                            .then(function (json) {
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, Util.reload);
                                }
                            })
                    });
                }
            },
            "operate": {
                addVip: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn(undefined, function (layerIndex) {
                        Util.formSubmit("<?php echo url_backend('members/addvip')?>", form, ajax, undefined, function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg);
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                setstatus: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    ajax.post("<?php echo url_backend('setstatus')?>", {"id": $this.data('pk')})
                        .then(function (json) {
                            if (json.code) {
                                Util.msgErr(json.msg);
                            } else {
                                layer.msg(json.msg, {time: 500}, function () {
                                    obj.del();
                                });
                            }
                        })
                },
                "clearCached": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    let $this = $(this), data = {"uid": $this.data('pk')};
                    ajax.post('<?php echo url_backend('members/clearCached')?>', data)
                        .then(function (json) {
                            Util.msgOk('操作成功');
                        })
                },
                recoveryUser: function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    let $this = $(this), data = {"uid": $this.data('pk')};
                    layer.confirm('确定要恢复用户['+$this.data('pk')+']的VIP吗?', function (index) {
                        layer.close(index);
                        ajax.post('<?php echo url_backend('recoveryuser')?>', data)
                            .then(function (json) {
                                Util.msgOk(json.msg);
                            })
                    });
                },
            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>