<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">用户</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[uuid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[status]', FindModel::STAT) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="created-dialog">
                                添加
                            </button>
<!--                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">-->
<!--                                添加-->
<!--                            </button>-->
<!--                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <div class="operate-toolbar">
                            <a lay-event="review" lay-form="status-dialog">
                                状态
                            </a> |
                            <a lay-event="edit" lay-form="user-edit-dialog">修改</a> <br>
                            {{#  if(d.member && d.member.role_id == <?php echo MemberModel::ROLE_NORMAL ?>){ }}
                            <a data-pk="{{=d.member.uid}}" data-flag="forbidden" lay-event="checkplus">封禁</a> |
                            {{#  } }}
                            <a lay-event="refresh" data-pk="{{=d.id}}" >刷新缓存</a> |
                            <a lay-event="yijianqinli" data-uuid="{{=d.uuid}}" >一键清理</a>
                            <!--                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">-->
                            <!--                            <i class="layui-icon layui-icon-delete"></i>删除</a>-->
                        </div>

                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-h="300" data-w="500" layer-dialog="确认,取消"
        data-option="{full:false}">

    <form class="layui-form form-dialog" action="" lay-filter="form-save" style="margin-top: 20px;">
        <div class="layui-form-item">

            <label class="layui-form-label">求片描述：</label>
            <div class="layui-input-block">
                <textarea lay-verify="required" placeholder="求片描述" name="title"
                          class="layui-textarea">{{=d.title }}</textarea>
            </div>
        </div>


        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="status-dialog" data-h="480" data-w="700" layer-dialog="确认,取消"
        data-option="{title:'拒绝申请',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">
                <?php echo Layui::radioMulti('status', FindModel::STAT); ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="updateStatus"></button>
        </div>
    </form>
</script>

<script type="text/html" class="data-dialog" id="created-dialog" data-h="780" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <label class="layui-form-label">用户：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="用户uuid" name="uuid" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">发片赏金：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="发片赏金" name="coins"
                       value="{{=d.coins }}" class="layui-input">

            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">求片描述：</label>
            <div class="layui-input-block">
                <textarea placeholder="求片描述" name="title" class="layui-textarea"></textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">求片引用：</label>
            <div class="layui-input-block">
                <input placeholder="视频id" name="vid" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">
                <?php echo Layui::radioMulti('status', FindModel::STAT); ?>
            </div>
        </div>


        <hr>
        <div class="layui-form-item">
            <label class="layui-form-label">图片1：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadPos('image_1', 'url_1'); ?>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">图片2：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadPos('image_2', 'url_2'); ?>

            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">图片3：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadPos('image_3', 'url_3'); ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script type="text/html" id="imt-list">
        <div class="td-cover-title" style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;position: relative">
            {{#  layui.each(d.images, function(index, item){ }}
            <img onclick="show_img('{{item}}')"  width="50" height="50" src="{{item}}">
            {{#  }); }}
        </div>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: undefined,
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
          /*  {type: 'checkbox', fixed: 'left'}*/
             {field: 'id', title: 'id',width: 80}
            , {field: 'uuid', width: 275, title: '用户', templet: "#member-basis"}
            , {field: 'title', title: '求片描述',width: 300}
            , {field: 'status_str', title: '状态'}
            , {field: 'img_list',width: 270, title: '图片', templet: "#imt-list"}
            , {
                field: 'mv_title', width: 100, title: '视频信息', templet: function (d) {
                    if (d.vid) {
                        return "<a title='" + d.mv_title + "' class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.mv_pre_href + "')\"><i class='layui-icon layui-icon-play'></i>" + d.vid + "</a>";
                    } else {
                        return '';
                    }
                }
            }
            , {field: 'is_top', title: '置顶',width: 100,type:'switch',value:'1|0',edit:true,sort:true}
            , {field: 'like', title: '想看',width: 80}
            , {field: 'reply', title: '回复',width: 80}
            , {field: 'coins', title: '赏金',width: 80}
            , {field: 'total_coins', title: '累计赏金',width: 80}
            , {field: 'created_str', width: 170, title: '创建时间'}
            , { fixed: 'right', width: 220, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "event": {
            "toolbar": {
                "addUser": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                    nextFn();
                    form.on('submit(create_data)', function (data){
                        console.log(data);
                        let images = [] , eleAry = $('input[name=url_1],input[name=url_2],input[name=url_3]');
                        for (let j = 0; j <eleAry.length ; j++) {
                            let vv = eleAry.eq(j);
                            let img = new Image();
                            img.src = $(vv).prev().attr('src');
                            if (img.height && img.width && $(vv).val()) {
                                images.push($(vv).val())
                            }
                        }
                        let field = data.field;
                        field.images = JSON.stringify(images);
                        let i = layer.load(0, {time: 6 * 1000, shade: [0.5, '#000']});
                        ajax.post('<?php echo url('save')?>', data.field).then(function (json) {
                            layer.close(i);
                            if (json.code) {
                                Util.msgErr(json.msg);
                            } else {
                                Util.msgOk(json.msg, obj.reload);
                            }
                        });
                        return false;
                    });
                }
            },
            "operate": {
                "checkplus": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    //var tr_index = $this.parents("tr").attr('data-index');
                    layer.confirm('您确定要封禁吗？', {
                        btn: ['确定', '取消']
                    }, function (index) {
                        ajax.post("<?php echo url_backend('/members/checkplus')?>", {"id": $this.data('pk'), "flag": $this.data('flag')})
                            .then(function (json) {
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg);
                                    table.reload('gridTab');
                                }
                                layer.close(index);
                            });
                    });

                },
                "refresh": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('您确定要刷新缓存吗？', {
                        btn: ['确定', '取消']
                    }, function (index) {
                        ajax.post("<?php echo url_backend('refresh')?>", {"id": $this.data('pk')})
                            .then(function (json) {
                                Util.msgOk('缓存已刷新');
                                layer.close(index);
                            });
                    });
                },
                "yijianqinli": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    //var index = layer.load(0, {time: 3 * 1000, shade: [0.5, '#666']});
                    var $this = $(this);
                    layer.confirm('您确定要一键清理吗？', {
                        btn: ['确定', '取消']
                    }, function (index) {
                        ajax.post("<?php echo url_backend('clear_all')?>", {"uuid": $this.data('uuid')})
                            .then(function (json) {
                                Util.msgOk('一键清理', function (){
                                    table.reload("gridTab");
                                });
                                layer.close(index);
                            });
                    });
                },
                'review': function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn(undefined, function (layerIndex) {
                        Util.formSubmit("<?php echo url_backend('status')?>", form, ajax, 'updateStatus', function (json) {
                            console.log(json)
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                }
            },
        }
    });
</script>
<script type="text/javascript" src="<?php echo LAY_UI_STATIC ?>/data-list.js?v=2"></script>
<?php importView("fooler.phtml"); ?>