<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理&nbsp;&nbsp;<span style="color: #FF5722;font-weight: bold">备注：索引值 根据回调类型分为mv_id|订单号|提现单号 </span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">类型</label>
                            <div class="layui-input-block">
                               <?php echo Layui::search('where[type]',NotifyLogModel::TYPE) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">索引值</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[value]" placeholder="mv_id|订单号|提现单号" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                    </script>
                    <script type="text/html" id="operate-toolbar">
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            //{type: 'checkbox', fixed: 'left'} ,
            {field: 'id', title: 'id', width: 100,sort:true}
            , {field: 'value', title: '索引值', width: 200}
            , {field: 'type', title: '类型', width: 80}
            , {field: 'log', title: '内容'}
            , {field: 'create_str', title: '时间', width: 160}
            //, {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>