<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">用户uid</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">活动</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[lottery_id]' , $lotteryAry) ; ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">奖品奖项id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[item_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
<!--                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">-->
<!--                                添加-->
<!--                            </button>-->
<!--                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="log_id">删除所选-->
<!--                            </button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.log_id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'log_id',
        cols: [[
            {field: 'log_id', title: 'ID'}
            , {field: 'uid', title: '用户uid'}
            , {field: 'item_id', title: '奖品奖项id'}
            , {field: 'item_name', title: '奖品名称'}
            // , {field: 'item_icon', title: '奖品图片'}
            , {field: 'lottery_name', title: '活动'}
            , {field: 'giveaway_type_str', title: '奖品类型'}
            , {field: 'giveaway_id', title: '奖品位置'}
            , {field: 'giveaway_num', title: '奖品数量'}
            , {field: 'created_at', title: '创建时间'}
            , {field: 'nickname', title: '用户昵称'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>