<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">常见管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">状态：</label>
                            <div class="layui-input-inline">
                                <?php echo Layui::select('where[status]',
                                    array_merge(['' => '不限'], UserhelperModel::STATUS),
                                    ['data-value' => '{{=d.status}}']) ?>
                            </div>
                        </div>


                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <!-- <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">

                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="800" data-h="600" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">

            <label class="layui-form-label"></label>
            <div class="layui-input-block">
              <span style="color: orangered;font-weight: bold">问题及答案要简单明了，通俗易懂，不要超过250个字</span>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">问题：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="问题描述" name="question"
                       value="{{=d.question }}" class="layui-input">

            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">答案：</label>
                <div class="layui-input-block">
                    <textarea lay-verify="required"  placeholder="答案" style="width: 600px;height: 200px;"  name="answer">
                        {{=d.answer }}
                    </textarea>
                </div>
            </div>
        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('status', UserhelperModel::STATUS, ['data-value' => '{{=d.status}}']) ?>
            </div>

        </div>


        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            /* {type: 'checkbox', fixed: 'left'}*/
            {field: 'id', title: 'id'}
            , {field: 'question', title: '问题描'}
             , {field: 'answer', title: '答案'}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true}
            /*, {field: 'type', title: '1.热点问题/2加载缓存3个人账户4资源内容5分享推广6其他问题'}*/
            , {field: 'created_at', title: '时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>