<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理<span style="color: orangered" class="layui-inline"
                                                       id="total-id"></span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto" lay-filter="order-search">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">用户id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">购买价格</label>
                            <div class="layui-input-block">
                                <?php echo Layui::between("coins") ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">漫画id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[mh_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <!--  <div class="layui-inline">
                              <label class="layui-form-label">类型 购买 次数 赠送</label>
                              <div class="layui-input-block">
                                  <input type="text" name="search[type]" placeholder="请输入" autocomplete="off"
                                         class="layui-input">
                              </div>
                          </div>-->
                        <div class="layui-inline">
                            <label class="layui-form-label">购买时间</label>
                            <div class="layui-input-block">
                                <?php echo Layui::dateBetween('created_at', date("Y-m-d", TIMESTAMP)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>

                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户id：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="用户id" name="uid"
                           value="{{=d.uid }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">购买时的价格：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="购买时的价格" name="coins"
                           value="{{=d.coins }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">漫画id：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="漫画id" name="mh_id"
                           value="{{=d.mh_id }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">类型 购买 次数 赠送：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="类型 购买 次数 赠送" name="type"
                           value="{{=d.type }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">购买时间：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="购买时间" name="created_at"
                           value="{{=d.created_at }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.uid }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">购买时的价格：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.coins }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">漫画id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.mh_id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">类型 购买 次数 赠送：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.type }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">购买时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.created_at }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>
<script type="text/html" id="search-total">
    <p style="font-size: medium">
        找到：{{=d.count}}，条数据,  成功支付金额: {{=d.payedTotal}}
    </p>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id',sort:true}
            , {field: 'uid', title: '用户id'}
            , {field: 'coins', title: '购买时的价格',sort:true}
            , {field: 'zy_id', title: '资源id'}
            //, {field: 'type', title: '类型 购买 次数 赠送'}
            , {field: 'created_at', title: '购买时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event: {
            search: function (ajax, laytpl, where) {
                ajax.get("<?php echo url_backend('total')?>&" + xx.queryEncode(where)).then(function (json) {
                    if (json.code == '0') {
                        let data = json.data, $ = layui.$;
                        $('#total-id').html(laytpl($('#search-total').html()).render(data));
                    }
                });
            }
        }
    });


    layui.use(['form', 'jquery', 'laytpl'], function () {
        let form = layui.form;
        let $ = layui.jquery;
        let laytpl = layui.laytpl;
        let data = form.val('order-search');
        //console.log('order-search'+xx.queryEncode(data))
        $.ajax({
            url: "<?php echo url_backend('total')?>&" + xx.queryEncode(data),
            dataType: 'json',
            success: function (json) {
                //console.log(json.code)
                if (json.code == '0') {
                    let response = json.data;
                    $('#total-id').html(laytpl($('#search-total').html()).render(response));
                }
            }
        });
    })
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>