<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">aff</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[aff]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addLotteryTimes" lay-form="add-lottery-times">添加次数</button>
                        </div>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" class="data-dialog" id="add-lottery-times" data-h="480" data-w="700" layer-dialog="确认,取消"
        data-option="{title:'添加次数',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>添加抽奖次数</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">aff：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="aff" name="aff" value="" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">次数(负数是减少)：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="次数" name="val" value="" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <button class="layui-btn submit" lay-submit="" lay-filter="addLotteryTimes"></button>
        </div>
    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id'}
            , {field: 'aff', title: 'aff'}
            , {field: 'val', title: '抽奖次数'}
            , {field: 'total', title: '总抽奖次数'}
            , {field: 'total_money', title: '活动期间金币充值总金额(元)'}
            , {field: 'created_at', title: '创建时间'}
            , {field: 'updated_at', title: '更新时间'}
        ]],
        event:{
            'toolbar': {
                addLotteryTimes: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn(undefined, function (layerIndex) {
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addLotteryTimes')?>", form, ajax, 'addLotteryTimes', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab")
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>