<?php include __DIR__ . "/../layout/header.phtml";?>
<script src="/static/admin/js/plugins/echarts/echarts.min.js"></script>
<script src="/static/admin/js/plugins/highcharts/highcharts.js"></script>
<script src="/static/admin/js/plugins/highcharts/exporting.js"></script>
<div class="row">
    <div id="gold" style="width: 100%; height:400px;"></div>
</div>
<hr/>
<div class="row">
    <div id="day" style="width:100%; height: 600px;"></div>
</div>
<hr/>
<div class="row">
    <div id="user" style="width:100%; height: 400px;"></div>
</div>
<script type="text/javascript">
    Highcharts.chart('gold', {
        chart: {
            type: 'area'
        },
        title: {
            text: '金币使用图'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            //categories: [<?=$items['date'];?>],
            categories: [<?=$items['date'];?>],
            tickmarkPlacement: 'on',
            title: {
                enabled: false
            }
        },
        yAxis: {
            title: {
                text: ''
            },
            labels: {
                formatter: function () {
                    return this.value;
                }
            }
        },
        tooltip: {
            split: true
        },
        plotOptions: {
            area: {
                stacking: 'normal',
                lineColor: '#666666',
                lineWidth: 1,
                marker: {
                    lineWidth: 1,
                    lineColor: '#666666'
                }
            }
        },
        series: [{
            name: '总获得',
            //data: [<?=$items['add_gold'];?>]
            data: [<?=$items['add_gold'];?>]
        }, {
            name: '总消费',
            // data: [<?=$items['all_spend'];?>]
            data: [<?=$items['all_spend'];?>]
        }, {
            name: '漫画消费',
            // data: [<?=$items['mh_spend'];?>]
            data: [<?=$items['mh_spend'];?>]
        }, {
            name: '动漫消费',
            //data: [<?=$items['dm_spend'];?>]
            data: [<?=$items['dm_spend'];?>]
        }]
    });
    Highcharts.chart('day', {
        chart: {
            type: 'area'
        },
        title: {
            text: '用户行为详情图'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
           // categories: [<?=$items['date'];?>],
            categories: [<?=$items['date'];?>],
            tickmarkPlacement: 'on',
            title: {
                enabled: false
            }
        },
        yAxis: {
            title: {
                text: ''
            },
            labels: {
                formatter: function () {
                    return this.value;
                }
            }
        },
        tooltip: {
            split: true
        },
        plotOptions: {
            area: {
                stacking: 'normal',
                lineColor: '#666666',
                lineWidth: 1,
                marker: {
                    lineWidth: 1,
                    lineColor: '#666666'
                }
            }
        },
        series: [{
            name: '邀请访问',
           // data: [<?=$items['aff'];?>]
            categories: [<?=$items['aff'];?>],
            // data: [<?=$items['date'];?>]
            data: [<?=$items['date'];?>]
        }, {
            name: '分享访问',
           // data: [<?=$items['share'];?>]
            data: [<?=$items['share'];?>]
        }, {
            name: '受邀人数',
           // data: [<?=$items['invited'];?>]
            data: [<?=$items['invited'];?>]
        }, {
            name: '邀请成功',
            //data: [<?=$items['invite'];?>]
            data: [<?=$items['invite'];?>]
        }, {
            name: '今日注册',
            //data: [<?=$items['all_reg'];?>]
            data: [<?=$items['all_reg'];?>]
        }, {
            name: '今日活跃',
           // data: [<?=$items['all_act'];?>]
            data: [<?=$items['all_act'];?>]
        }, {
            name: 'IOS注册',
           // data: [<?=$items['ios_reg'];?>]
            data: [<?=$items['ios_reg'];?>]
        }, {
            name: '安卓注册',
           // data: [<?=$items['and_reg'];?>]
            data: [<?=$items['and_reg'];?>]
        }, {
            name: 'IOS活跃',
            //data: [<?=$items['ios_act'];?>]
            data: [<?=$items['ios_act'];?>]
        }, {
            name: '安卓活跃',
            // data: [<?=$items['and_act'];?>]
            data: [<?=$items['and_act'];?>]
        }]
    });
    Highcharts.chart('user', {
        chart: {
            type: 'area'
        },
        title: {
            text: '用户数'
        },
        subtitle: {
            text: '总用户,IOS用户,安卓用户'
        },
        xAxis: {
            //categories: [<?=$items['date'];?>],
            categories: [<?=$items['date'];?>],
            tickmarkPlacement: 'on',
            title: {
                enabled: false
            }
        },
        yAxis: {
            title: {
                text: ''
            },
            labels: {
                formatter: function () {
                    return this.value;
                }
            }
        },
        tooltip: {
            split: true
        },
        plotOptions: {
            area: {
                stacking: 'normal',
                lineColor: '#666666',
                lineWidth: 1,
                marker: {
                    lineWidth: 1,
                    lineColor: '#666666'
                }
            }
        },
        series: [{
            name: '总用户',
           // data: [<?=$items['all_user'];?>]
            data: [<?=$items['all_user'];?>]
        }, {
            name: 'IOS用户',
           // data: [<?=$items['ios_user'];?>]
            data: [<?=$items['ios_user'];?>]
        }, {
            name: '安卓用户',
            //data: [<?=$items['and_user'];?>]
            data: [<?=$items['and_user'];?>]
        }]
    });


</script>
<?php include __DIR__ . "/../layout/footer.phtml";?>