<?php importView("header.phtml"); ?><body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {margin-right: 30px}</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[id]" placeholder="请输入" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">显示名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[title]" placeholder="请输入" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[status]', NavigationModel::STATUS_TIPS,
                                    ["lay-search" => '']) ?>
                            </div>
                        </div>
<!--                        <div class="layui-inline">-->
<!--                            <label class="layui-form-label">暗网</label>-->
<!--                            <div class="layui-input-block">-->
<!--                                --><?php //echo Layui::search('where[is_aw]', NavigationModel::STATUS_TIPS,
//                                    ["lay-search" => '']) ?>
<!--                            </div>-->
<!--                        </div>-->
                        <div class="layui-inline">
                            <label class="layui-form-label">发现</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[is_find]', NavigationModel::FIND_TIPS,
                                    ["lay-search" => '']) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">H5</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[is_h5]', NavigationModel::H5_TIPS,
                                    ["lay-search" => '']) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}"  lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">显示名称：</label>
                <div class="layui-input-inline">

                    <input  placeholder="显示名称" name="title"
                            value="{{=d.title }}" class="layui-input">

                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('status', NavigationModel::STATUS_TIPS, ['data-value' => '{{=d.status}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">首次选中：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('is_current', NavigationModel::CURRENT_TIPS, ['data-value' => '{{=d.is_current}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">是否H5地址：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('is_h5', NavigationModel::H5_TIPS, ['data-value' => '{{=d.is_h5}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">H5地址：</label>
            <div class="layui-input-block">
                <input  placeholder="H5外链地址" name="h5_url" value="{{=d.h5_url }}" class="layui-input">
            </div>
        </div>

<!--        <div class="layui-form-item">-->
<!--            <label class="layui-form-label">跑马灯：</label>-->
<!--            <div class="layui-input-block">-->
<!--                --><?php //echo Layui::select('open_light', NavigationModel::STATUS_TIPS, ['data-value' => '{{=d.open_light}}']) ?>
<!--            </div>-->
<!--        </div>-->

        <div class="layui-form-item">
            <label class="layui-form-label">中部样式：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('mid_style', NavigationModel::MID_STYLE_TIPS, ['data-value' => '{{=d.mid_style}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">底部样式：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('bot_style', NavigationModel::BOT_STYLE_TIPS, ['data-value' => '{{=d.bot_style}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">排序：</label>
                <div class="layui-input-inline">

                    <input  placeholder="排序" name="sort_num"
                            value="{{=d.sort_num }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id'}
            , {field: 'title', title: '显示名称'}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true}
            // , {field: 'is_dm', title: '是否动漫', type: "switch", "value": "1|0", edit: true}
            , {field: 'is_find', title: '是否发现', type: "switch", "value": "1|0", edit: true}
            , {field: 'is_current', title: '是否首次选中', type: "switch", "value": "1|0", edit: true}
            , {field: 'is_h5', title: '是否H5', type: "switch", "value": "1|0", edit: true}
            , {field: 'h5_url', title: 'h5地址'}
            // , {field: 'open_light', title: '跑马灯开关', type: "switch", "value": "1|0", edit: true}
            // , {field: 'is_aw', title: '暗网', type: "switch", "value": "1|0", edit: true}
            , {field: 'mid_style_str', title: '中部样式'}
            , {field: 'bot_style_str', title: '底部样式'}
            , {field: 'click_num', title: '点击量',sort:true}
            , {field: 'sort_num', title: '排序',edit: true,sort:true}
            , {fixed: 'right', width: 200, title: '操作',align:'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>