<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理<span
                            style="color:palevioletred;font-weight: bold">排序按降序排列</span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">话题名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[name]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]',
                                    merge_array(['' => '全选'], PostTopicModel::STATUS_TIPS)) ?>

                            </div>
                        </div>


                        <div class="layui-inline">
                            <label class="layui-form-label">热门 </label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_hot]',
                                    merge_array(['' => '全选'], PostTopicModel::HOT_TIPS)) ?>

                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">WEB显示</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[web_show]',
                                    merge_array(['' => '全选'], PcPostTopicModel::WEB_TIPS)) ?>

                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <!--  <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <!--  <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>-->
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <label class="layui-form-label">话题封面：</label>
            <?php echo Layui::uploadPos('thumb_full', 'thumb', 40, 40, 'xiao') ?>
        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">背景图片：</label>
            <?php echo Layui::uploadPos('bg_thumb_full', 'bg_thumb', 40, 40, 'xiao') ?>

        </div>


        <div class="layui-form-item">

                <label class="layui-form-label">话题名称：</label>
                <div class="layui-input-block">

                    <input lay-verify="required" placeholder="话题名称" name="name"
                           value="{{=d.name }}" class="layui-input">

                </div>

        </div>

        <div class="layui-form-item">

            <label class="layui-form-label">WEB话题名称：</label>
            <div class="layui-input-block">

                <input placeholder="WEB话题名称" name="web_name"
                       value="{{=d.web_name }}" class="layui-input">
            </div>

        </div>

        <div class="layui-form-item">

                <label class="layui-form-label">简介：</label>
                <div class="layui-input-block">

                    <input placeholder="简介" name="intro"
                           value="{{=d.intro }}" class="layui-input">

                </div>

        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">话题封面：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.thumb }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">背景图片：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.bg_thumb }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">话题名称：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.name }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">关注人数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.follow_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">浏览人数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.view_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">0不显示 1显示：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.status }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">创建时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.created_at }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">排序 越大越前：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.sort }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">热门 0非热门 1热门 ：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.is_hot }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">帖子数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.post_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">简介：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.intro }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            // {type: 'checkbox', fixed: 'left'}
            {field: 'id', title: 'id', sort: true, width: 90}
            , {field: 'name', title: '话题'}
            , {field: 'web_name', title: 'WEB名称'}
            //, {field: 'thumb', title: '话题封面'}
            , {
                field: 'thumb', width: 120, title: '图片', align: 'center', templet: function (d) {
                    if (d.thumb_full) {
                        return '<div onclick="show_img(\'' + d.thumb_full + '\')" ><img width="50" src="' + d.thumb_full + '" /></div>';
                    }
                    return '';
                }
            },
            {
                field: 'bg_thumb', width: 120, title: '背景', align: 'center', templet: function (d) {
                    if (d.bg_thumb_full) {
                        return '<div onclick="show_img(\'' + d.bg_thumb_full + '\')" ><img width="50" src="' + d.bg_thumb_full + '" /></div>';
                    }
                    return '';
                }
            }
            //, {field: 'bg_thumb', title: '背景图片'}
            , {field: 'follow_num', title: '关注', sort: true}
            , {field: 'view_num', title: '浏览', sort: true}
            , {field: 'post_num', title: '帖子数', sort: true}
            // , {field: 'created_at', title: '创建时间'}
            , {field: 'sort', title: '排序', sort: true, edit: true, width: 120}
            , {field: 'web_show', title: 'WEB显示', type: "switch", value: "1|0", edit: true, width: 120}
            , {field: 'is_hot', title: '热门', type: "switch", value: "1|0", edit: true, width: 120}
            , {field: 'status', title: '状态', type: "switch", value: "1|0", edit: true, width: 120}
            // , {field: 'intro', title: '简介'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>