<?php include __DIR__ . "/../layout/header.phtml"; ?>
<div class="col-sm-12">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <form class="form-horizontal" id="frm">
                <div class="form-group">
                    <label class="col-sm-3 control-label">内容：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="样本内容" class="form-control" name="content" value="<?= $data['content'] ?? ''; ?>">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-sm btn-white" type="button" onclick="handleEdit()">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    var index = parent.layer.getFrameIndex(window.name);
    var transFile = 0;
    $('#img_url').click(
        function () {
            transFile = 1;
        }
    );
    function handleEdit() {
        var formData = new FormData($( "#frm" )[0]);
        formData.append('id',"<?=$_GET['id']?>");
        $.ajax({
            url: '/d.php?mod=sample&code=doEdit',
            data: formData,
            type: 'POST',
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            success: function (res) {
                if (res.status == 1) {
                    parent.reload(res.data)
                    parent.layer.close(index)

                } else {
                    layer.msg(res.data, {icon: 5})
                }
            }
        })
    }
</script>
<?php include __DIR__ . "/../layout/footer.phtml"; ?>
