<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header" style="color: hotpink">缓存key管理</div>
<!--                <div class="layui-form layui-card-header layuiadmin-card-header-auto">-->
<!--                    <div class="layui-form-item">-->
<!---->
<!--                        <div class="layui-inline">-->
<!--                            <label class="layui-form-label">id</label>-->
<!--                            <div class="layui-input-block">-->
<!--                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"-->
<!--                                       class="layui-input">-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="layui-inline">-->
<!--                            <label class="layui-form-label">缓存名称</label>-->
<!--                            <div class="layui-input-block">-->
<!--                                <input type="text" name="where[name]" placeholder="请输入" autocomplete="off"-->
<!--                                       class="layui-input">-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="layui-inline">-->
<!--                            <label class="layui-form-label">缓存key</label>-->
<!--                            <div class="layui-input-block">-->
<!--                                <input type="text" name="where[key]" placeholder="请输入" autocomplete="off"-->
<!--                                       class="layui-input">-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="layui-inline">-->
<!--                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">-->
<!--                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>-->
<!--                            </button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                           <!-- <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <!--<a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>-->
                        <a class="layui-btn  layui-btn-xs" data-pk="{{=d.id}}" data-group="{{=d.group}}"  lay-event="clearcache">
                            <i class="layui-icon layui-icon-delete"></i>清理</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">缓存名称：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="缓存名称" name="name"
                           value="{{=d.name }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">缓存key：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="缓存key" name="key"
                           value="{{=d.key }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">缓存名称：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.name }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">缓存key：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.key }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            //{type: 'checkbox', fixed: 'left'}
              {field: 'name', title: '缓存名称',width: 200}
            , {field: 'group', title: '缓存组名',width: 300}
            , {fixed: 'right',  title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event:{
            operate:{
                clearcache: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    ajax.post("<?php echo url_backend('refresh')?>", {"id": $this.data('pk'),'group':$this.data('group')})
                        .then(function (json) {

                            if (json.code) {
                                Util.msgErr(json.msg);
                            } else {
                                Util.msgOk(json.msg,function () {
                                    obj.del();
                                });
                            }
                        })
                },
            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>