<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header" style="color: #FF5722">认证申请</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">uuid</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uuid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>


                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">

                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        {{# if (d.status==1) { }}
                        <a class="layui-btn layui-btn-xs" data-pk="{{=d.id}}" lay-event="pass">通过</a>
                        <a class="layui-btn layui-btn-xs" data-pk="{{=d.id}}" lay-event="refuse">拒绝</a>
                        {{#  } }}
                        {{# if (d.status==4) { }}
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="cancel">
                            <i class="layui-icon layui-icon-delete"></i>取消资格</a>
                        {{#  } }}
                        {{# if (d.status!=4) { }}
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">删除</a>
                        {{#  } }}
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: undefined,
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
             {field: 'id', title: '#',width: 100}
            , {field: 'uuid', title: 'uuid'}
            , {field: 'nickname', title: '昵称'}
            , {field: 'type_str', title: '类型'}
            , {field: 'number_code', title: '认证数字'}
            ,{
                field: 'video', width: 100, title: '认证视频', templet: function (d) {
                    if(d.video){
                        return "<a class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.video + "')\"><i class='layui-icon layui-icon-play'></i>MP4</a>"
                    }else{
                        return ""
                    }
                }
            }
            , {field: 'status_str', title: '状态 '}
            , {field: 'refuse_reason', title: '拒绝理由'}
            , {field: 'created_at', title: '创建时间'}
            , {field: 'updated_at', title: '更新时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "event": {
            "operate": {
                /**
                 * 拒绝
                 */
                "cancel": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    var index = layer.prompt({"title": "取消资格理由", formType: 2, area: ['250px', '80px']}, function (val) {
                        if (val.length <= 0) {
                            Util.msgErr("理由不能为空");
                            return;
                        }
                        layer.confirm('再次确认取消创作者身份认证资格?', function (index2) {
                            var index3 = layer.load(0, {time: 3 * 1000, shade: [0.5, '#666']});
                            ajax.post("<?php echo url_backend('doCancel')?>", {"refuse": val, "id": $this.data('pk')})
                                .then(function (json) {
                                    layer.close(index);
                                    layer.close(index);
                                    layer.close(index3);
                                    if (json.code) {
                                        Util.msgErr(json.msg);
                                    } else {
                                        Util.msgOk(json.msg, Util.reload);
                                    }
                                })
                        });
                    });
                },
                /**
                 * 通过
                 */
                "pass": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('真的要通过吗?', function (index) {
                        layer.close(index);
                        var index3 = layer.load(0, {time: 3 * 1000, shade: [0.5, '#666']});
                        ajax.post("<?php echo url_backend('doPass')?>", {"id": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index3);
                                if (json.code) {
                                    console.log(json.msg);
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, Util.reload);
                                }
                            })
                    });
                },
                /**
                 * 拒绝
                 */
                "refuse": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    var index = layer.prompt({"title": "拒绝的理由", formType: 2, area: ['250px', '80px']}, function (val) {
                        if (val.length <= 0) {
                            Util.msgErr("理由不能为空");
                            return;
                        }
                        var index3 = layer.load(0, {time: 3 * 1000, shade: [0.5, '#666']});
                        ajax.post("<?php echo url_backend('doRefuse')?>", {"refuse": val, "id": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index);
                                layer.close(index3);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, Util.reload);
                                }
                            })
                    });
                }
            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>