[common]
application.dispatcher.throwException=1
application.dispatcher.catchException=1
application.directory = APP_PATH "/application"
application.bootstrap=APP_PATH "/application/bootstrap/Bootstrap.php"

application.modules = "Index,Home,Api,Admin,Script,V2,Live,Wapi,Transit,Jump"
application.dispatcher.defaultModule = 'Home'
application.dispatcher.defaultController = 'Forward'
application.library.namespace = "App"
;user
user.default_filter='trim,addslashes,htmlspecialchars'
token.login=e096db7c006958f226bc469c27237345
sms.timeout=120
; img
img.cn_base_url=TB_IMG_APP_CN
pwa.img.cn.base=TB_IMG_PWA_CN
img.us_base_url=TB_IMG_APP_US
img.img_av_url=https://images.91tv.tv/img.av/
img.img_live_url=https://images.91tv.tv/img.live/
img.img_xiao_url=https://images.91tv.tv/
img.img_actors_url=https://images.91tv.tv/img.actors/
img.img_head_url=https://images.91tv.tv/img.head/
img.img_ads_url=https://images.91tv.tv/img.ads/
img.img_icos_url=https://images.91tv.tv/img.icos/

; upload 不加密

img.img_music_url=https://p.cnkamax.com/
img.default_jd_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
img.default_91nolog_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
img.default_91login_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
upload.mp4_play_url=TB_CHECK_VIDEO "/"

video.encrypt.referer = https://play.nbaidu.com
upload.site_url = https://upaw.dyclub.co

; user can watch count
; 页面
site.long_video_duration=30
site.can_watch_count = 3
template.compiled_root_path = /data/cache/tpl/
template.template_path = tpl
template.template_root_path = /theme/
video.local_url=TB_VIDEO_ADM_US

; 远程配置
cfg.json = "https://config.zxsnvvik.top/php-yuanc-share.json"
cfg.site = "https://config.zxsnvvik.top/php-yuanc.json"

; 后台地址
system.cn_name = 搜同社区
; 支付名称
pay.app_name = soutongappga
;支付回调
pay.notify = http://soutong-app-index.we-cname2.com

; 远程广告配置
ads.key =
ads.app_list_url = https://ads.microservices.vip/api/list
ads.app_report_url = https://ads.microservices.vip/api/click

; 渠道联盟
channel.product_id = 91
channel.sign_key =
channel.encrypt_key =

; 直播获取远程图片
live.cf_get=
live.proxy_url=
live.api_key=

;collect data url
boye.love.url =
cz.book.url =
grab.img_url =
grab.ucmh.url =

;官方群
official.group='https://t.me/bluelifeG'

; 联盟id
union.pid=0
; 联盟加解密key
union.key=""
; 联盟签名key
union.sign=""
; 联盟消息存放在redis中的消息队列name
union.qname="serv:chan-queue"
;  日志等级。最高16，最低0，调试时使用16，正式环境日志等级使用 9 ，不需要日志 0
union.log_level=9

[product : common]

[develop : common]

[test : common]

