[common]
database.driver='mysql'
database.read.host='db-server'
database.write.host='db-server'
database.port='3306'
database.database='soutong'
database.username='root'
database.password='root'
database.charset='utf8mb4'
database.collation='utf8mb4_unicode_ci'
database.prefix='ks_'
database.strict=false
;redis
redis.host.0=redis-server
redis.port=6379
redis.prefix=st:

[product : common]

[develop : common]

[test : common]

