<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="telephone=no" name="format-detection">
    <link type="text/css" rel="stylesheet" href="/static/index/css/layer.css">
    <link href="/static/index/css/common.css" rel="stylesheet" type="text/css">
    <title>招募令</title>
    <script>
        (function (c, d) {
            var e = document.documentElement || document.body,
                a = "orientationchange" in window ? "orientationchange" : "resize",
                b = function () {
                    var f = e.clientWidth;
                    e.style.fontSize = (f >= 750) ? "100px" : 100 * (f / 750) + "px"
                };
            b();
            c.addEventListener(a, b, false)
        })(window);
    </script>
    <link href='/static/index/css/proxy_recruit.css' rel="stylesheet" type="text/css" >
</head>
<body >

<div class="main-wrap page-join">

    <div class="row-box1">
        <header class="flex-center">
            <a href="<?=$config['site'];?>" class="nav flex-center"><img style="border-radius: 10px;border:2px solid white" src="/static/index/img/default_thumb.png" alt="">&nbsp;&nbsp;搜同片</a>
            <a href="<?=$config['site'];?>" class="nav" style="margin-right:0;">APP下载</a>
        </header>
        <div class="img-box">
            <img src="/static/index/img/join-img1.png" alt="" class="pc">
            <img src="/static/index/img/join-img-m1.png" alt="" class="mobile">
        </div>
        <div class="mobile-content">
            <p>現面向全球招聘代理，0門檻無需投資；時間地點自由，壹部手機，隨時隨地可賺錢；只要用妳的閑暇時間轉發和分享就能推廣。</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;壹看即會，約炮賺錢，終生享受利潤分紅。</p>
        </div>
    </div>

    <div class="row-box2">
        <div class="box-title">加盟好處</div>
        <ul class="list flex-center">

            <li class="item flex-center">
                <div class="img-box flex-center">
                    <img src="/static/index/img/join-icon1.png" class="icon">
                </div>
                <div class="text flex-vcenter">
                    <div class="title">完全免費</div>
                    <div class="desc">培訓免費，使用免費，無任何費用</div>
                </div>
            </li>

            <li class="item flex-center">
                <div class="img-box flex-center">
                    <img src="/static/index/img/join-icon2.png" class="icon">
                </div>
                <div class="text flex-vcenter">
                    <div class="title">零投資</div>
                    <div class="desc">沒有門檻，專心做推廣即可</div>
                </div>
            </li>

            <li class="item flex-center">
                <div class="img-box flex-center">
                    <img src="/static/index/img/join-icon3.png" class="icon">
                </div>
                <div class="text flex-vcenter">
                    <div class="title">壹鍵搞定</div>
                    <div class="desc">只需壹鍵分享轉發，操作簡單</div>
                </div>
            </li>

            <li class="item flex-center">
                <div class="img-box flex-center">
                    <img src="/static/index/img/join-icon4.png" class="icon">
                </div>
                <div class="text flex-vcenter">
                    <div class="title">利潤高</div>
                    <div class="desc">平臺最高返利30%，多勞多得</div>
                </div>
            </li>

            <li class="item flex-center">
                <div class="img-box flex-center">
                    <img src="/static/index/img/join-icon5.png" class="icon">
                </div>
                <div class="text flex-vcenter">
                    <div class="title">財務透明</div>
                    <div class="desc">財務流水隨時查看核對，公開透明</div>
                </div>
            </li>

            <li class="item flex-center">
                <div class="img-box flex-center">
                    <img src="/static/index/img/join-icon6.png" class="icon">
                </div>
                <div class="text flex-vcenter">
                    <div class="title">提現方便</div>
                    <div class="desc">操作簡單，到賬迅速</div>
                </div>
            </li>

        </ul>
    </div>


    <div class="row-box3">
        <div class="box-title">如何推廣</div>
        <div class="content flex-center">
            <img src="/static/index/img/join-img_p_3.png" class="col">
            <div class="col text">
                <div class="title">推廣方法：</div>
                <div class="row">1.在APP中，<span class="color-red">【我的】</span>-<span class="color-red">【分享推廣】</span>中，<span class="color-red">【分享推廣鏈接】</span>，或<span class="color-red">【復制推廣碼】</span>，分享給好友。</div>

                <div class="row">2.新用戶下載安裝APP後，即可綁定推薦關系，用戶的全部消費，您都可以獲得返利，最高比例可返<span class="color-red">30%</span>。<p></p>（詳見下方業績核算）</div>
            </div>
        </div>
    </div>

    <div class="row-box4">
        <div class="box-title">業績.返傭</div>
        <div class="content ">

            <div class="text">
                <div class="row">代理直接推薦的用戶為<span class="color-red">壹級用戶</span>,壹級用戶邀請的新用戶屬於您的<span class="color-red">二級用戶</span>,以此類推到<span class="color-red">四級用戶</span>,推薦用戶的每次消費，均會計入業績，產生返傭，並隨著業績的提高，返傭比例逐步提高。</div>
                <div class="row" style="text-align: center;"><span class="color-red">壹級用戶</span>充值:業績轉化=充值金額*100%。</div>
                <div class="row" style="text-align: center;"><span class="color-red">二級用戶</span>充值:業績轉化=充值金額*25%。</div>
                <div class="row" style="text-align: center;"><span class="color-red">三級用戶</span>充值:業績轉化=充值金額*15%。</div>
                <div class="row" style="text-align: center;"><span class="color-red">四級用戶</span>充值:業績轉化=充值金額*10%。</div>
                <div class="row" style="text-align: center;">傭金可提現到銀行卡，也可以在平臺消費。</div>
            </div>

            <div class="title-box ">
                代理傭金=新增業績*<span class="red">總業績對應的返傭比例</span>
                <div class="imgs">
                    <!--<img src="/images/arrow1.png">
                    <img src="/skin/frontend/default/assets/images/arrow2.png">-->
                </div>
            </div>

            <div class="img-box">

                <div class="col ">

                    <div class="title pc-title">返傭比例圖</div>
                    <div class="title mobile-title">代理傭金=新增業績*<span class="red">總業績對應的返傭比例</span></div>
                    <img src="/static/index/img/arrow3.png" class="list-img">
                    <ul class="list-box">
                        <li class="active">
                            <span>總業績（元）</span>
                            <span>返傭比例</span>
                        </li>

                        <li>
                            <span>0~1000</span>
                            <span>10%</span>
                        </li>

                        <li>
                            <span>1000~2000</span>
                            <span>12%</span>
                        </li>

                        <li>
                            <span>2000~5000</span>
                            <span>15%</span>
                        </li>

                        <li>
                            <span>5000~10000</span>
                            <span>16%</span>
                        </li>

                        <li>
                            <span>10000~20000</span>
                            <span>18%</span>
                        </li>

                        <li>
                            <span>20000~40000</span>
                            <span>20%</span>
                        </li>

                        <li>
                            <span>40000~70000</span>
                            <span>23%</span>
                        </li>

                        <li>
                            <span>70000~100000</span>
                            <span>26%</span>
                        </li>

                        <li>
                            <span>100000以上</span>
                            <span>30%</span>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <div><a href="http://a.kslive.tv/">點我下載APP</a></div>
        <div style="height: 60px;"></div>
    </footer>
</div>
<script src="/static/index/js/jquery.js"></script>
<script src="/static/index/js/layer.js"></script>
</body>
</html>