<!DOCTYPE html>
<html>
<head lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="telephone=no" name="format-detection">
    <link type="text/css" rel="stylesheet" href="/static/index/css/layer.css">
    <link href="/static/index/css/common.css" rel="stylesheet" type="text/css">

    <link type="text/css" rel="stylesheet" href="/static/index/css/cash.css"/>
    <title>提现记录</title>
    <style>
        .list ul li {
            /*background: #200139;*/
            padding: 20px;
            /*border-bottom: 1px solid #410076;*/
        }
        .list ul li p {
            color: #ad2eef;
        }
        .list ul li .list_r p {
            color: #ad2eef;
        }

    </style>
</head>
<body>
<div class="list">
    <ul>
        <?php if($list) foreach ($list as $v):?>
            <li>
                <div class="list_l">
                    <p><span>实收：</span><?=$v['trueto_amount'];?></p>
                    <p style="color: #999;"><span>申请:</span><?=$v['amount'];?></p>
                </div>
                <div class="list_r">
                    <p><?=$v['status_name'];?></p>
                    <p style="color: #999;"><?=$v['created_at'];?></p>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<script>
    var uid='<?=$uid;?>';
    var token=='<?=$token;?>';
</script>
<script src="/static/index/js/jquery.js"></script>
<script src="/static/index/js/layer.js"></script>
<script>
    $(function(){
        function getlistmore(){
            $.ajax({
                url:'/index.php?g=appapi&m=cash&a=getlistmore&theme=hailang',
                data:{'page':page,'uid':uid,'token':token},
                type:'post',
                dataType:'json',
                success:function(data){
                    if(data.nums>0){
                        var nums=data.nums;
                        var list=data.data;
                        var html='';
                        for(var i=0;i<nums;i++){
                            var v=list[i];
                            html='<li>\
                                    <div class="list_l">\
                                        <p><span><img class="coin" src="__PUBLIC__/appapi/images/coin.png"></span>'+v['votes']+'}</p>\
                                        <p class="money"><span>金额:</span>'+v['money']+'}</p>\
                                    </div>\
                                    <div class="list_r">\
                                        <p>'+v['status_name']+'}</p>\
                                        <p>'+v['created_at']+'}</p>\
                                    </div>\
                                </li>';
                        }

                        $(".list ul").append(html);
                    }

                    if(data.isscroll==1){
                        page++;
                        isscroll=true;
                    }
                }
            })
        }

        var page=2;
        var isscroll=true;

        var scroll_list=$("body");

        scroll_list.scroll(function(){
            var srollPos = scroll_list.scrollTop();    //滚动条距顶部距离(页面超出窗口的高度)
            var totalheight = parseFloat(scroll_list.height()) + parseFloat(srollPos);
            if(($(document).height()-50) <= totalheight  && isscroll) {
                isscroll=false;
                getlistmore()
            }
        });


    })
</script>
</body>
</html>