<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="telephone=no" name="format-detection">
    <link type="text/css" rel="stylesheet" href="/static/index/css/layer.css">
    <link type="text/css" rel="stylesheet" href="/static/index/css/detail.css">
    <link href="/static/index/css/common.css" rel="stylesheet" type="text/css">
    <title>我的明细</title>
</head>
<body class="detail">
<div class="profit_bg">
    <div class="tab">
        <ul>
            <li class="on">
                收礼物明细
            </li>
            <li>
                送礼物明细
            </li>
            <li>
                直播时长明细
            </li>
        </ul>
    </div>
    <div class="profit_line"></div>
    <div class="tab_b receive">
        <div class="profit_ul_t">
            <span class="name">礼物名称</span>
            <span class="coin">价值(钻石)</span>
            <span class="nums">个数</span>
            <span class="username">送礼人</span>
        </div>
        <div class="profit_ul clear">
            <ul>
                <?php foreach ($list as $v): ?>
                    <li>
                        <span class="name"><?=$v['giftinfo']['giftname']?></span>
                        <span class="coin"><?=intval($v['total'])?></span>
                        <span class="nums"><?=$v['giftcounts']?></span>
                        <span class="username"><?=$v['userinfo']['nickname']?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="tab_b hide send">
        <div class="profit_ul_t">
            <span class="name">礼物名称</span>
            <span class="coin">价值(钻石)</span>
            <span class="nums">个数</span>
            <span class="username">收礼人</span>
        </div>
        <div class="profit_ul clear">
            <ul>
                    <?php foreach ($send_list as $v): ?>
                    <li>
                        <span class="name"><?=$v['giftinfo']['giftname']?></span>
                        <span class="coin"><?=intval($v['total'])?></span>
                        <span class="nums"><?=$v['giftcounts']?></span>
                        <span class="username"><?=$v['userinfo']['nickname']?></span>
                    </li>
                    <?php endforeach;?>
            </ul>
        </div>
    </div>
    <div class="tab_b hide liverecord">
        <div class="profit_ul_t">
            <span style="width:36%;">开始时间</span>
            <span style="width:36%;">结束时间</span>
            <span style="width:28%;">直播时长</span>
        </div>
        <div class="profit_ul clear">
            <ul>
                    <?php foreach ($list_live as $v): ?>
                    <li>
                        <span style="width:36%;"><?=date("Y-m-d H:i",$v['starttime'])?></span>
                        <span style="width:36%;"><?=date("Y-m-d H:i",$v['endtime'])?></span>
                        <span style="width:28%;"><?=$v['length']?></span>
                    </li>
                    <?php endforeach;?>
            </ul>
        </div>
    </div>
</div>
<script>
    var uid = '<?=$uid?>';
    var token = '<?=$token?>';
</script>
<script src="/static/index/js/jquery.js"></script>
<script src="/static/index/js/layer.js"></script>
<script>
    $(function () {
        function getlistmore() {
            $.ajax({
                url: '/index.php?m=detail&a=receive_more',
                data: {'page': page, 'uid': uid, 'token': token},
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.nums > 0) {
                        var nums = data.nums;
                        var list = data.data;
                        var html = '';
                        for (var i = 0; i < nums; i++) {
                            html = '<li>\
										<span>' + list[i]['giftinfo']['giftname'] + '</span>\
										<span>' + list[i]['total'] + '</span>\
										<span>' + list[i]['giftcounts'] + '</span>\
										<span>' + list[i]['userinfo']['nickname'] + '</span>\
									</li>';
                        }

                        $(".receive .profit_ul ul").append(html);
                    }

                    if (data.isscroll == 1) {
                        page++;
                        isscroll = true;
                    }
                }
            })
        }

        function getsendlistmore() {
            $.ajax({
                url: '/index.php?m=detail&a=send_more',
                data: {'page': page, 'uid': uid, 'token': token},
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.nums > 0) {
                        var nums = data.nums;
                        var list = data.data;
                        var html = '';
                        for (var i = 0; i < nums; i++) {
                            html = '<li>\
										<span>' + list[i]['giftinfo']['giftname'] + '</span>\
										<span>' + list[i]['total'] + '</span>\
										<span>' + list[i]['giftcounts'] + '</span>\
										<span>' + list[i]['userinfo']['nickname'] + '</span>\
									</li>';
                        }

                        $(".receive .profit_ul ul").append(html);
                    }

                    if (data.isscroll == 1) {
                        page++;
                        isscroll = true;
                    }
                }
            })
        }

        function getlivelistmore() {
            $.ajax({
                url: '/index.php?m=detail&a=liverecord_more',
                data: {'page': page, 'uid': uid, 'token': token},
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.nums > 0) {
                        var nums = data.nums;
                        var list = data.data;
                        var html = '';
                        for (var i = 0; i < nums; i++) {
                            html = '<li>\
										<span style="width:35%;">' + list[i]['starttime'] + '</span>\
										<span style="width:35%;">' + list[i]['endtime'] + '</span>\
										<span style="width:30%;">' + list[i]['length'] + '</span>\
									</li>';
                        }

                        $(".liverecord .profit_ul ul").append(html);
                    }

                    if (data.isscroll == 1) {
                        page++;
                        isscroll2 = true;
                    }
                }
            })
        }

        $(".tab ul li").on("click", function () {
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
            $(".tab_b").hide().eq($(this).index()).show();
        })
        var page = 2;
        var isscroll = true;
        var isscroll2 = true;

        $(".receive .profit_ul").scroll(function () {
            var srollPos = $(".receive .profit_ul").scrollTop();    //滚动条距顶部距离(页面超出窗口的高度)
            var totalheight = parseFloat($(".receive .profit_ul").height()) + parseFloat(srollPos);
            if (($(document).height() - 50) <= totalheight && isscroll) {
                isscroll = false;
                getlistmore()
            }
        });

        $(".send .profit_ul").scroll(function () {
            var srollPos = $(".receive .profit_ul").scrollTop();    //滚动条距顶部距离(页面超出窗口的高度)
            var totalheight = parseFloat($(".receive .profit_ul").height()) + parseFloat(srollPos);
            if (($(document).height() - 50) <= totalheight && isscroll) {
                isscroll = false;
                getsendlistmore()
            }
        });

        $(".liverecord .profit_ul").scroll(function () {
            var srollPos = $(".liverecord .profit_ul").scrollTop();    //滚动条距顶部距离(页面超出窗口的高度)
            var totalheight = parseFloat($(".liverecord .profit_ul").height()) + parseFloat(srollPos);
            if (($(document).height() - 50) <= totalheight && isscroll2) {
                isscroll2 = false;
                getlivelistmore()
            }
        });

    })
</script>
</body>
</html>