<!DOCTYPE html>
<html>
<head lang="en">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="telephone=no" name="format-detection">
    <link type="text/css" rel="stylesheet" href="/static/index/css/layer.css">
    <link href="/static/index/css/common.css" rel="stylesheet" type="text/css">

    <title>错误提示</title>
    <style type="text/css">
        body {
            text-align: center
        }

        .title2 {
            color: #526165;
            font-size: 1.0em;
            text-align: center;
            margin-top: 4%;
        }

        img {
            width: 18%;
            margin: 30% auto 9%;
        }

        p {
            font-size: 0.9em;
            color: #B4C1C7;
            text-align: center;
            line-height: 150%
        }

        .alink {
            color: #00D8C9;
            text-decoration: underline;
        }
    </style>
</head>
<body>
<img src="/static/index/img/error.png">
<div class="title2"><p>您的登陆状态失效，请重新登陆！<br></p></div>

<script src="/static/index/js/jquery.js"></script>
<script src="/static/index/js/layer.js"></script>


</body>
</html>