<!DOCTYPE html>
<!-- saved from url=(0123)/index.php?m=Feedback&a=index&uid=69847&token=817618a5ea18548ba88928a6709b7fea -->
<html>
<head lang="en">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>意见反馈</title>


    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="telephone=no" name="format-detection">
    <link type="text/css" rel="stylesheet" href="/static/index/css/layer.css">
    <link href="/static/index/css/common.css" rel="stylesheet" type="text/css">

    <link type="text/css" rel="stylesheet" href="/static/index/css/feedback.css">
</head>
<body>
<?php if (!empty($show_tip)): ?>
    <h1 style="padding: 1rem;padding-bottom: 0;font-size: 1.4rem;margin-top: 8px;color: red">
        近期在线客服无法收到大家反馈的问题已经解决，程序员已祭天，现在可以正常发送并接收消息。</h1>
<?php endif; ?>
<div id="test">
    <textarea placeholder="请将您遇到的问题／产品建议反馈给我们，建议您尽可能详细的描述问题，便于运营同学帮您解决。" id="content" oninput="check_input()"
              maxlength="200" style="height: 266.8px;"></textarea>
    <div class="num" style="top:230px;bottom:auto">最多只能输入200字</div>

    <div class="thumb_bd" style="position: relative;bottom: auto">
        <div id="upload"></div>
        <input type="hidden" id="thumb" name="thumb" value="">
        <img src="/static/index/img/add.png" class="fl img-sfz" data-index="ipt-file1" id="img_file1"
             onclick="file_click($(this))">
        <div class="shad1 shadd" data-select="ipt-file1">
            <div class="title-upload">正在上传中...</div>
            <div id="progress1">
                <div class="progress ipt-file1"></div>
            </div>
        </div>
    </div>
</div>
<div id="btm" style="position: relative">
    <button disabled="" id="save_btn" class="button_default">点击反馈</button>
    <a href="/index.php?m=Feedback&a=feedbacklist&uid=<?= $_GET['uid'] ?>&token=<?= $_GET['token'] ?>">
        <button style="margin-top: 5%;width: 50%;margin-left: 25%;background-image: linear-gradient(to right, rgb(237, 0, 255), rgb(255, 0, 137));"
                class="button_default"
                href="/index.php?m=Feedback&a=feedbacklist&uid=<?= $_GET['uid'] ?>&token=<?= $_GET['token'] ?>">反馈记录
        </button>
    </a>
</div>

<input type="hidden" id="uid" value="<?= $_GET['uid'] ?>">
<input type="hidden" id="token" value="<?= $_GET['token'] ?>">
<input type="hidden" id="version" value="">
<input type="hidden" id="model" value="">

<script src="/static/index/js/jquery.js"></script>
<script src="/static/index/js/layer.js"></script>

<script>
    var picDomain = "<?=$picDomain;?>";
</script>
<script src="/static/index/js/ajaxfileupload.js"></script>
<script src="/static/index/js/feedback.js"></script>

</body>
</html>