<!DOCTYPE html>
<html>
<head lang="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="telephone=no" name="format-detection">
    <title>反馈历史</title>

    <script src="/static/index/js/jquery.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;d
            list-style: none;
            box-sizing: border-box;
            text-decoration: none;
        }
        .Replay{

        }
        .Replayitem{
            padding: 0.3rem 0.4rem;
            border-bottom: 1px solid #ccc;
            font-size: 0.32rem;
        }
        p{
            font-size: 0.28rem;
            color: #969696;
            margin-top: 0.2rem;
        }
    </style>
</head>
<body>
<?php foreach ($list as $vo): ?>
<?php $vo=(array)$vo;?>
    <li class="Replayitem">
        问题：<?=$vo['content']?>
        <p><?=date('Y-m-d H:i:s',$vo['addtime']);?></p>
    </li>
    <if condition="$vo['created_at'] neq ''">
        <li class="Replayitem">
            回答：<?=$vo['reply_content']?>
            <p><?=date('Y-m-d H:i:s',$vo['created_at']);?></p>
        </li>
    </if>
<?php endforeach;?>
</body>
<script type="text/javascript">
    // 计算rem单位
    (function (doc, win) {
        var docEl = doc.documentElement,
            isIOS = navigator
                .userAgent
                .match(/\(i[^;]+;( U;)? CPU.+Mac OS X/),
            dpr = isIOS
                ? Math.min(win.devicePixelRatio, 3)
                : 1,
            dpr = window.top === window.self
                ? dpr
                : 1, //被iframe引用时，禁止缩放
            dpr = 1,
            scale = 1 / dpr,
            resizeEvt = 'orientationchange' in window
                ? 'orientationchange'
                : 'resize';
        docEl.dataset.dpr = dpr;
        var metaEl = doc.createElement('meta');
        metaEl.name = 'viewport';
        metaEl.content = 'initial-scale=' + scale + ',maximum-scale=' + scale + ', minimum-scale=' + scale;
        docEl
            .firstElementChild
            .appendChild(metaEl);
        var recalc = function () {
            var width = docEl.clientWidth;
            if (width / dpr > 750) {
                width = 750 * dpr;
            }
            // 乘以100，px : rem = 100 : 1
            docEl.style.fontSize = 100 * (width / 750) + 'px';
        };
        recalc()
        if (!doc.addEventListener)
            return;
        win.addEventListener(resizeEvt, recalc, false);
    })(document, window);
</script>
</html>