
<!DOCTYPE html>
<html>
<head>
    <title><?=$news['post_title']?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta content="telephone=no" name="format-detection" />
    <!-- Set render engine for 360 browser -->
    <meta name="renderer" content="webkit">

    <!-- No Baidu Siteapp-->
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link type="text/css" rel="stylesheet" href="/static/index/css/page.css?t=1545290181" rel="stylesheet">
</head>

<body class="body-white">
<div class="container tc-main">
    <div class="page_content">
        <?=$news['post_content'];?>
    </div>

</div>
<!-- /container -->
</body>
<script>
    // 防止安卓自动弹出键盘问题
    document.activeElement.blur();
</script>
</html>