<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="telephone=no" name="format-detection" />
    <link type="text/css" rel="stylesheet" href="/static/index/css/layer.css"/>
    <link href='/static/index/css/common.css?t=1540432563' rel="stylesheet" type="text/css" >

	<link type="text/css" rel="stylesheet" href="/static/index/css/family.css"/>
    <title>家族盈利</title>
</head>
<body class="profit">
	<div class="profit_bg">
        <notempty name="list">
		<div class="profit_ul_t">
			<span>主播</span>
			<span>时间</span>
			<span>家族盈利</span>
			<span>主播盈利</span>
		</div>
        </notempty>
		<div class="profit_ul clear">
			<ul>
				<volist name="list" id="v">
				<li>
					<span>{$v['userinfo']['nickname']}</span>
					<span>{$v['time']}</span>
					<span class="coin"><img src="__PUBLIC__/appapi/images/coin.png">{$v['profitzong']}</span>
					<span class="coin"><img src="__PUBLIC__/appapi/images/coin.png">{$v['anthor_totoal']}</span>
				</li>
				</volist>
                <empty name="list">
                    <div class="li_empty">
                        <p class="title"></p>
                        <p class="des">暂时还没有家族盈利</p>
                    </div>
                </empty>
			</ul>
		</div>
	</div>
	<script>
        var uid='<?=$_GET['uid']?>';
        var token='<?=$_GET['$token']?>';
        var familyid='<?=$family_info['id'];?>';
	</script>
    <script src="/static/index/js/jquery.js"></script>
    <script src="/static/index/js/layer.js"></script>
	<script>
	$(function(){
		function getlistmore(){
			$.ajax({
				url:'/index.php?m=Family&a=profit_more',
				data:{'page':page,'uid':uid,'token':token,'familyid':familyid},
				type:'post',
				dataType:'json',
				success:function(data){
					if(data.nums>0){
							var nums=data.nums;
							var list=data.data;
							var html='';
							for(var i=0;i<nums;i++){
								html='<li>\
										<span>'+list[i]['userinfo']['nickname']+'</span>\
										<span>'+list[i]['time']+'</span>\
										<span>'+list[i]['profitzong']+'</span>\
										<span>'+list[i]['anthor_totoal']+'</span>\
									</li>';
							}
						
						$(".profit_ul ul").append(html);
					}
					
					if(data.isscroll==1){
						page++;
						isscroll=true;
					}
				}
			})
		}
		var page=2; 
		var isscroll=true; 

		$(".profit_ul").scroll(function(){  
				var srollPos = $(".profit_ul").scrollTop();    //滚动条距顶部距离(页面超出窗口的高度)  		
				var totalheight = parseFloat($(".profit_ul").height()) + parseFloat(srollPos);  
				if(($(document).height()-50) <= totalheight  && isscroll) {  
						isscroll=false;
						getlistmore()
				}  
		});  

	})
	</script>	
</body>
</html>