<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="telephone=no" name="format-detection" />
    <link type="text/css" rel="stylesheet" href="/static/index/css/layer.css"/>
    <link href='/static/index/css/common.css?t=1540432563' rel="stylesheet" type="text/css" >

	<link type="text/css" rel="stylesheet" href="/static/index/css/family.css"/>
    <title>解除签约</title>
</head>
<body class="relieve">

		<div class="tips">
			需要双方同意才能完成解约，解约后将会为双方造成一定的损失。
		</div>
		<div style="width: 100%; position: absolute;">
			<div class="relievebtn">申请</div>
		</div>


	<script>
        var uid='<?=$_GET['uid']?>';
        var token='<?=$_GET['token']?>';
	</script>
        <script src="/static/index/js/jquery.js"></script>
        <script src="/static/index/js/layer.js"></script>
	<script src="/static/index/js/family.js?t=1"></script>
</body>
</html>