<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">观影券管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">uid</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[status]', MvTicketModel::STATUS) ?>

                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">mv_id</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[mv_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">

                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" data-h="600" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">uid：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="uid" name="uid"
                       value="{{=d.uid }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('status', MvTicketModel::STATUS, ['data-value' => '{{=d.status }}']) ?>

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">expired_at：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="expired_at eg 20200912" name="expired_at"
                       value="{{=d.expired_at }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">优惠券名称：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="优惠券名称" name="name"
                       value="{{=d.name }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">used_at：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="used_at  eg 20200912" name="used_at"
                       value="{{=d.used_at }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">mv_id：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="mv_id" name="mv_id"
                       value="{{=d.mv_id }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">mv_uid：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="mv_uid" name="mv_uid"
                       value="{{=d.mv_uid }}" class="layui-input">

            </div>

        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id'}
            , {field: 'uid', title: 'uid', width: 100}
            , {
                field: 'status_str', title: '状态', templet: function (d) {
                    if (d.status == '0') {
                        return "<span style='color:green'>" + d.status_str + "</span>"
                    } else if (d.status == '1') {
                        return "<span style='color:orangered'>" + d.status_str + "</span>"
                    }
                    return "<span style='color: red'>" + d.status_str + "</span>"

                }
            }
            , {field: 'expired_at', title: 'expired_at'}
            , {field: 'name', title: '优惠券名称'}
            , {field: 'create_at', title: 'create_at'}
            , {field: 'used_at', title: 'used_at'}
            , {field: 'mv_id', title: 'mv_id'}
            , {field: 'mv_uid', title: 'mv_uid'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>