<?php importView("header.phtml"); ?><body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {margin-right: 30px}</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">导航</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[nag_id]', merge_array(['' => '全部'], $nagArr)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">中部样式</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[mid_style]', merge_array(['' => '全部'], NavigationModel::MID_STYLE_CONF_TIPS)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">导航</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('nag_id', merge_array(['' => '全部'], $nagArr), ['data-value' => '{{=d.nag_id}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">中部样式</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('mid_style', NavigationModel::MID_STYLE_CONF_TIPS, ['data-value' => '{{=d.mid_style}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">配置类型：</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('type', NagConfModel::CONF_TIPS, ['data-value' => '{{=d.type}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">文案：</label>
                <div class="layui-input-inline">
                    <input placeholder="文案" name="title" value="{{=d.title }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">图标：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('icon_url', 'icon') ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">数量：</label>
                <div class="layui-input-inline">
                    <input placeholder="数量" name="show_num" value="{{=d.show_num }}" class="layui-input">
                </div>
            </div>
        </div>

<!--        <div class="layui-form-item">-->
<!--            <div class="layui-inline">-->
<!--                <label class="layui-form-label">up主分类：</label>-->
<!--                <div class="layui-input-inline">-->
<!--                    --><?php //echo Layui::select('up_catid', merge_array(['' => '选择'], UpGroupModel::getDataList()), ['data-value' => '{{d.up_catid}}']); ?>
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">结构API：</label>
                <div class="layui-input-inline">
                    <input placeholder="结构API" name="api" value="{{=d.api }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">排序：</label>
                <div class="layui-input-inline">
                    <input placeholder="排序" name="sort" value="{{=d.sort }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id'}
            , {field: 'nag_title', title: '导航'}
            , {field: 'nag_mid_str', title: '中部样式'}
            , {field: 'type_str', title: '配置类型'}
            , {field: 'title', title: '文案'}
            , {
                field: 'icon', title: '图标', width: 80, templet: function (d) {
                    if (d.icon_url){
                        return '<img src="' + d.icon_url + '" style="width: 50px;height: 40px;" onclick="show_img(\'' + d.icon_url + '\')">';
                    }else{
                        return "";
                    }
                }
            }
            , {field: 'show_num', title: '数量'}
            // , {field: 'up_catid', title: 'up分类ID'}
            , {field: 'api', title: '结构API'}
            , {field: 'sort', title:  '排序',edit: true,sort:true}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>