<?php importView("header.phtml"); ?><body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {margin-right: 30px}</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                                                    <div class="layui-inline">
                                <label class="layui-form-label">id</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[id]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">1 个人类型 2 团队类型</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[type]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">uid</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[uid]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">创作者等级</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[level_num]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">手机</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[phone]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">0 缺省 1待审核  2 未通过  3. 禁用 4 正常 </label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[status]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">拒绝理由</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[refuse_reason]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">视频审核次数</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[mv_check]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">视频提交数量</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[mv_submit]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">视频拒绝次数</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[mv_refuse]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">creator_tag</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[creator_tag]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">creator_desc</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[creator_desc]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">update_at</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[update_at]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">created_at</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[created_at]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">用户昵称，和用户表保持一致</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[nickname]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">累计汤币</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[total_coins]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">扣量指标，出量率</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[output_rate]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">提现结算比例</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[pay_rate]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">创作者等级</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[rank]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}"  lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
                                

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">1 个人类型 2 团队类型：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="1 个人类型 2 团队类型" name="type"
                                                                                                    value="{{=d.type }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">uid：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="uid" name="uid"
                                                                                                    value="{{=d.uid }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">创作者等级：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="创作者等级" name="level_num"
                                                                                                    value="{{=d.level_num }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">手机：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="手机" name="phone"
                                                                                                    value="{{=d.phone }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">0 缺省 1待审核  2 未通过  3. 禁用 4 正常 ：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="0 缺省 1待审核  2 未通过  3. 禁用 4 正常 " name="status"
                                                                                                    value="{{=d.status }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">拒绝理由：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="拒绝理由" name="refuse_reason"
                                                                                                    value="{{=d.refuse_reason }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频审核次数：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="视频审核次数" name="mv_check"
                                                                                                    value="{{=d.mv_check }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频提交数量：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="视频提交数量" name="mv_submit"
                                                                                                    value="{{=d.mv_submit }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频拒绝次数：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="视频拒绝次数" name="mv_refuse"
                                                                                                    value="{{=d.mv_refuse }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">creator_tag：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="creator_tag" name="creator_tag"
                                                                                                    value="{{=d.creator_tag }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">creator_desc：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="creator_desc" name="creator_desc"
                                                                                                    value="{{=d.creator_desc }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">update_at：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="update_at" name="update_at"
                                                                                                    value="{{=d.update_at }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">created_at：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="created_at" name="created_at"
                                                                                                    value="{{=d.created_at }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">用户昵称，和用户表保持一致：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="用户昵称，和用户表保持一致" name="nickname"
                                                                                                    value="{{=d.nickname }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">累计汤币：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="累计汤币" name="total_coins"
                                                                                                    value="{{=d.total_coins }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">扣量指标，出量率：</label>
                    <div class="layui-input-inline">

                                                    <input  placeholder="扣量指标，出量率" name="output_rate"
                                                                                                    value="{{=d.output_rate }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">提现结算比例：</label>
                    <div class="layui-input-inline">

                                                    <input  placeholder="提现结算比例" name="pay_rate"
                                                                                                    value="{{=d.pay_rate }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">创作者等级：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="创作者等级" name="rank"
                                                                                                    value="{{=d.rank }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">id：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.id }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">1 个人类型 2 团队类型：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.type }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">uid：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.uid }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">创作者等级：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.level_num }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">手机：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.phone }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">0 缺省 1待审核  2 未通过  3. 禁用 4 正常 ：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.status }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">拒绝理由：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.refuse_reason }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频审核次数：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.mv_check }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频提交数量：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.mv_submit }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频拒绝次数：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.mv_refuse }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">creator_tag：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.creator_tag }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">creator_desc：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.creator_desc }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">update_at：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.update_at }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">created_at：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.created_at }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">用户昵称，和用户表保持一致：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.nickname }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">累计汤币：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.total_coins }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">扣量指标，出量率：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.output_rate }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">提现结算比例：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.pay_rate }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">创作者等级：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.rank }}" class="layui-input">
                    </div>
                </div>
            </div>
            </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
                        , {field: 'id', title: 'id'}
                        , {field: 'type', title: '1 个人类型 2 团队类型'}
                        , {field: 'uid', title: 'uid'}
                        , {field: 'level_num', title: '创作者等级'}
                        , {field: 'phone', title: '手机'}
                        , {field: 'status', title: '0 缺省 1待审核  2 未通过  3. 禁用 4 正常 '}
                        , {field: 'refuse_reason', title: '拒绝理由'}
                        , {field: 'mv_check', title: '视频审核次数'}
                        , {field: 'mv_submit', title: '视频提交数量'}
                        , {field: 'mv_refuse', title: '视频拒绝次数'}
                        , {field: 'creator_tag', title: 'creator_tag'}
                        , {field: 'creator_desc', title: 'creator_desc'}
                        , {field: 'update_at', title: 'update_at'}
                        , {field: 'created_at', title: 'created_at'}
                        , {field: 'nickname', title: '用户昵称，和用户表保持一致'}
                        , {field: 'total_coins', title: '累计汤币'}
                        , {field: 'output_rate', title: '扣量指标，出量率'}
                        , {field: 'pay_rate', title: '提现结算比例'}
                        , {field: 'rank', title: '创作者等级'}
                        , {fixed: 'right', width: 200, title: '操作',align:'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>