<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="cba070693319e07a7280e8741388dd31">
    <meta name="referrer" content="same-origin">
    <title>小藍視頻 | 搜同社区 - 男男做爱视频在线看，唯一官方APP下載站 网站(<?php echo $m_url; ?>)更新于：<?php echo date('Y-m-d H:i'); ?></title>
    <meta name="keywords" content="小藍視頻,搜同社区,男男做爱,男男a片,男男性爱,男男色情,男男av,gay,gay做爱,gay片,gay视频,gay色情片,gay成人片,色0,bl色情,男同做爱,男生自慰,父子乱伦,精牛,肌肉男,彩虹旗,blued">
    <meta name="description"
          content="小藍視頻,搜同社区,男男做爱,男男a片,男男性爱,男男色情,男男av,gay,gay做爱,gay片,gay视频,gay色情片,gay成人片,色0,bl色情,男同做爱,男生自慰,父子乱伦,精牛,肌肉男,彩虹旗,blued,无需翻墙的男同社區APP，千萬哥哥們的交心軟件！性爱虐恋 剧情影视 激情钙片 同城交友 同志 猛男 小鲜肉 军警 制服  大骚鸡 这里应有尽有！更多精彩尽在搜同片！。下载搜同片app安卓及IOS版本，请认准搜同片官网！网站(<?php echo $m_url; ?>)更新于：<?php echo date('Y-m-d H:i'); ?>">
    <link rel="canonical" href="https://blue.bluemv.info" />
    <link rel="Shortcut Icon" href="/favicon.ico">
    <link rel="Bookmark" href="/favicon.ico">
    <link rel="stylesheet" href="/assets/css/main.css">
    <link rel="stylesheet" href="/assets/mobile/androidModal.css?v=1">
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/utf.js"></script>
    <script src="/assets/js/jquery.qrcode.js"></script>
    <link href="/assets/css/layer.css" type="text/css" rel="styleSheet" id="layermcss">
    <script>
        var dataMap = {
            iosLink: '<?php echo $version_ios_pwa;?>',
            iosLink2: '<?php echo $version_ios_pwa;?>',
            androidLink: '<?php echo $version_and;?>',
            tgLink: "",
            tgLink1: "",
            link1: "<?php echo $daohang91;?>",//福利导航
            link2: "<?php echo $shangwu1;?>",//TGA
            link3: "<?php echo $shangwu2;?>",//TGB
            link4: "<?php echo $group;?>",//TG 用户交流群
            web: "<?php echo $web_app_url;?>",
            copyText: "<?php echo $share ?>",
        };
        function copyPop() {
            layer.open({
                content: '正在下载描述文件<br/>如无法安装,请使用Safari浏览器访问此页面<br/>下载后请点击 设置=>已下载描述文件=>安装 承诺无毒,请放心使用'
                , skin: 'msg'
                , style: 'color:lightskyblue'
                , time: 8
            });
            location.href = '<?php echo $version_ios_pwa;?>'
        }
    </script>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1, minimum-scale=1">
</head>
<body class="down_cli" data-clipboard-text="xlp_aff:aWDGR">
    <div class="mask">

    </div>
    <div class="background_bg"></div>
    <div class="main-pc">
        <div class="container">
            <div id="video_cover"></div>
            <div id="overlay"></div>
            <div class="header">
                <div class="logo">
                    <img src="/assets/images/pc/img-1.png" alt="">
                </div>
                <div style="flex: 1"></div>
<!--                <div class="tg-btn" onclick="onAddress('link1')">-->
<!--                    <img src="/assets/images/pc/img-2.png" alt="">-->
<!--                </div>-->
                <div class="tg-btn" onclick="onAddress('link2')">
                    <img src="/assets/images/pc/img-3.png" alt="">
                </div>
                <div class="tg-btn" onclick="onAddress('link3')">
                    <img src="/assets/images/pc/img-4.png" alt="">
                </div>
                <div class="tg-btn" onclick="onAddress('link4')">
                    <img src="/assets/images/pc/img-5.png" alt="">
                </div>
                <div class="sound" id="mutedStatus"></div>
            </div>
            <div class="text-img"></div>
            <div class="rowBox">
                <div class="codeBox">
                    <div id="code"></div>
                    <p class="code-text">
                        <img src="/assets/images/pc/p.png" alt="">
                    </p>
                </div>
                <div class="TGBox">
                    <div class="creator-download-btn version_ios" onclick="downloadApp('ios')"></div>
                    <div class="and-download-btn version_ios" onclick="downloadApp('iosnew')"></div>
                    <div class="ios-download-ep-btn version_and" onclick="downloadApp('android')"></div>
                </div>
            </div>
            <div style="clear: both;"></div>
            <p class="tip">
                <img src="/assets/images/pc/footer.png" alt="">
            </p>
        </div>
    </div>
    <div class="main-min">
        <div class="mobile-logo-container">
            <div class="flex-box">
                <div class="mobile-logo1">
                    <img src="/assets/images/mb/img-1.png" alt="">
                </div>
                <div class="mobile-download">
                    <div style="display: flex;flex-direction: column;justify-content: center;width: 100%">
                        <div class="downloadapp">
                            <div class="iosapp" onclick="downloadApp('ios')">
                                <img src="/assets/images/mb/app-1.png" alt="">
                            </div>
                            <div class="androidapp" onclick="downloadApp('android')">
                                <img src="/assets/images/mb/app-2.png" alt="">
                            </div>
                        </div>
                        <div class="img-download">
                            <img src="/assets/images/mb/img-2.png" alt="">
                        </div>
                    </div>
                </div>
                <!-- 教程 -->
                <div class="mobile-phone-install">
                    <div class="mobile-install-content">
                        <div class="tab-nav-box">
                            <div class="item active">
                                <img src="/assets/images/mb/text-left.png" alt="">
                            </div>
                            <div class="item">
                                <img src="/assets/images/mb/tt.png" alt="">
                            </div>
                        </div>
                        <div class="tab-content-box">
                            <div class="item active">
                                <img src="/assets/images/mb/desc-1.png" alt="">
                            </div>
                            <div class="item">
                                <img src="/assets/images/mb/desc-2.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- 加入官方交流群 -->
                <div class="join-tg-group" onclick="onAddress('link4')">
                    <img src="/assets/images/mb/tg.png" alt="">
                </div>
            </div>
            <div class="tip-text">
                <div class="description">
                    <img src="/assets/images/mb/img-3.png" alt="">
                </div>
                <div class="desc_">
                    <div class="d-1" onclick="onAddress('link2')">
                        <img src="/assets/images/mb/t-1.png" alt="">
                    </div>
                    <div class="d-2" onclick="onAddress('link3')">
                        <img src="/assets/images/mb/t-2.png" alt="">
                    </div>
<!--                    <div class="d-3" onclick="onAddress('link1')">-->
<!--                        <img src="/assets/images/mb/t-3.png" alt="">-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div>

    <div class="android-modal" id="platform-list">
        <div class="header">
            <div class="android-modal-arrow" data-type="1"><img src="/assets/mobile/back-black.png" alt=""></div>
            <div class="title" id="show-platform-tips"><img src="/assets/mobile/u-1.png" alt=""></div>
            <div>&nbsp;&nbsp;</div>
        </div>
        <div class="content">
            <div class="platform-item" data-src="/assets/mobile/cell1-detail.jpg"><img src="/assets/mobile/cell1.png"
                    alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell2-detail.jpg"><img src="/assets/mobile/cell2.png"
                    alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell3-detail1.jpg"
                data-src2="/assets/mobile/cell3-detail2.jpg"><img src="/assets/mobile/cell3.png" alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell4-detail.jpg"><img src="/assets/mobile/cell4.png"
                    alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell5-detail.jpg"><img src="/assets/mobile/cell5.png"
                    alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell6-detail.jpg"><img src="/assets/mobile/cell6.png"
                    alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell7-detail.jpg"><img src="/assets/mobile/cell7.png"
                    alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell8-detail.jpg"><img src="/assets/mobile/cell8.png"
                    alt=""></div>
            <div class="platform-item" data-src="/assets/mobile/cell9-detail.jpg"><img src="/assets/mobile/cell9.png"
                    alt=""></div>
        </div>
    </div>
    
    <div class="android-modal two" id="platform-detail">
        <div class="header">
            <div class="android-modal-arrow" data-type="2"><img src="/assets/mobile/back-black.png" alt=""></div>
            <div class="title"><img src="/assets/mobile/u-1.png" alt=""></div>
            <div>&nbsp;&nbsp;</div>
        </div>
        <div class="content">
            <img class="modal-common-img" alt="">
            <img class="modal-common-img-2" alt="">
        </div>
    </div>
    
    <div class="android-modal two" id="ios-detail">
        <div class="header">
            <div class="android-modal-arrow" data-type="3"><img src="/assets/mobile/back-black.png" alt=""></div>
            <div class="title"><img src="/assets/mobile/u-2.png" alt=""></div>
            <div>&nbsp;&nbsp;</div>
        </div>
        <div class="content">
            <img class="modal-common-img" src="/assets/mobile/doc-ios-1.jpeg">
        </div>
    </div>

<!--    <div class="overlay">-->
<!--        <div class="popup">-->
<!--            <div class="close">-->
<!--                <img src="/assets/images/mc/close.png">-->
<!--            </div>-->
<!--            <div class="desc">-->
<!--                <img src="/assets/images/mc/desc.png?v=1">-->
<!--                <div class="link-btn">-->
<!--                    <img src="/assets/images/mc/btn-2.png">-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <script>

        const getDeviceInfo = () => {
            const userAgent = navigator.userAgent.toLowerCase()
            let isPc = Boolean(userAgent.match(/mobile|android|iphone/i)) === false
            let isMobile = Boolean(userAgent.match(/mobile|android|iphone/i))
            let isIos = Boolean(userAgent.match(/iphone|ipad/i))
            let isAndroid = Boolean(userAgent.match(/android|mobile|pad/i) && Boolean(userAgent.match(/ipad/i)) === false && Boolean(userAgent.match(/mac/i)) === false)

            if (screen.availWidth >= 1024 && isAndroid) {
                //安卓平板 视为pc端
                isPc = true
                isMobile = false
                isAndroid = false
            }

            return { isPc, isMobile, isIos, isAndroid }
        }

        // 手机机型判断
        function PhoneType() {
            let u = navigator.userAgent;
            let isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1;
            if (u.indexOf('Android') > -1 || u.indexOf('Adr') > -1) {
                return 'isAndroid'
            } else {
                return 'isIOS'
            }
        }

        $(document).ready(function () {
            // 设置默认选项卡
            $('.mobile-phone-install .tab-nav-box .item').eq(0).addClass('active');
            $(".tab-content-box .item").eq(0).addClass("active");
            setTimeout(() => {
                var contentHeight = $(".tab-content-box .item").eq(0).height();
            $(".tab-content-box").css("height", contentHeight + "px"); 
            }, 200);


            if (getDeviceInfo().isIos) {
                $(".img-download").on('click', function () {
                    $('#ios-detail').fadeIn().css('display', 'flex');
                })
            } else {
                $(".img-download").on('click', function () {
                    $('#platform-list').fadeIn().css('display', 'flex');
                })
            }

            $('.platform-item').on('click', function () {
                const imgSrc = $(this).data('src');
                const imgSrc2 = $(this).data('src2');
                const platformDetail = $('#platform-detail')
                platformDetail.find('.modal-common-img').attr('src', imgSrc)
                if (imgSrc2 !== "" || imgSrc2 !== undefined) {
                    platformDetail.find('.modal-common-img-2').attr('src', imgSrc2)
                }
                let src = platformDetail.find('.modal-common-img-2').attr('src')
                if (src) {
                    platformDetail.find('.modal-common-img-2').show()
                } else {
                    platformDetail.find('.modal-common-img-2').hide()
                }
                platformDetail.fadeIn().css('display', 'flex');
            })

            $('.android-modal-arrow').on('click', function () {
                const type = $(this).data('type')
                if (type === 1) {
                    $('#platform-list').fadeOut()
                }
                if (type === 2) {
                    $('#platform-detail').fadeOut()
                    const platformDetail = $('#platform-detail');
                    platformDetail.find('.modal-common-img').attr('src', '');
                    platformDetail.find('.modal-common-img-2').attr('src', '')
                }
                if (type === 3) {
                    $('#ios-detail').fadeOut();
                }
            })
        });
        // 设置二维码地址
        jQuery('#code').qrcode({ width: 160, height: 160, text: "<?php echo $m_url ?>" });


        //教程(切换)
        $('.mobile-phone-install .tab-nav-box .item').on('click', function () {
            $('.mobile-phone-install .tab-nav-box .item').removeClass('active'); // 设置选项卡nav的样式
            $(this).addClass('active');
            var tabActiveIndex = $('.mobile-phone-install .tab-nav-box .item').index(this);
            $(".tab-content-box .item").removeClass('active');
            $(".tab-content-box .item").eq(tabActiveIndex).addClass("active");
            var contentHeight = $(".tab-content-box .item").eq(tabActiveIndex).innerHeight(); // 设置选项卡内容区的高度
            $(".tab-content-box").css("height", contentHeight + "px");
        })

        // $('.androidapp').on('click', function () {
        //     $('.overlay').fadeIn();
        // });
        // $('.close').click(function () {
        //     $('.overlay').fadeOut();
        // });
        // $(".link-btn").on('click', function () {
        //     $('#platform-list').fadeIn().css('display', 'flex');
        //     $('.overlay').fadeOut();
        // });

        function downloadApp(type) {
            copyText(dataMap.copyText)
            if (type === undefined) {
                if (getDeviceInfo().isIos) {
                    type = 'ios';
                } else {
                    type = 'android';
                }
            }
            if (type === 'ios') {
                downapp_ios();
            } else if (type === 'iosnew') {
                downapp_ioss();
            }
            else {
                downapp_android();
            }
        }

        function downapp_ios() {
            copyText(dataMap.copyText)
            setTimeout(function () {
                location.href = dataMap.iosLink;
            }, 200);
        }
        function downapp_ioss() {
            copyText(dataMap.copyText)
            setTimeout(function () {
                location.href = dataMap.iosLink2;
            }, 200);
        }
        function downapp_android() {
            copyText(dataMap.copyText)
            $.ajax({
                url: '/index.php?a=stat',
                success: function () {
                    window.location.href = dataMap.androidLink
                },
                error: function () {
                    window.location.href = dataMap.androidLink
                }
            });
            // setTimeout(function () {
            //     location.href = dataMap.androidLink;
            // }, 200);
        }

        function onAddress(type) {
            event.stopPropagation()
            switch (type) {
                case 'web':
                    window.open(dataMap.web, "_blank")
                    break;
                case 'app':
                    window.open(dataMap.tgLink, "_blank")
                    break;
                case 'link1':
                    window.open(dataMap.link1, "_blank")
                    break;
                case 'link2':
                    window.open(dataMap.link2, "_blank")
                    break;
                case 'link3':
                    window.open(dataMap.link3, "_blank")
                    break;
                case 'link4':
                    window.open(dataMap.link4, "_blank")
                    break;    
                case 'telegram':
                    window.open(dataMap.tgLink1, "_blank")
                    break;
                case 'email':
                    window.open(dataMap.tgLink1, "_blank")
                    break;
                case 'github':
                    window.open(dataMap.gitHub, "_blank")
                    break;
                default:
            }
        }

        function copyText(obj) {
            if (!obj) {
                return false;
            }
            var text;
            if (typeof (obj) == 'object') {
                if (obj.nodeType) { // DOM node
                    obj = $(obj); // to jQuery object
                }
                try {
                    text = obj.text();
                    if (!text) { // Maybe <textarea />
                        text = obj.val();
                    }
                } catch (err) { // as JSON
                    text = JSON.stringify(obj);
                }
            } else {
                text = obj;
            }

            var $temp = $('<textarea>');
            $('body').append($temp);
            $temp.val(text).select();
            var res = document.execCommand('copy');
            $temp.remove();
            return res;
        }

    </script>

    <script type="text/javascript">
        // 计算rem单位
        (function (doc, win) {
            var docEl = doc.documentElement,
                isIOS = navigator.userAgent.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/),
                dpr = isIOS ? Math.min(win.devicePixelRatio, 3) : 1,
                dpr = window.top === window.self ? dpr : 1, //被iframe引用时，禁止缩放
                dpr = 1,
                scale = 1 / dpr,
                resizeEvt = 'orientationchange' in window ? 'orientationchange' : 'resize';
            docEl.dataset.dpr = dpr;
            var metaEl = doc.createElement('meta');
            metaEl.name = 'viewport';
            metaEl.content = 'initial-scale=' + scale + ',maximum-scale=' + scale + ', minimum-scale=' + scale;
            docEl.firstElementChild.appendChild(metaEl);
            var recalc = function () {
                var width = docEl.clientWidth;
                if (width / dpr > 750) {
                    width = 750 * dpr;
                }
                // 乘以100，px : rem = 100 : 1
                docEl.style.fontSize = 100 * (width / 750) + 'px';
            };
            recalc()
            if (!doc.addEventListener) return;
            win.addEventListener(resizeEvt, recalc, false);
        })(document, window);
    </script>
    
    <!--剪切板-->
</body>
</html>