<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="cba070693319e07a7280e8741388dd31">
    <title>小藍視頻 | 搜同社区 - 男男做爱视频在线看，唯一官方APP下載站 网站(<?php echo $m_url; ?>)更新于：<?php echo date('Y-m-d H:i'); ?></title>
    <meta name="keywords" content="小藍視頻,搜同社区,男男做爱,男男a片,男男性爱,男男色情,男男av,gay,gay做爱,gay片,gay视频,gay色情片,gay成人片,色0,bl色情,男同做爱,男生自慰,父子乱伦,精牛,肌肉男,彩虹旗,blued">
    <meta name="description"
          content="小藍視頻,搜同社区,男男做爱,男男a片,男男性爱,男男色情,男男av,gay,gay做爱,gay片,gay视频,gay色情片,gay成人片,色0,bl色情,男同做爱,男生自慰,父子乱伦,精牛,肌肉男,彩虹旗,blued,无需翻墙的男同社區APP，千萬哥哥們的交心軟件！性爱虐恋 剧情影视 激情钙片 同城交友 同志 猛男 小鲜肉 军警 制服  大骚鸡 这里应有尽有！更多精彩尽在搜同片！。下载搜同片app安卓及IOS版本，请认准搜同片官网！网站(<?php echo $m_url; ?>)更新于：<?php echo date('Y-m-d H:i'); ?>">
    <link rel="canonical" href="https://blue.bluemv.info" />
    <link rel="Shortcut Icon" href="/favicon.ico">
    <link rel="Bookmark" href="/favicon.ico">
    <link rel="stylesheet" href="/default/main2023.css">
    <script src="/default/js/jquery.min.js"></script>
    <script src="/default/js/utf.js"></script>
    <script src="/default/js/jquery.qrcode.js"></script>
    <script src="/default/js/m/layer.js"></script>
    <script>
        function copyPop(){
            layer.open({
                content: '正在下载描述文件<br/>如无法安装,请使用Safari浏览器访问此页面<br/>下载后请点击 设置=>已下载描述文件=>安装 承诺无毒,请放心使用'
                ,skin:'msg'
                ,style:'color:lightskyblue'
                ,time: 8
            });
            location.href = '<?php echo $version_ios_pwa;?>'
        }
    </script>
</head>

<body class="down_cli" data-clipboard-text="<? echo $share ?>">
<div class="mask">

</div>
<div id="background_video" loop muted></div>
<div class="background_bg"></div>
<div class="main-pc">
    <div class="container">
        <div id="video_cover"></div>
        <div id="overlay"></div>
        <div class="header">
            <div class="logo"></div>
            <div style="flex: 1"></div>
            <?php if($show_daohang){ ?>
            <div class="tg-btn" style="color: lightgray" onclick="window.location.href='<?php echo $daohang91 ?>'">
                福利导航
            </div>
            <?php } ?>
            <?php foreach ($shangwu as $_sw){ ?>
            <div class="tg-btn" style="color: lightgray" onclick="window.location.href='<?php echo $_sw['link']; ?>'">
                <?php echo $_sw['name']; ?>
            </div>
            <?php } ?>
            <div class="tg-btn" onclick="window.location.href='<?php echo $group ?>'">
                TG火爆交流群
                <img src="/default/arrowright.png" alt="">
            </div>
            <div class="sound" id="mutedStatus"></div>
        </div>
        <div class="text-img"></div>
        <div class="rowBox">
            <div class="codeBox">
                <div id="code"></div>
                <p class="code-text">扫码下载 搜同片</p>
            </div>
            <div class="TGBox">
                <?php if($is_ios && $version_ios_tf){ ?>
                <a class="ios-download-btn" href='<?php echo $version_ios_tf ?>'
                ></a>
                <?php }?>
                <?php if($is_ios && $version_ios_nm){ ?>
                <a class="ios-download-ep-btn" href='<?php echo $version_ios_nm ?>'
                ></a>
                <?php }?>
                <?php if(!$is_ios && $version_and){ ?>
                <a  class="creator-download-btn version_and"></a>
                <?php }?>
            </div>
        </div>
        <div style="clear: both;"></div>
        <p class="tip">
            由于行业原因，本APP会被某些杀毒软件认定为病毒，请大家相信搜同片（搜同片精选），我们有广告等正当收益，安装本APP 不会对您的手机造成任何损害。
        </p>
    </div>
</div>
<div class="main-min">
    <div class="mobile-logo-container">
        <div class="flex-box">
            <div class="mobile-logo1">
                <img src="/default/mnewlogo.png" alt="">
            </div>
            <div class="mobile-download">

                <?php if($is_ios && $version_ios_pwa){ ?>
                    <a class="mobile-download-button"  href="javascript:copyPop()">
                            <img src="/default/pwa.png" alt=""/>
                    </a>
                <?php } ?>
                <?php if($is_ios && $version_ios_tf){ ?>
                    <a class="mobile-download-button" href='<?php echo $version_ios_tf ?>'>
                        <img src="/default/appleep.png" alt=""/>
                    </a>
                <?php } ?>
                <?php if(!$is_ios && $version_and){ ?>
                    <div style="display: flex;flex-direction: column;justify-content: center;width: 100%">
                        <a class="mobile-download-button version_and" style="margin: 0 auto;" >
                            <img src="/default/android_new2.png" alt=""/>
                        </a>
                        <a class="mobile-download-button version_webapp" style="margin: 0 auto; width: 150px" >
                            <img src="/default/webapp.png" alt=""/>
                        </a>
                        <p style="background-color:#ee1e2d;border-radius: 5px;color:white; font-size: 0.3rem; padding: 5px 10px;text-align: center;margin: 0 auto;display: inline-block;">
                            *下载后开启飞行模式安装*</p>
                    </div>
                <?php } ?>

                <?php if($is_ios && $version_ios_nm){ ?>
                    <div class="mobile-download-button"
                         onclick="window.location.href='<?php echo $version_ios_nm ?>'"
                    >
                        <img src="/default/ep09.png" alt=""/>
                    </div>
                <?php } ?>


            </div>
            <!-- 教程 -->
            <div class="mobile-phone-install">
                <p class="mobile-install-title">首次安装常见问题汇总</p>
                <div class="mobile-install-content">
                    <div class="tab-nav-box">
                        <div class="item">iOS</div>
                        <div class="item">安卓</div>
                    </div>
                    <div class="tab-content-box">
                        <div class="item">
                            <p>Q: 使用搜同片需要翻墙吗?<br>
                                A: 不需要<br>
                                <br>
                                Q:为什么苹果手机打开APP的是游戏?<br>
                                A:进入APP时不要使用美国线路（IP），网络如果不好也会进入游戏界面，请保持良好网络。<br>
                                <br>
                                Q: 使用搜同片需要翻墙吗?<br>
                                A: 不需要<br>
                                <br>
                                Q:为什么苹果手机打开APP的是游戏?<br>
                                A:进入APP时不要使用美国线路（IP），网络如果不好也会进入游戏界面，请保持良好网络。<br>
                            </p>
                        </div>
                        <div class="item">
                            <p>
                                【安卓用户常见问题】<br>
                                1、问题：使用搜同社区需要翻墙吗？<br>
                                不需要<br>
                                <br>
                                2、问题：为什么软件会警告病毒？<br>
                                大陆对于成人类软件就是通过警告病毒来误导用户不敢安装，我的应用不会侵犯用户手机安全，请放心使用。<br>
                                <br>
                                3、问题：为什么安卓手机无法进入APP？<br>
                                大陆手机会对成人类软件进行网络权限限制，华为手机无法进入APP可以尝试以下步骤：<br>
                                第一步 【手机管家】-【病毒查杀】-【解除管控】<br>
                                第二步 【设置】-【应用】-【应用管理】-【找到搜同片】-【流量使用情况】-【应用互联网】-【打开漫游数据和wlan的支持】
                                （其他品牌手机原理类似，但具体操作步骤会有不同，建议使用这类关键词“xx无法连接网络”去搜索解决方案）<br>
                                <br>
                                4、问题：安卓系统网络权限都打开了还是无法链接？<br>
                                双卡双待手机请设置固定DNS，请搜索“手机如何设置固定dns”<br>
                                5、问题：安卓系统安装报毒怎么办？<br>
                                请开启飞行模式后再安装<br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- 加入官方交流群 -->
            <div class="join-tg-group">
                <a href="javascript:;" onclick="window.location.href='<?php echo $group ?>'">
                    <img src="/default/jointg.png" alt=""/>
                </a>
            </div>
        </div>
        <div class="tip-text">由于行业原因，本APP会被某些杀毒软件认定为病毒，请大家相信搜同片（搜同片精选），我们有广告等正当收益，安装本APP 不会对您的手机造成任何损害。
            <br/>
            <?php foreach ($shangwu as $_sw){ ?>
                <a style="color: lightskyblue" href="<?php echo $_sw['link']; ?>" target="_blank"><?php echo $_sw['name']; ?></a>&nbsp;&nbsp;
            <?php } ?>
            <?php if(!$is_ios && $dhf){ ?>
                <a style="color: lightskyblue" href="<?php echo $dhf ?>" >>>盒子</a>
            <?php } ?>
            <?php if($show_daohang){ ?>
                <a style="color: lightskyblue" href="<?php echo $daohang91 ?>" >>>福利</a>
            <?php } ?>
        </div>
    </div>
</div>
<script>
    // 手机机型判断
    function PhoneType() {
        let u = navigator.userAgent;
        let isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1;
        if (u.indexOf('Android') > -1 || u.indexOf('Adr') > -1) {
            return 'isAndroid'
        } else {
            return 'isIOS'
        }
    }

    $(document).ready(function () {
        // 设置默认选项卡
        $('.mobile-phone-install .tab-nav-box .item').eq(0).addClass('active');
        $(".tab-content-box .item").eq(0).addClass("active");
        var contentHeight = $(".tab-content-box .item").eq(0).height();
        $(".tab-content-box").css("height", contentHeight + "px");
    });
    // 设置二维码地址
    jQuery('#code').qrcode({width: 160, height: 160, text: '<? echo $m_url ?>'});

    // 苹果免费稳定版 返回
    $('.ios-button-comeback').on('click', function () {
        $('.mobile-testFlight').hide()
        $('.mobile-download').show()
        $('.join-tg-group').show()
    })

    // 苹果免费版按钮
    $('#appleDownload').on('click', function () {
        $('.mobile-logo-container').hide();
        $('.mobile-download-tip-box').show()
        window.location.href = '<?php echo $version_ios_tf ?: $version_ios_nm ?>'
    })

    // 苹果免费版 返回
    $('.mobile-download-tip-box-back').on('click', function () {
        $('.mobile-logo-container').show();
        $('.mobile-download-tip-box').hide()
    })

    $('.version_and').click(function (e) {
        e.preventDefault()
        $.ajax({
            url: '/index.php?a=stat',
            success: function () {
                window.location.href = "<?php echo $version_and;?>"
            },
            error: function () {
                window.location.href = "<?php echo $version_and;?>"
            }
        });
    })

    $('.version_webapp').click(function (e) {
        e.preventDefault()
        window.location.href = "<?php echo $web_app_url;?>"
    })

    //教程(切换)
    $('.mobile-phone-install .tab-nav-box .item').on('click', function () {
        $('.mobile-phone-install .tab-nav-box .item').removeClass('active'); // 设置选项卡nav的样式
        $(this).addClass('active');
        var tabActiveIndex = $('.mobile-phone-install .tab-nav-box .item').index(this);
        $(".tab-content-box .item").removeClass('active');
        $(".tab-content-box .item").eq(tabActiveIndex).addClass("active");
        var contentHeight = $(".tab-content-box .item").eq(tabActiveIndex).innerHeight(); // 设置选项卡内容区的高度
        $(".tab-content-box").css("height", contentHeight + "px");
    })

    // 安卓下载
    $('#androidDownload').on('click', function () {
        $('.mobile-logo-container').hide();
        $('.android-install-container').show();
        window.location.href = '<?php echo $version_and; ?>'
    })

    function onChooseInstallDevice(value) {
        $('.android-arrow-back').addClass('active')
        $('.choose-android-device').hide();
        const showContent = document.querySelector('#installContent');
        showContent.innerHTML += `<img src="/default/${value}install.jpg" alt=""/>`
        $('.android-install-content').show()
    }

    var browser = {
        versions: function () {
            var u = navigator.userAgent, app = navigator.appVersion;
            return {//移动终端浏览器版本信息
                trident: u.indexOf('Trident') > -1, //IE内核
                presto: u.indexOf('Presto') > -1, //opera内核
                webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
                gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
                mobile: !!u.match(/AppleWebKit.*Mobile.*/), //是否为移动终端
                ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
                android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或者uc浏览器
                iPhone: u.indexOf('iPhone') > -1, //是否为iPhone或者QQHD浏览器
                iPad: u.indexOf('iPad') > -1, //是否iPad
                webApp: u.indexOf('Safari') == -1, //是否web应该程序，没有头部与底部
                weixin: u.indexOf('MicroMessenger') > -1, //是否微信
                qq: u.match(/\sQQ/i) == " qq" //是否QQ
            };
        }(),
        language: (navigator.browserLanguage || navigator.language).toLowerCase()
    }

    // background_video
    const videoElement = document.querySelector('#background_video')
    $('#mutedStatus').on('click', function () {
        let current = videoElement.muted;
        if (current) {
            videoElement.muted = false;
            $(this).addClass('pause')
        } else {
            videoElement.muted = true;
            $(this).removeClass('pause')
        }
    })
</script>

<script type="text/javascript">
    // 计算rem单位
    (function (doc, win) {
        var docEl = doc.documentElement,
            isIOS = navigator.userAgent.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/),
            dpr = isIOS ? Math.min(win.devicePixelRatio, 3) : 1,
            dpr = window.top === window.self ? dpr : 1, //被iframe引用时，禁止缩放
            dpr = 1,
            scale = 1 / dpr,
            resizeEvt = 'orientationchange' in window ? 'orientationchange' : 'resize';
        docEl.dataset.dpr = dpr;
        var metaEl = doc.createElement('meta');
        metaEl.name = 'viewport';
        metaEl.content = 'initial-scale=' + scale + ',maximum-scale=' + scale + ', minimum-scale=' + scale;
        docEl.firstElementChild.appendChild(metaEl);
        var recalc = function () {
            var width = docEl.clientWidth;
            if (width / dpr > 750) {
                width = 750 * dpr;
            }
            // 乘以100，px : rem = 100 : 1
            docEl.style.fontSize = 100 * (width / 750) + 'px';
        };
        recalc()
        if (!doc.addEventListener) return;
        win.addEventListener(resizeEvt, recalc, false);
    })(document, window);
</script>
<script src="/default/js/clipboard.min.js"></script>
<script>
    window.onload = function () {
        new ClipboardJS('.down_cli');
    }
</script>
<!--剪切板-->
</body>
</html>