<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <!-- cache control -->
        <meta http-equiv="Pragma" content="no-cache,no-store,must-revalidate" />
        <meta http-equiv="Cache-Control"
            content="Cache-Control: no-store, no-cache, max-age=0, must-revalidate, proxy-revalidate" />
        <meta http-equiv="Expires" content="0" />
        <meta name="referrer" content="same-origin">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/lottery-hn/css/style.css">
        <script src="/lottery-hn/js/jquery-3.6.3.min.js"></script>
        <script src="/lottery-hn/js/jquery.tmpl.min.js"></script>
        <script src="/lottery-hn/js/adaptation.js"></script>
        <script src="/lottery-hn/js/carousel.js" defer></script>
        <script src="/lottery-hn/js/popups.js" defer></script>
        <script src="/lottery-hn/js/turntable.js?v=1" defer></script>
        <script src="/lottery-hn/js/sweetalert2.js"></script>
        <title>春节盛会</title>
        <meta name="keywords" content="春节盛会">
        <meta name="description" content="春节盛会">
        <script>
    </script>
    </head>

    <body>
    <script id="template" type="text/x-jQuery-tmpl">
    <div class="container">
        <div class="wrap-body" id="blur">
            <div class="round-area">
                <div class="title-header">
                    <img src="/lottery-hn/images/img-2.png" class="icon-header" alt>
                    <div class="icon-txt" id="scroll-list">
                        <ul>
                            {{each(i, e) hots}}
                                <div>恭喜 “{{= e.nick_name}}抽奖活动中获得 {{= e.hint}}”</div>
                            {{/each}}
                        </ul>
                    </div>
                </div>
                <div class="txt-img">
                    <img src="/lottery-hn/images/img-3.png" alt >
                </div>
                <div class="content-1">
                    <img src="/lottery-hn/images/img-4.png?v=1" alt id="spin">
                    <div class="round-icon">
                        <img src="/lottery-hn/images/u-1.png" class="pointer" alt>
                    </div>
                </div>
                <div class="leg">
                    <img src="/lottery-hn/images/img-6.png" alt>
                    <div class="txt">
                         你有 <span class="number">{{= chance}}</span> 次抽奖机会
                    </div>
                </div>
                <div class="content-2 act-1">
                    <img src="/lottery-hn/images/img-7.png" alt>
                </div>
                <div class="content-3">
                    <img src="/lottery-hn/images/img-8.png" alt>
                </div>
            </div>
            <div class="contact-us">
                中奖记录
            </div>

            <div class="box-2">
                <img src="/lottery-hn/images/img-9.png" alt>
            </div>
        </div>

        <div id="myPopup">
            <div class="contact-msg">
                <div class="contact_">
                    <div class="header">
                        <h3>恭喜中奖</h3>
                    </div>
                    <div class="body-txt" id="warn-content">

                    </div>
                    <div class="f-img ok">
                        <img src="/lottery-hn/images/i-3.png" alt>
                        <span>继续</span>
                    </div>
                </div>
            </div>
        </div>

        <div id="myPopupList">
            <div class="contact-msg">
                <div class="contacts">
                    <div class="header">
                        <div class="txt-list-popup">抽奖记录</div>
                        <img src="/lottery-hn/images/close.png" class="close-icon" alt>
                    </div>
                    <div class="body-text" id="warn-content">
                        <div class="lists">
                            <div class="list">
                                <div class="avatar">
                                    <strong>活动类型</strong>
                                </div>
                                <div class="name">
                                    <strong>
                                        奖品
                                    </strong>
                                </div>
                                <div class="desc">
                                    <strong>
                                        时间
                                    </strong>
                                </div>
                            </div>
                            {{each(i, e) historys}}
                            <div class="list">
                                <div class="avatar">
                                    <span>{{= e.type}}</span>
                                </div>
                                <div class="name">
                                    <span>{{= e.bi}}</span>
                                </div>
                                <div class="desc">
                                    <span>{{= e.date}}</span>
                                </div>
                            </div>
                            {{/each}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>
<script>
    function scrollUserList() {
        $('#scroll-list ul').animate({ marginTop: '-40px' }, 1000, function(){
            $(this).css({ marginTop: "0" }).find(":first").appendTo(this)
        })
    }

    $(document).ready(function () {
        $(".contact-us").on('click', function () {
            //$('#lists').fadeIn().css('display', 'flex');
            var myPopupList = document.getElementById("myPopupList");
            myPopupList.classList.toggle("active");
        });

        $(".header").on('click', function () {
            $("#myPopupList").removeClass("active");
        });

        setInterval(function () {
            scrollUserList()
        },3000)

        // 积分余额
        $('#point-value').text(1000)

        // 1. 初始数据
        const data = {

            //用户信息
            code: '<?php echo $code; ?>',

            // 中奖名单
            hots: <?php echo $top_list; ?>,

            // 活动日期
            datatime: '',

            // 抽奖次数
            chance: '<?php echo $lottery_times; ?>',

            // 奖品列表
            awards: [
                {
                    value: 0,
                    text: "1088金币",
                    rotate: 3600
                },
                {
                    value: 1,
                    text: "588金币",
                    rotate: 3630
                },
                {
                    value: 2,
                    text: "288金币",
                    rotate: 3660
                },
                {
                    value: 3,
                    text: "暗网年卡",
                    rotate: 3690
                },
                {
                    value: 4,
                    text: "暗网月卡",
                    rotate: 3720
                },
                {
                    value: 5,
                    text: "10金币",
                    rotate: 3760
                },
                {
                    value: 6,
                    text: "至尊通卡",
                    rotate: 3790
                },
                {
                    value: 7,
                    text: "88金币",
                    rotate: 3810
                },
                {
                    value: 8,
                    text: "王者通卡",
                    rotate: 3840
                },
                {
                    value: 9,
                    text: "188金币",
                    rotate: 3870
                },
                {
                    value: 10,
                    text: "永久VIP",
                    rotate: 3900
                },
                {
                    value: 11,
                    text: "３～６金币",
                    rotate: 3930
                }
            ],

            // 抽奖历史
            historys: <?php echo $user_award; ?>,

        };

        // 2. 初始加载
        const reLoad = (e = null) => {
            // 获取数据
            const tempdata = { ...data, ...(e ?? {}) }

            // 获取模板
            let template = $("#template").html();

            // 模板编译
            let temphtml = $.tmpl(template, tempdata);

            // 页面渲染
            $("body").html(temphtml);
        }

        // 3. 开始加载
        reLoad();

        // 4. 抽奖操作
        $(document).on('click', '.pointer', (event) => {
            if (data.chance == 0){
                Swal.fire({
                    title: "温馨提示",
                    html: "抽奖次数不足，请前往商城充值获取抽奖次数",
                    confirmButtonText: "确认",
                });
                return;
            }
            $.ajax({
                url: '/index.php?m=lottery&a=draw',
                data: {'code': data.code},
                type: 'POST',
                success: function (res) {
                    if (res.code == 0) {
                        onPointerStart(data.awards, res.data.index, res.data.hint).then((e)=>{
                            $('.number').html(res.data.chance);
                        });
                    } else {
                        Swal.fire({
                            title: "温馨提示",
                            html: res.data,
                            confirmButtonText: "确认",
                        });
                    }
                }
            })
        });

        // 5. 重置抽奖
        $(document).on('click', '.ok', (event) => onPointerOver().then((e)=>{
            // 刷新页面、数据更新 ~ 示例
            // 注意：如果没必要模板刷新(全局), 请通过jQuery指定更新(局部)
            // reLoad();
            location.reload();
        }));
    });

</script>
</body>

</html>

