<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">vid</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[vid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">status</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('status', PitTopModel::STAT) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>

                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="600" data-h="500" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">视频编号：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="vid" name="vid"
                       value="{{=d.vid }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('status', PitTopModel::STAT, ['data-value' => '{{=d.status}}']) ?>
            </div>

        </div>

        <div class="layui-form-item">

            <label class="layui-form-label">评语：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="comment" name="comment"
                       value="{{=d.comment }}" class="layui-input">

            </div>

        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id',width: 80}
            , {field: 'vid', title: '视频',edit:true,width: 100}
            , {
                field: 'mv_title', title: '视频信息', width: 300, templet: function (d) {
                    return "<span style='color: orangered'>[" + d.vid + "] " + d.mv_title +" coins:【"+ d.mv_coins + "】</span>";
                }
            }
            , {
                field: 'mv_img_thumb', title: '图标', width: 100, templet: function (d) {
                    return '<img src="' + d.mv_img_thumb + '" style="width: 100px;height: 80px;" onclick="show_img(\'' + d.mv_img_thumb + '\')">';
                }
            }, {
                field: 'mv_pre_href', title: '播放源', width: 100, templet: function (d) {
                    return "<a class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.mv_pre_href + "')\"><i class='layui-icon layui-icon-play'></i>Pre</a>";
                }
            }, {
                field: 'mv_full_href', title: '播放源', width: 100, templet: function (d) {

                    return "<a class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.mv_full_href + "')\"><i class='layui-icon layui-icon-play'></i>Full</a>";
                }
            }
            , {field: 'status', title: '状态', type: 'switch', value: '1|0', edit: true,width: 100}
            , {field: 'comment', title: '评语',edit: true}
            , {field: 'created_at', title: '时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>