<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">关联ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[pid]" placeholder="请输入"
                                       autocomplete="off" class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>



<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">用户AFF：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="用户AFF" name="aff"
                       value="{{=d.aff }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">关联类型：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('relate_type', PornMediaModel::TYPE_RELATE_TIPS, ['data-value' => '{{=d.relate_type}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">关联ID：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="pid" name="pid"
                       value="{{=d.pid }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">资源类型：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('type', PornMediaModel::TYPE_TIPS, ['data-value' => '{{=d.TYPE_TIPS}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">资源地址：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="资源地址" name="media_url" value="{{=d.media_url }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('status', PostMediaModel::STATUS_TIPS, ['data-value' => '{{=d.status}}']) ?>
                </div>
            </div>
        </div>


        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<?php
$w = [];
if(isset($_GET['pid']) && $_GET['pid']){
    $w['where[pid]'] = (int)$_GET['pid'];
}
?>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax",$w) ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id',sort:true}
            , {field: 'pid', title: '黄游ID'}
            , {field: 'cover', title: '封面',templet: function (d) {
                    if(d.cover){
                        return '<img src="' + d.cover + '" style="width: 40px;height: 40px;" onclick="show_img(\'' + d.cover + '\')">';
                    }
                    return '';
                }
            }
            , {field: 'media_url', title: '视频或图片地址',templet:function (d){
                    if (d.media_url) {
                        if (d.media_flag == 0) {
                            return '<img src="' + d.media_url_full + '" style="width: 40px;height: 40px;" onclick="show_img(\'' + d.media_url_full + '\')">';
                        } else if (d.media_flag == 1) {// mp4
                            return "<a class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.media_url_full + "')\"><i class='layui-icon layui-icon-play'></i>MP4</a>"
                        } else if (d.media_flag == 2) {// m3u8
                            let html = "<a class='layui-btn layui-btn-sm layui-btn-xs' target='_blank' href='"
                                + d.media_url_full + "'><i class='layui-icon layui-icon-play'></i>浏览器</a>"
                            return html
                        }
                    }
                    return '';

                }}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event:{
            operate:{

            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>