<?php importView("header.phtml"); ?>
    <body>
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">角色名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[name]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"
                           lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" id="user-edit-dialog" data-w="1000" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">角色名称：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="角色名称" name="name"
                           value="{{=d.name }}" class="layui-input">
                </div>
            </div>
        </div>

        <!--            {{# if(!d.id) { }}-->
        <!--            <div class="layui-form-item">-->
        <!--                <div class="layui-inline">-->
        <!--                    <label class="layui-form-label">密码：</label>-->
        <!--                    <div class="layui-input-inline">-->
        <!--                        <input lay-verify="required" placeholder="密码" name="password" class="layui-input">-->
        <!--                    </div>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--            {{# }}}-->
        <div class="layui-form-item">
            <label class="layui-form-label">角色规则：</label>
            <div class="layui-input-block">
                <div id="adminrole_div" class="xtree_contianer" style="margin-bottom: 30px"></div>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">角色描述：</label>
            <div class="layui-input-block">
                <?php echo Layui::textarea('desc', '{{=d.desc }}', ['placeholder' => '角色描述']) ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<style>
    .layui-xtree-item > .layui-xtree-item {
        display: inline-block;
        width: 80px;
    }

    .layui-xtree-item > .layui-form-checkbox {
        display: block;
    }
</style>
<script src="<?php echo LAY_UI_STATIC ?>layuiadmin/layui-xtree.js"></script>
<script>
    layui.config({
        base: '<?php echo LAY_UI_STATIC ?>layuiadmin/' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    });
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        updateUrl: "",
        title: '数据表',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id'}
            , {field: 'name', title: '角色名称'}
            , {field: 'desc', title: '角色描述'}
            , {field: 'rule', title: '角色规则'}
            , {field: 'updated_at', title: 'updated_at'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
        , event: {
            "renderTree": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                var ruleArray = obj.data.rule.split(','), menudata = xx.config('menu'), treeJson = [];
                $.each(menudata, function (i, item, data) {
                    data = {
                        "title": item.name,
                        "value": item.id,
                        "inputname": 'rule[]',
                        "checked": in_array(item.id, ruleArray),
                        "data": [],
                    };
                    if (typeof (item.children) !== "undefined") {
                        $.each(item.children, function (i, item) {
                            data.data.push({
                                "title": item.name,
                                "value": item.id,
                                "inputname": 'rule[]',
                                "checked": in_array(item.id, ruleArray),
                                "data": [],
                            })
                        });
                    }
                    treeJson.push(data);
                });
                nextFn();
                new layuiXtree({
                    elem: 'adminrole_div'
                    , form: form
                    , data: treeJson
                });
            },
            "operate": {
                "edit": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, tpl, layerEle, form, $, nextFn)
                }
            },
            "toolbar": {
                "addUser": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                    obj.data = {
                        rule: ""
                    };
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, tpl, layerEle, form, $, nextFn)
                }
            }
        }
        , "done": function (table, data, from, ajax, tpl, $) {
            ajax.get("<?php echo url_backend('adminMenu/treeList')?>")
                .then(function (json) {
                    return json.data;
                })
                .then(function (data) {
                    xx.use({"menu": data})
                })
        }
    })
</script>
<script type="text/javascript" src="<?php echo LAY_UI_STATIC ?>data-list.js"></script>
<?php importView("fooler.phtml"); ?>