<?php include __DIR__ . "/../layout/header.phtml";?>
<div class="row">
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <div class="table-responsive">
                    <div class="row">
                        <form action="d.php" method="get">
                            <input type="hidden" name="mod" value="user">
                            <input type="hidden" name="code" value="userActionLog">
                            <div class="col-sm-2">
                                <input class="input-sm form-control input-s-sm inline" placeholder="UUID" type="text"
                                       name="uuid" value="<?=$uuid;?>">
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-sm btn-primary"> 搜索</button>
                            </div>
                        </form>
                    </div>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th>操作项</th>
                            <th>管理员操作说明</th>
                            <th>管理人员</th>
                            <th>用户uuid</th>
                            <th>备注</th>
                            <th>操作时间</th>
                          <!--  <th>详情</th>-->
                        </tr>
                        </thead>
                        <tbody>
                        <?php if($data):?>
                        <!--<?php foreach ($data as $k=>$v) :?>-->
                        <tr>
                            <td><?=$v['id'];?></td>
                            <td><?=$v['name'];?></td>
                            <td><?=$v['extra'];?></td>
                            <td><?=$v['username'];?></td>
                            <td><?=$v['operated_user'];?></td>
                            <td><?=$v['description'];?></td>
                            <td><?=$v['created_at'];?></td>
                           <!-- <th><a class="btn btn-xs btn-danger" onclick="changedetail(<?=$v['id'];?>)">查看更改详情</a></th>-->
                        </tr>
                        <!--<?php endforeach; ?>-->
                        <?php else:?>
                        <tr>
                            <td colspan="16">暂无数据</td>
                        </tr>
                        <?php endif;?>
                        </tbody>
                    </table>
                </div>
                <?=$page_arr['html'];?>
            </div>
        </div>
    </div>

</div>
<script>



    function changedetail(id) {
        var url = "d.php?mod=user&code=changedetail&id=" + id;
        layerOpen(url, '查看更改详情')
    }

    function collectionList(uuid) {
        var url = "d.php?mod=user&code=listUserSaved&uuid=" + uuid;
        layerOpen(url, '收藏记录')
    }

    function downloadList(uuid) {
        var url = "d.php?mod=user&code=listDownload&uuid=" + uuid;
        layerOpen(url, '下载记录')
    }

    function searchList(uuid) {
        var url = "d.php?mod=user&code=listUserSearchLog&uuid=" + uuid;
        layerOpen(url, '搜索记录')
    }

    function chatList(uuid) {
        var url = "d.php?mod=user&code=chatList&uuid=" + uuid;
        layer.open({
            type: 2,
            title: '用户私聊',
            closeBtn: 1,
            shadeClose: true,
            shade: [0.5],
            area: ['370px', '600px'],
            content: url
        })
    }

    function coinsInfo(uuid) {
        var url = "d.php?mod=static&code=gold&uuid=" + uuid;
        layerOpen(url, '金币明细')
    }

    function layerOpen(url, title) {
        layer.open({
            type: 2,
            title: title,
            closeBtn: 1,
            shadeClose: true,
            shade: [0.5],
            area: ['1000px', '800px'],
            content: url
        })
    }

    function getAjax(url) {
        $.ajax({
            url: url,
            type: 'GET',
            success: function (res) {
                if (res.status == 1) {
                    layer.msg(res.data, {icon: 1})
                } else {
                    layer.msg(res.data, {icon: 5})
                }
            }
        })
    }

    function reload(msg) {
        parent.layer.msg(msg, {icon: 1});
        window.location.reload()
    }
</script>
<?php include __DIR__ . "/../layout/footer.phtml";?>
