<?php include __DIR__ . "/../layout/header.phtml";?>
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <form class="form-horizontal" >
                        <input type="hidden" id="id" value="<?=$data['id'];?>">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">问题：</label>
                            <div class="col-sm-8">
                                <input type="text" placeholder="问题" class="form-control" id="question" value="<?=$data['question'];?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">答案(需要换行用#分割)：</label>
                            <div class="col-sm-8">
                                <input type="text" placeholder="答案" class="form-control" id="answer" value="<?=$data['answer'];?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">问题类型：</label>
                            <div class="col-sm-8">
                                <select class="form-control m-b" id="type">
                                    <!--{loop $this->user_help_type $k $v}-->
<!--                                        <option value="--><?//=$k;?><!--" --><?php //if($data['type']==$k):?><!--selected--><?php //endif;?><!-->--><?//=$v;?><!--</option>-->

                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">状态：</label>
                            <div class="col-sm-8">
                                    <select class="form-control m-b" id="status">
                                        <option value="0" <?php if($data['status']==0):?> selected<?php endif;?>>开启</option>
                                        <option value="1" <?php if($data['status']==1):?> selected<?php endif;?>>关闭</option>
                                    </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-8">
                                <button class="btn btn-sm btn-white" type="button" onclick="handleEdit()">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
<script>
    var index = parent.layer.getFrameIndex(window.name);
    function handleEdit() {
        var data = {
            mod: 'user',
            code: 'dohelpedit',
            FORMHASH: '<?=$formhash;?>',
            data: {
                id: $('#id').val(),
                question: $('#question').val(),
                answer: $('#answer').val(),
                type: $('#type').val(),
                status: $('#status').val()
            }
        }
        console.log(data);
        $.ajax({
            url: 'd.php',
            data: data,
            type: 'POST',
            success: function (res) {
                if (res.status == 1) {
                    parent.reload(res.data)
                    parent.layer.close(index)

                } else {
                    layer.msg(res.data, {icon: 5})
                }
            }
        })
    }
    function layerOpen(url, title) {
        layer.open({
            type: 2,
            title: title,
            closeBtn: 1,
            shadeClose: true,
            shade: [0.5],
            area: ['800px', '800px'],
            content: url
        })
    }

    function getAjax(url) {
        $.ajax({
            url: url,
            type: 'GET',
            success: function (res) {
                if (res.status == 1) {
                    layer.msg(res.data, {icon: 1})
                } else {
                    layer.msg(res.data, {icon: 5})
                }
            }
        })
    }
</script>
        <?php include __DIR__ . "/../layout/footer.phtml";?>
