<?php include __DIR__ . "/../layout/header.phtml";?>
<form action="d.php?mod=version&code=recommend" method="post">
    <table cellspacing="1" width="100%" align="center" class="tableborder">
        <tbody>
        <tr class="header">
            <td class="altbg1"><input type="text" name="flag" placeholder="aff" style="width: 200px">
                <input class="button lf" type="submit" name="setting_submit" id="setting_submit" value="搜索">
            </td>
        </tr>
        </tbody>
    </table>
</form>
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tableborder">
    <tr class="header">
        <td>
            发起邀请id
            (
            <a href="<?=$query_link;?>&sort=inviteasc">↑</a>
            |
            <a href="<?=$query_link;?>&sort=invitedesc">↓</a>
            )
        </td>
        <td>受邀人id</td>
        <td>注册ip</td>
        <td>注册时间</td>

    </tr>
    <?php if($topic):?>
    <!--<?php foreach ($topic as $k=>$v) :?>-->
    <tr>
        <td><?=$v['invited_by'];?></td>
        <td><?=$v['uid'];?></td>
        <td>
            <a href="http://ip.zxinc.org/ipquery/?ip=<?=$v['regip'];?>&action=2" target="_blank"><?=$v['regip'];?></a>
        </td>
        <td><?=$v['regdate'];?></td>
    </tr>
    <!--<?php endforeach; ?>-->
    <?php else:?>
    <tr>
        <td colspan="16">暂无数据</td>
    <tr/>
    <?php endif;?>
</table>
<br>
<?=$page_arr['html'];?>
<br>
<br>
</body>
</html>
