<?php include __DIR__ . "/../layout/header.phtml";?>
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <form class="form-horizontal">
                        <input type="hidden" id="id" name="id" value="<?=$data['id'];?>">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">模板内容：</label>
                            <div class="col-sm-8">
                                <input type="text" placeholder="模板内容" class="form-control" id="title" value="<?=$data['title'];?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-8">
                                <button class="btn btn-sm btn-white" type="button" onclick="handleEdit($data['id'])">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <script>
            var index = parent.layer.getFrameIndex(window.name);
            function handleEdit(id) {
                var title = $("#title").val();
                var url = "d.php?mod=user&code=doreplyedit&id=" + id+"&title="+title;
                window.location.href = url;
            }
        </script>
        <?php include __DIR__ . "/../layout/footer.phtml";?>
