<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<script type="text/html" id="search-total">
    <p style="font-size: medium;margin-left: 10px;">
        统计数据： 帖子总数:{{=d.totalPost}}, VIP帖子:{{=d.totalVipPost}}, 金币帖子: {{=d.totalCoinsPost}}, 帖子收益: {{=d.totalPostCoins}}
    </p>
</script>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">帖子管理<span style="color: red" class="layui-inline" id="total-id"></span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">话题ID</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[topic_id]', merge_array(['' => '请选着'], $topicArr)) ?>
                            </div>
                        </div>
                        
                        <div class="layui-inline">
                            <label class="layui-form-label">用户AFF</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[aff]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">删除 </label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_deleted]', merge_array(['' => '请选着'], GirlModel::DELETED_TIPS)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">置顶 </label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[set_top]', merge_array(['' => '请选着'], GirlModel::TOP_TIPS)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">置精</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_best]', merge_array(['' => '请选着'], GirlModel::BEST_TIPS)) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">帖子类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[category]', merge_array(['' => '请选着'], GirlModel::TYPE_TIPS)) ?>

                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">创建时间</label>
                            <div class="layui-input-block">
                                <?php echo Layui::dateBetween('created_at') ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">添加</button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a lay-event="edit" lay-form="user-edit-dialog" style="color: blue">修改</a> |
                        <a data-pk="{{=d.id}}" lay-event="del" style="color: red">删除</a> |
                        <a lay-event="refresh" data-id="{{d.id}}" style="color: blue">涮新</a>
                        <br>
                       {{# if(d.photo_num > 0){ }}
                       <a lay-event="img" lay-form="img-dialog" >图片</a> |
                       {{# } }}
                       {{# if(d.video_num > 0){ }}
                       <a lay-event="video" lay-form="video-dialog">视频</a> |
                       {{# } }}
                       <a lay-event="element" lay-form="element-dialog">评论</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <label class="layui-form-label">标题：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="标题" name="title"
                       value="{{=d.title }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">圈子：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('topic_id', $topicArr, ['data-value' => '{{=d.topic_id}}']) ?>
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">aff：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="aff" name="aff" value="{{d.aff || 0 }}"
                           class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">内容：</label>
            <div class="layui-input-block">
                <textarea rows="10" name="content" class="layui-textarea">{{d.content || '' }}</textarea>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">图片：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadPos('img_0', 'img_0') ?>
                <?php echo Layui::uploadPos('img_1', 'img_1') ?>
                <?php echo Layui::uploadPos('img_2', 'img_2') ?>
                <?php echo Layui::uploadPos('img_3', 'img_3') ?>
                <?php echo Layui::uploadPos('img_4', 'img_4') ?>
                <?php echo Layui::uploadPos('img_5', 'img_5') ?>
                <?php echo Layui::uploadPos('img_6', 'img_6') ?>
                <?php echo Layui::uploadPos('img_7', 'img_7') ?>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面：</label>
                <div class="layui-input-block">
                    <?php echo Layui::uploadPos('video_img', 'video_img') ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">视频时长：</label>
                <div class="layui-input-inline">
                    <input placeholder="视频时长" name="video_duration" value="{{d.video_duration || ''}}"
                           class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">联系方式：</label>
                <div class="layui-input-inline">
                    <input placeholder="联系方式" name="contact" value="{{d.contact}}"
                           class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">视频地址：</label>
            <div class="layui-input-block" style="width: 514px">
                <input placeholder="视频地址" name="video_url" value="{{d.video_url || '' }}"
                       class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">排序：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="排序" name="sort" value="{{d.sort||0}}"
                           class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">定位城市：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="定位城市"  name="cityname" value="{{=d.cityname }}"
                           class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">价格：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="价格" name="price" value="{{d.price||0}}"
                           class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户AFF：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.aff }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">内容：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.content }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户删除标识 0否 1是 ：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.is_deleted }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">点赞数量：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.like_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">评论数量：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.comment_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">置精 0否 1是：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.is_best }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">帖子类型 1图片 2视频 3图文：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.category }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">拒绝通过的原因：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.refuse_reason }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">图片数量：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.photo_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">视频数量：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.video_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">资源是否完成 0否1是：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.is_finished }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户ip：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.ipstr }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">定位城市：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.cityname }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">话题ID：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.topic_id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">浏览数量：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.view_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">刷新时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.refresh_at }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">标题：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.title }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">0:待审核 1:审核中 2.审核通过 3.未通过 4.被举报：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.status }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">创建时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.created_at }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">修改时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.updated_at }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">排序 越大越前：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.sort }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">收藏数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.favorite_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">打赏次数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.reward_num }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">set_top：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.set_top }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">_id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d._id }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>
<script type="text/html" id="a6">
    <div style="display: inline-block;flex-direction: row;align-items:center;">
        <img style="width: 50px;height:50px;" title="头像"
             alt="头像" src="{{d.user_thumb}}" onclick="show_img('{{d.user_thumb}}')">
        <hr/>
        <div>
            会员昵称：{{d.user_nickname}}<br>
            会员AFF：{{d.user_aff}}<br>
            会员等级：{{d.user_vip_level_str}}<br>
            会员到期：{{d.user_expired_at_str}}
        </div>
    </div>
</script>
<script type="text/html" id="a5">
    价格：{{d.price}}  <br>
    总数量：{{d.reward_num}}  <br>
    联系方式：{{d.contact}}
</script>
<script type="text/html" id="a4">
    ip：{{d.ipstr}}  <br>
    城市：{{d.cityname}}
</script>
<script type="text/html" id="a3">
    图片：{{d.photo_num}} &nbsp;|&nbsp;
    视频：{{d.video_num}} <br>
    点赞：{{d.like_num}} &nbsp;|&nbsp;
    评论：{{d.comment_num}} <br>
    浏览：{{d.view_num}} <br>
    收藏：{{d.favorite_num}}<br>
    创建:{{d.created_at}}<br>
    刷新:{{d.refresh_at}}
</script>
<script type="text/html" id="a2">
    <span style="color:blue">话题:{{d.topic_str}}</span>&nbsp;&nbsp;<span style="color: darkgreen">类型:{{d.category_str}}</span>
    <hr/>
    <h3 style="white-space: pre-wrap;">{{d.title}}</h3>
    <hr/>
    <h4 style="white-space: pre-wrap;">{{d.content}}</h4>
</script>
<script type="text/html" id="a1">
    <span style="color: green;font-weight: bold;">状态：{{d.status_str}}</span><br>
    <span style="color: blue;font-weight: bold;">资源状态：{{d.finish_str}}</span><br>
    置顶：{{d.set_top_str}}<br>
    置精：{{d.bast_str}}<br>
    删除：{{d.deleted_str}}<br>
    IP：{{d.ipstr}}  <br>
    城市：{{d.cityname}}
</script>

<script type="text/html" class="data-dialog" id="img-dialog" data-h="780" data-w="900"
        data-iframe="<?php echo url_backend('girlmedia/index') ?>&pid={{=d.id}}" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">

</script>

<script type="text/html" class="data-dialog" id="video-dialog" data-h="780" data-w="900"
        data-iframe="<?php echo url_backend('girlmedia/index') ?>&pid={{=d.id}}" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">

</script>
<script type="text/html" class="data-dialog" id="element-dialog" data-h="780" data-w="900"
        data-iframe="<?php echo url_backend('girlcomment/index') ?>&post_id={{=d.id}}" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">

</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax",['where[status]'=>GirlModel::STATUS_PASS]) ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id',sort:true,width:100}
            , {field: 'aff', title: '用户',templet:'#a6',width:200}
            , {field: 'content', title: '内容',templet:'#a2',width:400}
            , {field: 'category_str', title: '解锁',templet:'#a5',width:200}
            , {field: 'like_num', title: '属性',templet:'#a3',width:200}

            , {field: 'is_best', title: '状态',templet:'#a1',width:160}
            //, {field: 'category', title: '帖子类型 1图片 2视频 3图文'}
            //, {field: 'refuse_reason', title: '拒绝通过的原因'}
            //, {field: 'photo_num', title: '图片数量'}
            //, {field: 'video_num', title: '视频数量'}
            //, {field: 'is_finished', title: '资源是否完成 0否1是'}
            , {field: 'sort', title: '排序',sort:true,edit:true}
            , {field: 'set_top', title: '置顶',type:"switch",value: "1|0", edit: true, width: 120}
            , {field: 'is_best', title: '置精',type:"switch",value: "1|0", edit: true, width: 120}
            , {field: 'is_deleted', title: '隐藏',type:"switch",value: "1|0", edit: true, width: 120}
            //, {field: 'ipstr', title: 'ip',templet:'#a4', width: 220}
            //, {field: 'cityname', title: '时间',templet:'#time-attr'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event:{
            search: function (ajax, laytpl, where) {
                ajax.get("<?php echo url_backend('total')?>&" + xx.queryEncode(where)).then(function (json) {
                    if(json.code =='0'){
                        let data = json.data,$ = layui.$;
                        $('#total-id').html(laytpl($('#search-total').html()).render(data));
                    }
                });
            },
            'toolbar': {
                add: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                },
            },
            operate:{
                refresh: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('确定要刷新吗?', function (index2) {
                        ajax.post("<?php echo url_backend('refresh')?>", {"id": $this.data('id')})
                            .then(function (json) {
                                Util.msgOk(json.msg);return;
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg,function () {
                                        obj.del();
                                    });
                                }
                            })
                    });
                },
            }
        }
    });

    layui.use(['form', 'jquery', 'laytpl'], function () {
        let form = layui.form;
        let $ = layui.jquery;
        let laytpl = layui.laytpl;
        let data = form.val('order-search');
        //console.log('order-search'+xx.queryEncode(data))
        $.ajax({
            url: "<?php echo url_backend('total')?>&" + xx.queryEncode(data),
            dataType: 'json',
            success: function (json) {
                //console.log(json.code)
                if (json.code == '0') {
                    let response = json.data;
                    $('#total-id').html(laytpl($('#search-total').html()).render(response));
                }
            }
        });
    })
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>