<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">uid</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <!--                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">-->
                            <!--                                添加-->
                            <!--                            </button>-->
                            <!--                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="uid">删除所选</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <div class="operate-toolbar">
                            <a lay-event="add_time" data-pk="{{=d.uid}}"> 加时间</a> |
                        </div>
                        <!--                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.uid}}" lay-event="del">-->
                        <!--                            <i class="layui-icon layui-icon-delete"></i>删除</a>-->
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'uid',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'uid', title: 'uid'}
            , {field: 'province', title: '用户省份'}
            , {field: 'hide_province', title: '隐藏位置'}
            , {field: 'age_range', title: '年龄'}
            , {field: 'tag', title: '标签'}
            , {field: 'expired_at', title: '过期时间'}
            , {field: 'hope_province', title: '希望对方的省份'}
            , {field: 'hope_age_range', title: '希望对方的省份'}
            , {field: 'created_at', title: '创建时间'}
            , {field: 'updated_at', title: '修改时间'}
            // , {field: 'match_status', title: '是否进行匹配'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        'event': {
            'operate': {
                "clearCached": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var index = layer.prompt({"title": "加时间，小时", formType: 1}, function (val) {
                        if (val.length <= 0) {
                            Util.msgErr("时间错误");
                            return;
                        }
                        ajax.post("<?php echo url_backend('add_time')?>", {"val": val, "uid": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, Util.reload);
                                }
                            })
                    });
                },
            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>