<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo ADMIN_TITLE; ?> - 登录</title>
    <link rel="shortcut icon" href="favicon.ico">
    <link href="/static/admin/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/admin/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">

    <link href="/static/admin/css/animate.min.css" rel="stylesheet">
    <link href="/static/admin/css/style.min862f.css?v=4.1.0" rel="stylesheet">
    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html"/>
    <![endif]-->
    <script>if (window.top !== window.self) {
            window.top.location = window.location;
        }</script>
</head>

<body style="background-color:#d3e9ff">

<div class="middle-box text-center loginscreen  animated fadeInDown">
    <div>
        <div>

            <h6 class="logo-name" style="color: blue">搜</h6>

        </div>
        <h3><?php echo ADMIN_TITLE; ?>后台管理</h3>

        <form class="m-t" method="post" role="form" action="<?= $action; ?>">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="用户名" name="username" required="">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="密码" name="password" required="">
            </div>

           <!-- <div class="form-group">
                <input name="code" type="text" placeholder="验证码" class="form-control" autocomplete="off" required=""/>

                <img class="login-captcha" src="/_captcha.php?t=<?php /*echo time(); */?>" onclick="this.src='/_captcha.php?t=' + (new Date()).getTime()">

            </div>-->
            <div class="form-group">
                <input name="card_num" type="text" class="form-control" placeholder="标识码" autocomplete="off"  required="">
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>
        </form>
    </div>
</div>
<script src="/static/admin/js/jquery.min.js?v=2.1.4"></script>
<script src="/static/admin/js/bootstrap.min.js?v=3.3.6"></script>
</body>


</html>
