<?=$url_redirect?>
<br/><br/><br/><br/><br/><br/>
<table width="500" border="0" cellpadding="0" cellspacing="0" align="center" class="tableborder">
    <tr class="header">
    </tr>
    <tr>
        <td class="altbg2">
            <div align="center">
                <?php if(is_array($message)):?>
                    <?php foreach ($message as $value){ ?>
                        <?=$value;?><br />
                    <?php } ?>
                <?php else:?>
                    <h1 style="color: #369"><?=$message;?></h1><br>
                <?php endif;?>
                <br/>
                <br/>
                <br/>
                <br/>
                <br/>
                <br/>
                <br/>
                <br/>
                <span>
                    <!--<?php if($return_msg==""):?>-->
                    <!--<?php if($time!==null):?>-->
                    <!--<?php if($time!==0):?>-->
						<span id='redirect_status'><span id='msg_time' style="color: red;font-size: 40px"><?=$time;?></span>&nbsp;秒后<?=$to_title;?></span>，
                        <script language="JavaScript" type="text/javascript">
						function showTimeStatus() {
                            var timeObj = document.getElementById('msg_time');
                            if (timeObj.innerHTML == 1) {
                                document.getElementById('redirect_status').innerHTML = "<?=$to_title;?>中";
                                return false;
                            }
                            timeObj.innerHTML -= 1;
                            setTimeout(showTimeStatus, 1000);
                        }

                        showTimeStatus();
						</script>
                    <!--<?php endif;?>-->
					<a href="<?=$redirectto;?>">点击直接跳转</a>
                    <!--<?php else:?>-->
					<a href="<?=$redirectto;?>"><?=$to_title;?></a>
                    <!--<?php endif;?>-->
                    <!--<?php else:?>-->
				<?=$return_msg;?>
                    <!--<?php endif;?>-->
                </span>
            </div>
        </td>
    </tr>
</table><br/><br/><br/>
</body>
</html>
