<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header"><span style="color: orangered;font-weight: bold">X-Lan xx 后台管理中心</span>
                </div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">用户ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[touid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">管理员</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[admin]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">type</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[type]', ChargeAdminModel::TYPE) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>

                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <!-- <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                             <i class="layui-icon layui-icon-edit"></i>修改</a>
                         <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                             <i class="layui-icon layui-icon-delete"></i>删除</a>-->
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900"  data-h="600" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: red">管理员&补充操作</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">type：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('type', ChargeAdminModel::TYPE,
                    ['lay-verify' => 'required', 'data-value' => '{{=d.type }}']) ?>

            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">用户：</label>
            <div class="layui-input-inline">

                <input lay-verify="required" placeholder="充值对象ID" name="touid"
                       value="{{=d.touid }}" class="layui-input">

            </div>

            <label class="layui-form-label">数值<a style="color: red" title="根据类型不同而不同，都为整数">?</a>：</label>
            <div class="layui-input-inline">

                <input lay-verify="required" placeholder="数值" name="coin"
                       value="{{=d.coin }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">描述：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="des" name="des"
                       value="{{=d.des }}" class="layui-input">

            </div>

        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: undefined,
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id', width: 100}
            , {field: 'touid', title: '用户', width: 160}
            , {
                field: 'coin', title: '数值', templet: function (d) {
                    return "<span style='color: red;font-weight: bold'>" + d.coin + "</span>"
                }, width: 140
            }
            , {
                field: 'type',
                title: 'type',
                type: 'enum',
                value:<?php echo json_encode(ChargeAdminModel::TYPE) ?>,
                width: 140
            }
            , {field: 'addtime_str', title: '时间', width: 160}
            , {
                field: 'admin', title: '管理', templet: function (d) {
                    return "<span style='color: lightskyblue;font-weight: bold'>" + d.admin + "</span>"
                }, width: 160
            }
            , {field: 'ip', title: 'IP', width: 120}
            , {field: 'des', title: 'des'}
            //, {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>