<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">uid</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">action</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[action]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">day</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[day]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">

                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">uid：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="uid" name="uid"
                           value="{{=d.uid }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">action：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="action" name="action"
                           value="{{=d.action }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">day：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="day" name="day"
                           value="{{=d.day }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">value：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="value" name="value"
                           value="{{=d.value }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">note：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="note" name="note"
                           value="{{=d.note }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">description：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="description" name="description"
                           value="{{=d.description }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">id：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.id }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">note：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.note }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">description：</label>
            <div class="layui-input-block">
                    <pre style="color: #F74C31">
                        {{=d.description_str }}
                    </pre>
            </div>
        </div>
    </form>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id', sort: true, width: 80}
            , {field: 'uid', title: 'uid', width: 100}
            , {field: 'action', title: 'action', width: 80}
            , {field: 'day', title: 'day', sort: true, width: 120}
            , {field: 'value', title: 'value', width: 100}
            , {field: 'status_text', title: 'value', width: 100}
            , {
                field: 'note', title: '备注', templet: function (d) {
                    return "<span style='color:grey;font-weight: bold'>" + d.note + "</span>"
                }
            }, {
                field: 'description_note', title: '转账', templet: function (d) {
                    return "<span style='color:red;font-weight: bold'>" + d.description_note + "</span>"
                }
            }
            //, {field: 'description', title: 'description'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>