<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[status]', PcTabModel::STATUS) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">导航标签</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[tab_name]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                        <span style="font-weight: bold;color: orangered">备注：前端按照升序排序方式展示（App导航）</span>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">

                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.tab_id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900"  data-h="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend><span style="color: #029789">导航更新|展示-信息</span></legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">

            <label class="layui-form-label">导航名：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="导航名" name="tab_name"
                       value="{{=d.tab_name }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('status', PcTabModel::STATUS, ['data-value' => '{{=d.status}}']) ?>
            </div>

        </div>

        <div class="layui-form-item">

            <label class="layui-form-label">排序：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="排序" name="sort_num"
                       value="{{=d.sort_num }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">标签编排：</label>
            <div class="layui-input-block">
                <!-- <input placeholder="标签编排" name="tags_str"
                        value="{{=d.tags_str }}" class="layui-input">-->
                <div id="adminrole_div" class="xtree_contianer" style="margin-bottom: 10px"></div>

            </div>

        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">简介</label>
            <div class="layui-input-block">
                <textarea name="intro" rows="10" cols="100" style="width: 500px" >{{=d.intro }}</textarea>
            </div>
        </div>


        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.tab_id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<style>
    .layui-table-cell {
        height: 50px;
        line-height: 50px
    }


    .layui-xtree-item {
        display: inline-block;
        width: 80px;
    }
</style>
<script src="<?php echo LAY_UI_STATIC ?>layuiadmin/layui-xtree.js?t=<?php echo time(); ?>"></script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'tab_id',
        cols: [[
            {field: 'tab_id', title: '编号', width: 100}
            , {field: 'tab_name', title: '导航'}
            , {field: 'tags_str', title: '标签编组'}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true}
            // , {field: 'is_tab', title: '导航', type: "switch", "value": "1|0", edit: true}
            // , {field: 'is_aw', title: '暗网', type: "switch", "value": "1|0", edit: true}
            // , {field: 'is_search', title: '搜索', type: "switch", "value": "1|0", edit: true}
            // , {field: 'is_category', title: '分类', type: "switch", "value": "1|0", edit: true}
            , {field: 'sort_num', title: '排序', sort: true}
            //, {field: 'updated_str', title: '更新'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "done": function (table, data, from, ajax, tpl, $) {
            ajax.get("<?php echo url_backend('mv/tagsList')?>")
                .then(function (json) {
                    return json.data;
                })
                .then(function (data) {
                    xx.use({"menu": data})
                })
        },
        event: {
            'toolbar':{
                addUser: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                }
            },
            "operate": {
                edit: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                }
            },
            "renderTree": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                console.log(obj.data);
                let ruleArray = [] , menudata = xx.config('menu'), treeJson = [];
                if (typeof(obj.data) !=="undefined"){
                    ruleArray = obj.data.tags_ary
                }
                $.each(menudata, function (i, item, data) {
                    data = {
                        "inputname": 'tags_str[]',
                        "title": item,
                        "value": item,
                        "checked": in_array(item, ruleArray),
                        "data": [],
                    };
                    treeJson.push(data);
                });
                nextFn();
                Util.renderSelect(obj.data , $,form);
                new layuiXtree({
                    elem: 'adminrole_div'
                    , form: form
                    , data: treeJson
                });
            },
        }

    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>