<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理<span
                            style="color:palevioletred;font-weight: bold">排序按降序排列</span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">动漫ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[pid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">金币(大于)</label>
                            <div class="layui-input-block">
                                <input type="text" name="between[coins][from]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]',
                                    merge_array(['' => '全选'], CartoonChaptersModel::STATUS_TIPS)) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[type]',
                                    merge_array(['' => '全选'], CartoonChaptersModel::TYPE_TIPS)) ?>

                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">付费类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_free]',
                                    merge_array(['' => '全选'], CartoonChaptersModel::FREE_TIPS)) ?>

                            </div>
                        </div>


                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <!--  <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>-->
                            <button class="layui-btn layui-btn-sm" lay-event="batchSetCoins" data-pk="id"
                                    lay-form="batch-set-coins">
                                付费设置
                            </button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <!--  <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>-->
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <label class="layui-form-label">动漫id：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="动漫id" name="title" value="{{=d.pid }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">资源：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="演员" name="source" value="{{=d.source }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">封面：</label>
            <?php echo Layui::uploadPos('cover_full', 'cover', 40, 40) ?>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">宽度：</label>
            <div class="layui-input-inline">
                <input  placeholder="宽度" name="width" value="{{=d.width }}" class="layui-input">
            </div>
            <label class="layui-form-label">高度：</label>
            <div class="layui-input-inline">
                <input  placeholder="高度" name="height" value="{{=d.height }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">类型：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('type', CartoonChaptersModel::TYPE_TIPS, ['data-value' => '{{=d.type}}']) ?>
            </div>
            <label class="layui-form-label">付费类型：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('is_free', CartoonChaptersModel::FREE_TIPS, ['data-value' => '{{=d.is_free}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">价格：</label>
            <div class="layui-input-inline">
                <input  placeholder="价格" name="coins" value="{{=d.coins }}" class="layui-input">
            </div>
            <label class="layui-form-label">排序：</label>
            <div class="layui-input-inline">
                <input  placeholder="排序" name="sort" value="{{=d.sort }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">时长：</label>
            <div class="layui-input-inline">
                <input  placeholder="时长" name="duration" value="{{=d.duration }}" class="layui-input">
            </div>
            <label class="layui-form-label">状态：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('status', CartoonChaptersModel::STATUS_TIPS, ['data-value' => '{{=d.status}}']) ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script type="text/html" class="data-dialog" id="batch-set-coins" data-h="500" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'付费类型设置',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">付费类型设置</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">付费类型</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('is_free', CartoonChaptersModel::FREE_TIPS) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">金币</label>
            <div class="layui-input-inline">
                <input name="coins" value="" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchCoinsSave"></button>
        </div>
    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            ,{field: 'id', title: 'id', sort: true, width: 90}
            ,{field: 'pid', title: '动漫信息',width: 120,templet:"#original_info"}
            ,{field: 'media_url', title: '视频地址',templet:function (d){
                    if (d.source) {
                        let html = "<a class='layui-btn layui-btn-sm layui-btn-xs' target='_blank' href='"
                            + d.source_url + "'><i class='layui-icon layui-icon-play'></i>播放</a>"
                        return html
                    }
                    return '';

                }}
            , {title: '属性', templet:"#info-list",width: 120}
            , {
                field: 'cover', width: 120, title: '图片', align: 'center', templet: function (d) {
                    if (d.cover_full) {
                        return '<div onclick="show_img(\'' + d.cover_full + '\')" ><img width="50" src="' + d.cover_full + '" /></div>';
                    }
                    return '';
                }
            }
            ,{field: 'is_free_str', title: '类型', width: 70}
            ,{field: 'coins', title: '金币', width: 70}
            // , {field: 'like_count', title: '点赞数', sort: true, edit: true, width: 70}
            // , {field: 'play_count', title: '播放数', sort: true, edit: true, width: 70}
            // , {field: 'com_count', title: '评论数', sort: true, edit: true, width: 70}
            , {field: 'pay_count', title: '购买数', sort: true, width: 70}
            , {field: 'status', title: '状态', type: "switch", value: "1|0", edit: true, width: 120}
            , {field: 'created_at', title: '创建时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event: {
            'toolbar': {
                addUser: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                },
                batchSetCoins: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');

                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        form.val("form-save", {
                            "ids": pkValAry.join(',')
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchCoins')?>", form, ajax, 'addBatchCoinsSave', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
            },
            //event.operate->refuse
            "operate": {
            }
        }
    });
</script>
<script type="text/html" id="info-list">
    时长:{{ d.duration}}<br/>
    宽度:{{ d.width}}<br/>
    高度:{{ d.height}}<br/>

</script>
<script type="text/html" id="original_info">
    类型:{{ d.type_str}}<br/>
    动漫:{{ d.pid}}<br/>
    剧集:{{ d.sort_str}}<br/>
    标题:{{ d.title}}<br/>
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>