<?php


use Illuminate\Database\Eloquent\Model;

/**
 * class ProductUserModel
 *
 * @property int $id
 * @property int $aff
 * @property int $product_id
 * @property int $vip_level
 * @property int $type
 * @property int $status
 * @property string $created_at
 * @property string $expired_date
 * @property ProductModel $product
 *
 *
 * @date 2022-03-30 16:44:25
 *
 * @mixin \Eloquent
 */
class ProductUserModel extends Model
{

    protected $table = "product_user";

    protected $primaryKey = 'id';

    protected $fillable = [
        'aff',
        'product_id',
        'vip_level',
        'type',
        'created_at',
        'status',
        'expired_date'
    ];

    protected $guarded = 'id';

    public $timestamps = false;

    const TYPE_CARD = 1;
    const TYPE_ACT = 2;
    const TYPE = [
        self::TYPE_CARD => '卡',
        self::TYPE_ACT => '活动'
    ];
    const STATUS_NO = 0;
    const STATUS_YES = 1;

    const STATUS = [
        self::STATUS_NO => '无效',
        self::STATUS_YES => '有效'
    ];

    const USER_PRODUCT_AFF = "user:product:aff:%s";

    static function addDateTime($dateTime, $addDay)
    {
        $nowDate = date("Y-m-d");
        $expDate = ($dateTime > $nowDate) ? $dateTime : $nowDate;
        return date("Y-m-d H:i:s", strtotime("+{$addDay} days", strtotime($expDate)));
    }

    static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        self::saved(function (ProductUserModel $productUserModel) {
            // 更新
            redis()->del(UsersProductPrivilegeModel::REDIS_KEY_USER_PRIVILEGE . $productUserModel->aff);
        });
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function product()
    {
        return $this->hasOne(ProductModel::class, 'id', 'product_id');
    }

    /**
     * 我的购买激活产品
     * @param $aff
     * @return \Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    static function getMemberProduct($aff)
    {
        return self::where([
            'aff' => $aff,
            'status' => self::STATUS_YES
        ])->get();
    }

    /**
     * 用户是否已经购买卡片 判断及更新
     * @param MemberModel $user
     * @param ProductModel $product
     */
    static function buyVIPProduct(MemberModel $user, ProductModel $product)
    {
        //用户是否已经购买卡片 判断及更新
        /** @var ProductUserModel $userProduct */
        $userProduct = self::where([
            'aff' => $user->aff,
            'product_id' => $product->id
        ])->first();
        if (is_null($userProduct)) {
            $userProduct = self::create([
                'aff' => $user->aff,
                'product_id'    => $product->id,
                'vip_level'     => $product->vip_level,
                'type'          => 1,
                'status'        => self::STATUS_YES,
                'created_at'    => date("Y-m-d H:i:s"),
                'expired_date'  => date("Y-m-d H:i:s", strtotime("+{$product->valid_date} days")),
            ]);
        } else {
            $userProduct->status = self::STATUS_YES;
            $userProduct->expired_date = self::addDateTime($userProduct->expired_date, $product->valid_date);
            $userProduct->save();
        }
        //查看用户购买商品的所有权益 新增或更新
        //echo "buy{$product->id}";
        self::buyVIPProductPrivilege($user, $product);
    }

    /**
     * 查看商品的所有权益 新增或更新
     * @param MemberModel $user
     * @param ProductModel $product
     */
    static function buyVIPProductPrivilege(MemberModel $user, ProductModel $product)
    {
        //查看商品的所有权益 新增或更新
        ProductPrivilegeModel::where('product_id', $product->id)
            ->get()
            ->map(function (ProductPrivilegeModel $productPrivilege) use ($user, $product) {
                //权限被删除
                if (empty($productPrivilege->privilege)){
                    return;
                }

                /** @var UsersProductPrivilegeModel $userPrivilege */
                $userPrivilege = UsersProductPrivilegeModel::where([
                    'aff' => $user->aff,
                    'product_id' => $product->id,
                    'privilege_id' => $productPrivilege->id
                ])->first();
                if (is_null($userPrivilege)) {
                    UsersProductPrivilegeModel::create([
                        'aff' => $user->aff,
                        'product_id' => $product->id,
                        'privilege_id' => $productPrivilege->id,
                        'resource_type' => $productPrivilege->privilege->resource_type,
                        'privilege_type' => $productPrivilege->privilege->privilege_type,
                        'value' => $productPrivilege->privilege->value,
                        'day_value' => $productPrivilege->privilege->day_value,
                        'status' => UsersProductPrivilegeModel::STATUS_YES,
                        'expired_date' => date("Y-m-d H:i:s", strtotime("+{$product->valid_date} days")),
                        'created_at' => date("Y-m-d H:i:s"),
                    ]);
                } else {
                    if ($userPrivilege->privilege_type == PrivilegeModel::PRIVILEGE_TYPE_UNLOCK) {//解锁次数累计
                        $userPrivilege->value += $productPrivilege->privilege->value;
                    } else {
                        $userPrivilege->value = $productPrivilege->privilege->value;
                    }
                    $userPrivilege->status = UsersProductPrivilegeModel::STATUS_YES;
                    $userPrivilege->expired_date = self::addDateTime($userPrivilege->expired_date, $product->valid_date);
                    $userPrivilege->save();
                }

            });

        //清理缓存
        UsersProductPrivilegeModel::clearCache($user->aff);
    }

    public static function getUserProduct($aff)
    {
        $key = sprintf(self::USER_PRODUCT_AFF, $aff);
        return cached($key)
            ->fetchPhp(function () use ($aff) {
                return self::query()
                    ->with(['product'])
                    ->where('aff', $aff)
                    //->where('status',self::STATUS_YES)
                    ->orderByDesc('id')
                    ->first();
            });
    }

}
