<?php


use Carbon\Carbon;

/**
 * class UsersProductPrivilegeModel
 *
 * @property int $id
 * @property int $aff
 * @property int $product_id
 * @property int $privilege_id
 * @property int $resource_type
 * @property int $privilege_type
 * @property int $value
 * @property int $day_value
 * @property int $status
 * @property string $expired_date
 * @property string $created_at
 * @property ProductModel $product
 * @property PrivilegeModel $privilege
 *
 *
 * @date 2022-04-08 21:28:12
 *
 * @mixin \Eloquent
 */
class UsersProductPrivilegeModel extends EloquentModel
{

    protected $table = "users_product_privilege";

    protected $primaryKey = 'id';

    protected $fillable = [
        'aff',
        'product_id',
        'privilege_id',
        'resource_type',
        'privilege_type',
        'value',
        'day_value',
        'status',
        'expired_date',
        'created_at'
    ];

    protected $guarded = 'id';

    public $timestamps = false;


    CONST STATUS_NO = 0;
    CONST STATUS_YES = 1;

    CONST STATUS = [
        self::STATUS_NO  => '无效',
        self::STATUS_YES => '有效'
    ];
    CONST REDIS_KEY_USER_PRIVILEGE = 'user:privilege:';

    const REDIS_KEY_DAY_USER_PRIVILEGE = 'user:privilege:%s:%s:%s';

    CONST USER_DEFINE_PRIVILEGE = 0;

    /*static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        self::saved(function (UsersProductPrivilegeModel $userPrivilege) {
            // 更新
            redis()->del(UsersProductPrivilegeModel::REDIS_KEY_USER_PRIVILEGE . $userPrivilege->aff);
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function product()
    {
        return $this->hasOne(ProductModel::class, 'id', 'product_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function privilege()
    {
        return $this->hasOne(PrivilegeModel::class, 'id', 'privilege_id');
    }

    /**
     * @param MemberModel $member
     * @return array<ProductUserModel>|Collection
     */
    static function getUserPrivilege(MemberModel $member)
    {
        $userPrivilege = self::initPrivilege();
        /** @var array<ProductUserModel> $userProducts */
        $userProducts = ProductUserModel::where('status',ProductUserModel::STATUS_YES)
            ->where('aff', $member->aff)
            ->orderByDesc('id')
            ->get();
        if ($userProducts) {
            foreach ($userProducts as $userProduct) {
                if (Carbon::parse($userProduct->expired_date)->lt(Carbon::now())) {
                    $userProduct->status = ProductUserModel::STATUS_NO;
                    $userProduct->save();
                    ProductUserModel::where([
                        'aff' => $member->aff,
                        'product_id' => $userProduct->product_id
                    ])->update(['status' => ProductUserModel::STATUS_NO]);
                    continue;
                }
                /** @var array<UsersProductPrivilegeModel> $privileges */
                $privileges = UsersProductPrivilegeModel::where('status',UsersProductPrivilegeModel::STATUS_YES)
                    ->where('aff',$member->aff)
                    ->where('product_id',$userProduct->product_id)
                    ->get();
                foreach ($privileges as $privilege) {
                    list($resource_type, $privilege_type) = [$privilege->resource_type, $privilege->privilege_type];
                    if ($userPrivilege[$resource_type][$privilege_type]['status'] == 0) {
                        $userPrivilege[$resource_type][$privilege_type]['status'] = 1;
                        //免费解锁 和 下载
                        if ($privilege->day_value > 0 && in_array($privilege->privilege_type, PrivilegeModel::PRIVILEGE_DAY_TYPE)){
                            $userPrivilege[$resource_type][$privilege_type]['value'] = self::hasDayValue($member->aff, $privilege->id, $privilege->value, $privilege->day_value);
                        }else{
                            //使用总次数的
                            $userPrivilege[$resource_type][$privilege_type]['value'] = $privilege->value;
                        }
                    } elseif ($privilege_type == PrivilegeModel::PRIVILEGE_TYPE_DISCOUNT) {
                        if ($userPrivilege[$resource_type][$privilege_type]['value'] > $privilege->value) {
                            $userPrivilege[$resource_type][$privilege_type]['value'] = $privilege->value;
                        }
                    } elseif ($userPrivilege[$resource_type][$privilege_type]['value'] < $privilege->value) {
                        $userPrivilege[$resource_type][$privilege_type]['value'] += $privilege->value;
                    }
                    $userPrivilege[$resource_type][$privilege_type]['_id'] = $privilege->id;
                }
            }
        } else {
            if ($member->vip_level != 0) {
                $member->vip_level = 0;
                if($member->expired_at > TIMESTAMP){
                    $member->expired_at = TIMESTAMP;
                }
                $member->save();
            }
        }

        return $userPrivilege;
    }

    public static function hasDayValue($aff, $privilege_id, $value, $day_value){
        $day_key = sprintf(self::REDIS_KEY_DAY_USER_PRIVILEGE, date('Y-m-d'), $aff, $privilege_id);
        $day_has_use = redis()->get($day_key);
        $day_has_use = intval($day_has_use);
        if ($value > 0){
            if ($day_has_use >= $day_value){
                return 0;
            }else{
                if ($value >= $day_value){
                    return $day_value - $day_has_use;
                }else{
                    return $value - $day_value;
                }
            }
        }else{
            if ($day_has_use >= $day_value){
                return 0;
            }else{
                return $day_value - $day_has_use;
            }
        }
    }

    /**
     * 初始化 权限赋值
     * @return array
     */
    public static function initPrivilege()
    {
        $userPrivilege = [];
        foreach (PrivilegeModel::RESOURCE_TYPE_NUM as $resource) {
            foreach (PrivilegeModel::PRIVILEGE_TYPE_NUM as $privilege) {
                $userPrivilege[$resource][$privilege] = ['value' => 0, 'status' => 0, '_id' => 0];
            }
        }
        //上门
        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL_AGENT][PrivilegeModel::PRIVILEGE_TYPE_VIEW]['status'] = 1;
        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL_AGENT][PrivilegeModel::PRIVILEGE_TYPE_VIEW]['value'] = 9999;

        //观看
        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL][PrivilegeModel::PRIVILEGE_TYPE_VIEW]['status'] = 1;
        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL][PrivilegeModel::PRIVILEGE_TYPE_VIEW]['value'] = 9999;

        //裸聊
        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL_CHAT][PrivilegeModel::PRIVILEGE_TYPE_VIEW]['status'] = 1;
        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL_CHAT][PrivilegeModel::PRIVILEGE_TYPE_VIEW]['value'] = 9999;

        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_SYSTEM][PrivilegeModel::PRIVILEGE_TYPE_FEED]['status'] = 1;
        //$userPrivilege[PrivilegeModel::RESOURCE_TYPE_SYSTEM][PrivilegeModel::PRIVILEGE_TYPE_FEED]['value'] = 9999;

//        $userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL][PrivilegeModel::PRIVILEGE_TYPE_VIEW] = ['status' => 1, 'value' => 9999, '_id' => 0];
//        $userPrivilege[PrivilegeModel::RESOURCE_TYPE_GIRL_CHAT][PrivilegeModel::PRIVILEGE_TYPE_VIEW] = ['status' => 1, 'value' => 9999, '_id' => 0];
        $userPrivilege[PrivilegeModel::RESOURCE_TYPE_SYSTEM][PrivilegeModel::PRIVILEGE_TYPE_FEED] = ['status' => 1, 'value' => 9999, '_id' => 0];

        return $userPrivilege;
    }

    public static function hasPrivilege($userPrivilege, $resource, $privilege)
    {
        if ($userPrivilege[$resource][$privilege]['status'] == 1) {
            return $userPrivilege[$resource][$privilege]['value'];
        }
        return false;
    }

    public static function hasPrivilegeAndSubTimePrivilege($userPrivilege, $resource, $privilege, $aff)
    {
        $value = self::hasPrivilege($userPrivilege, $resource, $privilege);
        if ($value !== false) {
            if ($value >= 9999) {
                return true;
            }
            if ($value > 0) {
                $userPrivilege[$resource][$privilege]['value'] -= 1;
                /** @var UsersProductPrivilegeModel $user */
                $user = UsersProductPrivilegeModel::where('aff', $aff)
                    ->where('resource_type', $resource)
                    ->where('privilege_type', $privilege)
                    ->where('status', UsersProductPrivilegeModel::STATUS_YES)
                    ->where('value', '>', 0)
                    ->first();
                if ($user) {
                    if (in_array($user->privilege_type,PrivilegeModel::PRIVILEGE_DAY_TYPE) && $user->day_value > 0){
                        //每日次数加一
                        $day_key = sprintf(self::REDIS_KEY_DAY_USER_PRIVILEGE, date('Y-m-d'), $aff, $user->id);
                        redis()->incr($day_key);
                    }
                    $user->value = $user->value - 1;
                    $user->save();
                    cached(UsersProductPrivilegeModel::REDIS_KEY_USER_PRIVILEGE . $aff)->clearCached();
                    return true;
                } else {
                    return false;
                }
            }
            return false;
        }
        return false;
    }

    /**
     * 清空所有用户缓存
     * @param $uid
     * @return void
     */
    public static function clearCache($aff)
    {
         cached(UsersProductPrivilegeModel::REDIS_KEY_USER_PRIVILEGE.$aff)->clearCached();
         cached(sprintf(ProductUserModel::USER_PRODUCT_AFF, $aff))->clearCached();
         cached('user:vip:upgrade:' . $aff)->clearCached();
//        if (!$uid) {
//            return 0;
//        }
//        $userPrivilegeKeys = collect(PrivilegeModel::RESOURCE_TYPE)->map(function ($resource_type) use ($uid) {
//            foreach (PrivilegeModel::PRIVILEGE_TYPE as $privilege_type) {
//                return "u:privilege:{$uid}:{$resource_type}:{$privilege_type}";
//            }
//        })->toArray();
//        return redis()->del($userPrivilegeKeys);
    }

    /**
     * 折扣
     * @return int
     */
    public static function getUserDiscount($resource_type)
    {
        $zheKou = 100;//默认不打折
        $hasPrivilege = UsersProductPrivilegeModel::hasPrivilege(USER_PRIVILEGE, $resource_type, PrivilegeModel::PRIVILEGE_TYPE_DISCOUNT);
        if(!$hasPrivilege){
            return $zheKou;
        }
        if(is_integer($hasPrivilege)){
            return min($hasPrivilege,$zheKou);
        }
        return $zheKou;

    }

    public static function hasAwMvPerm(){
        $vip_perm = self::hasPrivilege(USER_PRIVILEGE,PrivilegeModel::RESOURCE_TYPE_AW_VIP_VIDEO,PrivilegeModel::PRIVILEGE_TYPE_VIEW);
        $coins_perm = self::hasPrivilege(USER_PRIVILEGE,PrivilegeModel::RESOURCE_TYPE_AW_COINS_VIDEO,PrivilegeModel::PRIVILEGE_TYPE_VIEW);
        if ($vip_perm || $coins_perm){
            return 1;
        }
        return 0;
    }
}
