<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="shortcut icon" href="favicon.ico"> <link href="/static/admin/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="/static/admin/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="/static/admin/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="/static/admin/css/animate.min.css" rel="stylesheet">
    <link href="/static/admin/css/style.min862f.css?v=4.1.0" rel="stylesheet">
    <link href="/static/admin/css/admin.css" rel="stylesheet">
    <script src="/static/admin/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/admin/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="/static/admin/js/plugins/peity/jquery.peity.min.js"></script>
    <script src="/static/admin/js/plugins/iCheck/icheck.min.js"></script>
    <script src="/static/admin/js/plugins/layui.all.js"></script>
    <style>
        body .demo-class .layui-layer-title{background:#029789; color:#fff; border: none;}
    </style>
</head>
<body>
    <div class="wrapper wrapper-content animated fadeInRight">
        <script>

            // 点击图片放大
            function show_img(url) {
                var img = new Image(),
                    layer = top.layer,
                    index = layer.load(2);
                img.src = url;
                img.onload = function () {
                    layer.close(index);
                    let width = img.width,
                        height = img.height,
                        bfb = 0.65,
                        availHeight = top.screen.availHeight * bfb,
                        availWidth = top.screen.availWidth * bfb;
                    while (width > availWidth || height > availHeight) {
                        width *= 0.95;
                        height *= 0.95;
                    }
                    layer.open({
                        type: 1,
                        title: '浏览图片',
                        //skin: 'layui-layer-rim', //加上边框
                        shadeClose:true,
                        area: [width + 'px', height + 'px'], //宽高
                        end: function (index, layero) {
                            return false;
                        },
                        content: '<img src="' + url + '" style="width: 100%;height: 100%" />'
                    });
                };
                img.onerror = function () {
                    layer.msg('图片加载失败', {time: 1000});
                    layer.close(index);
                }
            }


            function previewVideo(url) {
                if (url.indexOf('m3u8') !== -1) {
                    //弹出层
                    var base = "d.php?mod=index&code=preview&url=" + url;

                    let index = layer.open({
                        type: 2,
                        icon: 2,
                        maxWidth: 600,
                        offset: ['100px', '8px'],
                        scrollbar: false,
                        skin: 'demo-class', //加上边框
                        title: ["M3U8视频预览", 'font-size:14px;'],
                        area: ['600px', '400px'], //宽高
                        shadeClose: true,
                        content: base,
                        success: function (layero, index) {
                            layer.iframeAuto(index)
                        }
                    });
                    return;
                }

                var html = '<div>';
                html += '<video  width="600px" height="400px"  controls="controls" autobuffer="autobuffer" autoplay="autoplay" loop="loop"  x-webkit-airplay="true" x5-video-player-fullscreen="true" preload="auto" playsinline="true" webkit-playsinline x5-video-player-typ="h5" >';
                html += '<source src="' + url + '" type="video/mp4" />';
                html += '<source src="' + url + '" type="application/x-mpegURL"  />';
                html += '<source src="' + url + '" type="video/ogg" />';
                html += '<source src="' + url + '" type="video/webm" />';
                html += '<object data="' + url + '" height="600px"  width="400px" />';
                html += '<embed  src="' + url + '" height="600px"  width="400px" />';
                html += '</video>';
                html += '</div>';
                //弹出层
                layer.open({
                    type: 1,
                    icon: 2,
                    maxWidth: 600,
                    //area: ['auto' , 'auto'], //宽高
                    skin: 'layui-layer-rim', //加上边框
                    title: ["MP4-视频预览", 'font-size:12px;'],
                    shadeClose: true,
                    content: html,
                    offset: ['100px', '8px'],
                    success: function (layero) {
                        //layer.setTop(layero); //重点2
                    }
                });
            }

        </script>

