<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">导航</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[tab_id]', merge_array(['' => '全部'], $pcTab), ["lay-search" => '']) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">视频ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[mv_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">导航：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('tab_id', $pcTab, ['data-value' => '{{=d.tab_id}}']) ?>
                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">视频ID：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="视频ID" name="mv_id"
                           value="{{=d.mv_id }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">排序：</label>
                <div class="layui-input-inline">

                    <input placeholder="排序" name="sort"
                           value="{{=d.sort }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">PC导航ID：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.tab_id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">视频ID：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.mv_id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">排序：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.sort }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">created_at：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.created_at }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">updated_at：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.updated_at }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>

<script type="text/html" id="cover-title">
    <div style="width: 150px">
        <div style="width: 150px" class="clearfix">
            <img style="float:left; display: block;background: #cccccc" src="{{d.cover_thumb_url}}" width="40px"  onclick="url_cover_show('{{=d.cover_thumb_url}}')"/>
            <p style="white-space: pre-wrap;float:left;margin-left: 5px;max-width: 100px">
                {{=d.title}}
            </p>
        </div>
        <hr>
        <p class="clearfix" style="white-space: pre-wrap"><span style="color: blue">ID：</span>{{d.mv_id}}</p>
        <p class="clearfix" style="white-space: pre-wrap"><span style="color: red">标签：</span>{{d.tagsname}}</p>
        <p class="clearfix" style="white-space: pre-wrap"><span style="color: blue">类型：</span>{{d.free_str}}</p>
    </div>
</script>

<script type="text/html" id="tab-title">
    <div style="width: 150px">
        <p class="clearfix" style="white-space: pre-wrap"><span style="color: blue">导航ID：</span>{{d.tab_id}}</p>
        <p class="clearfix" style="white-space: pre-wrap"><span style="color: red">导航标题：</span>{{d.tab_name}}</p>
    </div>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id'}
            , {field: 'title', title: '标题',templet:'#cover-title'}
            , {
                field: 'href', title: '播放源', templet: function (d) {
                    let html = "<a class='layui-btn layui-btn-sm layui-btn-xs' target='_blank' href='"
                        + d.full_href + "'><i class='layui-icon layui-icon-play'></i>浏览器</a>"
                    return html
                }
            }
            , {field: 'title', title: '标题',templet:'#tab-title'}
            , {field: 'sort', title: '排序', edit:true, sort:true}
            , {field: 'created_at', title: '创建时间'}
            , {field: 'updated_at', title: '更新时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>