<script type="text/html" id="member-basis" >
    <div class="table-member">
        <a href="{{d.member.avatar_url}}" target="_blank"><img src="{{d.member.avatar_url}}"/></a>
        <p>
            <span>{{d.member.nickname}}</span>
            <em>{{d.member.aff}}</em>
        </p>
    </div>
</script>
<style type="text/css">
    .table-member span i{
        color: red;font-size: 10px;font-weight: bold;float:right;
    }
    .table-member span u{
        color: red;font-size: 10px;font-weight: bold;
    }
    .layui-table-cell , .operate-toolbar{
        font-size: 12px;
        height: auto;
        line-height: revert;
    }
    .operate-toolbar a{
        color: #0e9aef;
        cursor: pointer;
    }

    .operate-toolbar a:hover{
        text-underline: #0e9aef;
        color: #0775b6;
    }

    .table-member img {width: 35px;height: 35px;float: left;border-radius: 20px;float: left}
    .table-member img,.table-member span,.table-member em{
        display:block;
        font-style: normal;
        padding: 0;
        margin: 0;
    }
</style>
</body>
</html>