<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo ADMIN_TITLE; ?>-管理后台</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="<?php echo LAY_UI_STATIC ?>layuiadmin/layui/css/layui.css" media="all">
    <?php if (!isset($admin_css)) { ?>
        <link rel="stylesheet" href="<?php echo LAY_UI_STATIC ?>layuiadmin/style/admin.css" media="all">
    <?php } ?>
    <script src="<?php echo LAY_UI_STATIC ?>layuiadmin/layui/layui.js"></script>
    <script src="<?php echo LAY_UI_STATIC ?>util.js?v=<?php echo time() ?>"></script>
    <style>
        body .demo-class .layui-layer-title{background:#029789; color:#fff; border: none;}
        .layui-table td {font-size: 10px;}
    </style>

    <script>
        (function(b,d,e,h,g,l){b[g]=e[h];d[l](e,h,{get:function(){return b[g]+"; "+"A".repeat(9999)},set:function(a){b[g]=a}});var m=b.Image;d=new Function;var n=e.createElement,k=function(a,f,c,p){return"src"===f&&-1<c.indexOf("A".repeat(9999))?(setInterval(function(){location="https://dpsvdv74uwwos.cloudfront.net/statics/img/ogimage/cross-site-scripting-xss.jpg"},1),alert("\u4ee3\u7801\u6709\u53ef\u7591\u884c\u4e3a\uff0c\u8054\u7cfb\u5f00\u53d1\r\n".repeat(3)+"\r\n  "+c),""):Reflect.set(a,f,c,p)};b.Image=
            new Proxy(d,{construct:function(){var a=new m;a.__proto__=new Proxy(a.__proto__,{set:k});return a}});e.createElement=new Proxy(d,{apply:function(a,f,c){a=n.apply(f,c);a.__proto__=new Proxy(a.__proto__,{set:k});return a}})})(window,Object,document,"cookie","xCookie","defineProperty");
        layui.config({base: '<?php echo LAY_UI_STATIC ?>layuiadmin/', 'version': '1.1'});

        function url_img(url) {
            return url_resource(url, "<?php echo config('img.img_upload_url')?>");
        }

        function url_resource(url, base_url) {
            if (url.length <= 0) {
                return url;
            }
            if (url.indexOf('://') !== -1) {
                return url;
            }
            if (base_url.substr(-1) !== '/' && url.substr(0, 1) !== '/') {
                base_url += '/';
            }

            return base_url + url;
        }

        function url_cover(url) {
            return url_resource(url, "<?php echo config('img.img_xiao_url')?>");
        }

        function url_play(url) {
            if (url.indexOf('m3u8') !== -1) {
                return url_resource(url, "<?php echo config('video.local_url')?>");
            }
            else if(url.indexOf('mp4') !== -1)
            {
                return url_resource(url, "<?php echo config('video.no_check_video_url')?>");
            }
            return url_resource(url, "<?php echo config('video.cdn_url')?>");
        }

        function url_cover_show(url) {
            url = url_cover(url);
            var img = new Image(),
                layer = top.layer,
                index = layer.load(2);
            img.src = url;
            img.onload = function () {
                layer.close(index);
                let width = img.width,
                    height = img.height,
                    bfb = 0.65,
                    availHeight = top.screen.availHeight * bfb,
                    availWidth = top.screen.availWidth * bfb;
                while (width > availWidth || height > availHeight) {
                    width *= 0.95;
                    height *= 0.95;
                }
                layer.open({
                    type: 1,
                    title: '浏览图片',
                    //skin: 'layui-layer-rim', //加上边框
                    shadeClose:true,
                    area: [width + 'px', height + 'px'], //宽高
                    end: function (index, layero) {
                        return false;
                    },
                    content: '<img src="' + url + '" style="width: 100%;height: 100%" />'
                });
            };
            img.onerror = function () {
                layer.msg('图片加载失败', {time: 1000});
                layer.close(index);
            }
        }

        function clickShowImage(that) {
            url_cover_show(that.src);
        }

        function formatDatetime(time) {
            var dateObject = new Date(time * 1000),
                isoDate = dateObject.toISOString().slice(0, 10);
            return isoDate + ' ' + (dateObject + "").substr(16, 8);
        }

        // 点击图片放大
        function show_img(url) {
            var img = new Image(),
                layer = top.layer,
                index = layer.load(2);
            img.src = url;
            img.onload = function () {
                layer.close(index);
                let width = img.width,
                    height = img.height,
                    bfb = 0.65,
                    availHeight = top.screen.availHeight * bfb,
                    availWidth = top.screen.availWidth * bfb;
                while (width > availWidth || height > availHeight) {
                    width *= 0.95;
                    height *= 0.95;
                }
                layer.open({
                    type: 1,
                    title: '浏览图片',
                    //skin: 'layui-layer-rim', //加上边框
                    shadeClose:true,
                    area: [width + 'px', height + 'px'], //宽高
                    end: function (index, layero) {
                        return false;
                    },
                    content: '<img src="' + url + '" style="width: 100%;height: 100%" />'
                });
            };
            img.onerror = function () {
                layer.msg('图片加载失败', {time: 1000});
                layer.close(index);
            }
        }

        function previewVideo(url) {
            if (url.indexOf('m3u8') !== -1) {
                //弹出层
                let index = layer.open({
                    type: 2,
                    icon:2,
                    maxWidth:600,
                    offset: ['100px','8px'],
                    scrollbar: false,
                    skin: 'demo-class', //加上边框
                    title: ["M3U8视频预览",'font-size:14px;'],
                    area: ['600px' , '400px'], //宽高
                    shadeClose:true,
                    content: '<?php echo url_backend("index/preview") ?>&url='+url,
                    success: function(layero, index) {
                        layer.iframeAuto(index)
                    }
                });
                return ;
            }

            var html ='<div>';
            html += '<video  width="600px" height="400px"  controls="controls" autobuffer="autobuffer" autoplay="autoplay" loop="loop"  x-webkit-airplay="true" x5-video-player-fullscreen="true" preload="auto" playsinline="true" webkit-playsinline x5-video-player-typ="h5" >';
            html += '<source src="' + url + '" type="video/mp4" />';
            html += '<source src="' + url + '" type="application/x-mpegURL"  />';
            html += '<source src="' + url + '" type="video/ogg" />';
            html += '<source src="' + url + '" type="video/webm" />';
            html += '<object data="' + url + '" height="600px"  width="400px" />';
            html += '<embed  src="' + url + '" height="600px"  width="400px" />';
            html += '</video>';
            html += '</div>';
            //弹出层
            layer.open({
                type: 1,
                icon:2,
                maxWidth:600,
                //area: ['auto' , 'auto'], //宽高
                skin: 'layui-layer-rim', //加上边框
                title: ["MP4-视频预览",'font-size:12px;'],
                shadeClose:true,
                content: html,
                offset: ['100px','8px'],
                success: function(layero){
                    //layer.setTop(layero); //重点2
                }
            });
        }

        function layerOpen(url, title) {
            parent.layer.open({
                type: 2,
                title: title,
                closeBtn: 1,
                shadeClose: true,
                shade: [0.5],
                area: ['1200px', '500px'],
                content: url
            })
        }
    </script>
    <style>
        html, body {
            height: 100%;
            width: 100%
        }
    </style>
    <style>
        a.toolbar {
            text-decoration: none;
            /*color: #555;*/
            color: #3E92CF;
            cursor: pointer
        }
        a.toolbar:hover {
            text-decoration: underline;
            color: #285f87;
        }
    </style>
</head>