<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[status]', ConstructModel::STATUS) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">展示名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="like[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">导航</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[nag_id]', merge_array(['' => '全部'], $nagArr),["lay-search" => '']) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[type]', ConstructModel::TYPE_TIPS) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                        <span style="font-weight: bold;color: orangered">备注：前端按照降序排序方式展示（App导航）</span>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="worksUpdate" data-pk="id">作品数更新</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">

                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900"  data-h="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend><span style="color: #029789">导航更新|展示-信息</span></legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <label class="layui-form-label">展示名称：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="app名称" name="title"
                       value="{{=d.title }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">副标题：</label>
            <div class="layui-input-block">
                <input placeholder="副标题" name="sub_title"
                       value="{{=d.sub_title }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">导航</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('nag_id', $nagArr,['data-value' => '{{=d.nag_id}}']) ?>
                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">类型:</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('type', ConstructModel::TYPE_TIPS,['data-value' => '{{=d.type}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">分类样式:</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('show_style', ConstructModel::SHOW_STYLE,['data-value' => '{{=d.show_style}}']) ?>
                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">数量：</label>
                <div class="layui-input-block">
                    <input placeholder="最大数量" name="show_max"
                           value="{{=d.show_max }}" class="layui-input">

                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">查询tab:</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('has_tab', ConstructModel::TAB_TIPS,['data-value' => '{{=d.has_tab}}']) ?>
                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">换一换：</label>
                <div class="layui-input-block">
                    <?php echo Layui::select('has_hyh', ConstructModel::HYH_TIPS,['data-value' => '{{=d.has_hyh}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">排序：</label>
            <div class="layui-input-block">
                <input placeholder="排序" name="sort_num"
                       value="{{=d.sort_num }}" class="layui-input">

            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">图标：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('icon_url', 'icon') ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">背景图：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('bg_thumb_url', 'bg_thumb') ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">简介：</label>
            <div class="layui-input-block">
                <input placeholder="简介" name="intro"
                       value="{{=d.intro}}" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<style>
    .layui-table-cell {
        height: 50px;
        line-height: 50px
    }


    .layui-xtree-item {
        display: inline-block;
        width: 80px;
    }
</style>
<script src="<?php echo LAY_UI_STATIC ?>layuiadmin/layui-xtree.js?t=<?php echo time(); ?>"></script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: undefined,
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: '编号', width: 100}
            , {field: 'title', title: 'app名称',edit: true}
            , {field: 'sub_title', title: '副标题',edit: true}
            , {
                field: 'icon', title: '图标', width: 80, templet: function (d) {
                    if (d.icon_url){
                        return '<img src="' + d.icon_url + '" style="width: 50px;height: 40px;" onclick="show_img(\'' + d.icon_url + '\')">';
                    }else{
                        return "";
                    }
                }
            }
            , {
                field: 'icon', title: '背景图', width: 80, templet: function (d) {
                    if (d.bg_thumb_url){
                        return '<img src="' + d.bg_thumb_url + '" style="width: 50px;height: 40px;" onclick="show_img(\'' + d.bg_thumb_url + '\')">';
                    }else{
                        return "";
                    }
                }
            }
            , {field: 'nag_title', title: '导航名称'}
            , {field: 'type_str', title: '类型'}
            , {field: 'show_style_str', title: '分类样式(导航)', width: 130}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true}
            , {field: 'is_search', title: '推荐', type: "switch", "value": "1|0", edit: true}
            , {field: 'sort_num', title: '排序', sort: true,edit: true}
            , {field: 'work_num', title: '作品数', sort: true}
            , {field: 'favorites_num', title: '收藏数', sort: true}
            , {field: 'rating', title: '点击量', sort: true}
            //, {field: 'updated_str', title: '更新'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "done": function (table, data, from, ajax, tpl, $) {
            ajax.get("<?php echo url_backend('mv/tagsList')?>")
                .then(function (json) {
                    return json.data;
                })
                .then(function (data) {
                    xx.use({"menu": data})
                })
        },
        event: {
            'toolbar':{
                worksUpdate: function (obj, table, ajax, laytpl, layerEle, form, $) {
                    layer.confirm('此功能不能频繁使用，确定需要更新分类作品数?', function (index2) {
                        ajax.post("<?php echo url_backend('works_update')?>", {})
                            .then(function (json) {
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.data);
                                    table.reload('gridTab');
                                }
                            })
                    });
                },
            },
            "operate": {
            },
        }

    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>