<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">漫画ID，剧集ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[m_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">章节ID，单本默认1</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[s_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">漫画ID，剧集ID：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="漫画ID，剧集ID" name="m_id"
                           value="{{=d.m_id }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">章节ID，单本默认1：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="章节ID，单本默认1" name="s_id"
                           value="{{=d.s_id }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">漫画图片显示顺序：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="漫画图片显示顺序" name="short"
                           value="{{=d.short }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">图片地址：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="图片地址" name="img_url"
                           value="{{=d.img_url }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">img_width：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="img_width" name="img_width"
                           value="{{=d.img_width }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">img_height：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="img_height" name="img_height"
                           value="{{=d.img_height }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">from：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="from" name="from"
                           value="{{=d.from }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id',sort:true, width: 100}
            , {field: 'm_id', title: '漫画ID',sort:true, width: 100}
            , {field: 's_id', title: '章节ID',sort:true, width: 100}
            //, {field: 'thumb_url', title: '缩率图'}
            //, {field: 'img_url', title: '图片地址'}
            , {
                field: 'img_url', title: '新封面图', width: 180, templet: function (d) {
                    if (d.img_url) {
                        return '<img src="' + d.img_url_full + '" style="width: 100px;height: 80px;" onclick="show_img(\'' + d.img_url_full + '\')">';
                    } else {
                        return '--';
                    }
                }
            }
            , {field: 'img_width', title: '图宽',edit:true}
            , {field: 'img_height', title: '图高',edit:true}
            // , {field: 'created_at', title: '创建时间'}
            // , {field: 'updated_at', title: '更新时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>