<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header" style="color: #FF5722">制片人列表</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">uuid</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[uuid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">手机</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[phone]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">

                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="refuse">
                            <i class="layui-icon layui-icon-delete"></i>取消资格</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>&where[status]=<?php echo MemberMakerModel::CREATOR_STAT_YES; ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: undefined,
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
             {field: 'id', title: '#',width: 100}
            , {field: 'uuid', title: 'uuid'}
            , {field: 'level_num', title: '等级'}
            , {field: 'phone', title: '手机'}
            //, {field: 'status', title: '0 缺省 1待审核  2 未通过  3. 禁用 4 正常 '}
            , {field: 'refuse_reason', title: '拒绝理由'}
            , {field: 'created_at', title: '时间'}
            , {field: 'nickname', title: '昵称'}
            //, {field: 'contact', title: '扩展联系方式'}
            , {field: 'total_coins', title: '累计汤币',sort:true}
            , {field: 'pay_rate', title: '结算比例',edit:true}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "event": {
            "operate": {
                /**
                 * 拒绝
                 */
                "refuse": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    var index = layer.prompt({"title": "取消资格理由", formType: 2, area: ['250px', '80px']}, function (val) {
                        if (val.length <= 0) {
                            Util.msgErr("理由不能为空");
                            return;
                        }
                        layer.confirm('再次确认取消创作者身份认证资格?', function (index2) {
                            var index3 = layer.load(0, {time: 3 * 1000, shade: [0.5, '#666']});
                            ajax.post("<?php echo url_backend('doCancel')?>", {"refuse": val, "id": $this.data('pk')})
                                .then(function (json) {
                                    layer.close(index);
                                    layer.close(index);
                                    layer.close(index3);
                                    if (json.code) {
                                        Util.msgErr(json.msg);
                                    } else {
                                        Util.msgOk(json.msg, Util.reload);
                                    }
                                })
                        });
                    });
                }
            }
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>