<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">直播ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[live_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">PID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[pid]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">用户aff</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[aff]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态
                            </label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]', merge_array(['' => '全选'], LiveCommentModel::STATUS_TIPS)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">置顶
                            </label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_top]', merge_array(['' => '全选'], LiveCommentModel::TOP_TIPS)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                            <button class="layui-btn layui-btn-sm" lay-event="passSelect" data-pk="id">批量通过</button>
                            <button class="layui-btn layui-btn-sm" lay-event="refuseSelect" lay-form="refuseSelect" data-pk="id">批量拒绝</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        {{# if(d.status == 0 ) { }}
                        <a class="layui-btn layui-btn-xs" lay-event="pass" data-pk="{{=d.id}}" data-flag="ban">
                            通过</a> ｜
                        <a class="layui-btn layui-btn-xs" lay-event="refuse" data-pk="{{=d.id}}" data-flag="black">
                            拒绝</a> ｜
                        {{# } }}
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">直播ID：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="直播ID" name="live_id"
                           value="{{=d.live_id }}" class="layui-input">

                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">PID：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="评论ID,默认0(第一层评论)" name="pid"
                           value="{{=d.pid }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户aff：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="用户aff" name="aff"
                           value="{{=d.aff }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">留言内容：</label>
            <div class="layui-input-block">

                <input placeholder="留言内容" name="comment"
                       value="{{=d.comment }}" class="layui-input">

            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">0:待审核 1:审核通过 2.未通过：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="0:待审核 1:审核通过 2.未通过" name="status"
                           value="{{=d.status }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户ip：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="用户ip" name="ipstr"
                           value="{{=d.ipstr }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">定位城市：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="定位城市" name="cityname"
                           value="{{=d.cityname }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">拒绝通过原因：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="拒绝通过原因" name="refuse_reason"
                           value="{{=d.refuse_reason }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">created_at：</label>
                <div class="layui-input-inline">

                    <input placeholder="created_at" name="created_at"
                           value="{{=d.created_at }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">updated_at：</label>
                <div class="layui-input-inline">

                    <input placeholder="updated_at" name="updated_at"
                           value="{{=d.updated_at }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">是否置顶 0未置顶 1已置顶：</label>
                <div class="layui-input-inline">

                    <input placeholder="是否置顶 0未置顶 1已置顶" name="is_top"
                           value="{{=d.is_top }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" id="a1">
    直播ID：{{d.live_id}}<br>
    PID：{{d.pid}}<br>
    IP：{{d.ipstr}}  <br>
    城市：{{d.cityname}}
</script>
<script type="text/html" id="a4">
    <div class="td-cover-title" style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;position: relative">
        <img onclick="show_img('{{d.user_thumb}}')" width="100" height="100" src="{{d.user_thumb}}">
    </div>
    <hr/>
    aff：<span class="st">{{d.aff}}</span>
    <hr/>
    昵称：<span class="st">{{d.user_nickname}}</span>
</script>
<script type="text/html" id="a2">
    <span style="color: {{d.status==1 ? 'blue':'red'}};font-weight: bold;">{{d.status_str}}</span><br>
</script>
<script type="text/html" id="a3">
    创建时间：{{d.created_at}}<br>
    更新时间：{{d.updated_at}}
</script>
<script type="text/html" class="data-dialog" id="refuseSelect" data-h="480" data-w="700" layer-dialog="确认,取消"
        data-option="{title:'拒绝申请',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>审核不通过</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">选择拒绝的理由：</label>
            <div class="layui-input-block">
                <select name="refused" class="refused layui-select" id="refused" data-id="{{d.id}}">
                    <option value="">选择拒绝理由</option>
                    <option value="评论植入广告或联系方式。">1.评论植入广告或联系方式。</option>
                    <option value="评论内容标题和主题不符。">2.评论内容标题和主题不符。</option>
                    <option value="评论不适用抖阴MAX'',含暴力/血腥/未成年等违反国际法行为">3.评论不适用抖阴MAX'',含暴力/血腥/未成年等违反国际法行为
                    </option>
                    <option value="其他">4.其他</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="comment_ids" value="">
            <button class="layui-btn submit" lay-submit="" lay-filter="refuseSelect"></button>
        </div>
    </form>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id',width:100}
            , {field: 'pos', title: '信息', width: 200, templet:'#a1'}
            , {field: 'aff', title: '用户',templet:'#a4',width:160}
            , {field: 'comment', title: '留言内容'}
            , {field: 'status', title: '状态',templet:'#a2',width:160}
            , {field: 'is_top', title: '置顶',type:"switch",value: "1|0", edit: true, width: 120}
            , {field: 'created_at', title: '时间',templet:'#a3',width:220}
            , {fixed: 'right', width: 300, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event: {
            'toolbar': {
                passSelect: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');

                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }

                    layer.confirm('确定审核通过吗?', function (index) {
                        layer.close(index);
                        ajax.post("<?php echo url_backend("passAll") ?>", {
                            "ids": pkValAry.join(','),
                        })
                            .then(function (json) {
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, function (){
                                        table.reload("gridTab");
                                    });
                                }
                            })
                    });
                },
                refuseSelect: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');

                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        form.val("form-save", {
                            "comment_ids": pkValAry.join(',')
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('batchRefuse')?>", form, ajax, 'refuseSelect', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
            },
            operate: {
                /**
                 * 通过
                 */
                "pass": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('真的通过审核吗?', function (index) {
                        layer.close(index);
                        ajax.post("<?php echo url_backend("doPass") ?>", {"id": $this.data('pk')})
                            .then(function (json) {
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    table.reload("gridTab");
                                }
                            })
                    });
                },

                /**
                 * 拒绝
                 */
                "refuse": function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    var index3 = layer.load(0, {time: 3 * 1000, shade: [0.5, '#666']});
                    layer.confirm('真的要拒绝吗?', function (index) {
                        ajax.post("<?php echo url_backend("doReject") ?>", {"id": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index3);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    table.reload("gridTab");
                                }
                            })
                    });
                }
            }
        },
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>