<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>
    .layui-form.form-dialog .layui-input-block {
        margin-right: 5px
    }

    .layui-form-item .layui-inline {
        margin-right: 0px
    }
    .layui-xtree-item {
        display: inline-block;
        width: 200px;
    }
    .copy-item {
        cursor: pointer;
        padding: 10px;
        background-color: #f0f0f0;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin: 5px 0;
        display: block;
        white-space: pre-wrap;
    }

    .copy-item:hover {
        background-color: #e0e0e0;
    }

    .alert {
        padding: 10px;
        margin: 20px;
        border: 1px solid #d4edda;
        border-radius: 5px;
        background-color: #d4edda;
        color: #155724;
        font-size: 16px;
        position: fixed;
        top: 500px;
        right: 800px;
        z-index: 1000;
        opacity: 0;
        transition: opacity 0.3s ease-in-out;
    }

    .alert.show {
        opacity: 1;
    }
</style>

<script type="text/html" id="search-total">
    <p style="font-size: medium;margin-left: 10px;">
        数量:{{=d.total}}
    </p>
</script>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">黄游管理<span style="color: red" class="layui-inline" id="total-id"></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off" class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="like[name]" placeholder="请输入"
                                       autocomplete="off" class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">分类</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[category_id]', merge_array(['' => '全部'], $cat_list)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">解锁类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[type]', merge_array(['' => '全部'], PornGameModel::TYPE_TIPS)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">热门</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_hot]', merge_array(['' => '全部'], PornGameModel::HOT_TIPS)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]', merge_array(['' => '全部'], PornGameModel::STATUS_TIPS)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">排序</label>
                            <div class="layui-input-block">
                                <select name="orderBy[sort]">
                                    <option value="">无</option>
                                    <option value="desc">降序</option>
                                    <option value="asc">升序</option>
                                </select>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">浏览</label>
                            <div class="layui-input-block">
                                <select name="orderBy[real_view_count ]">
                                    <option value="">无</option>
                                    <option value="desc">降序</option>
                                    <option value="asc">升序</option>
                                </select>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">点赞</label>
                            <div class="layui-input-block">
                                <select name="orderBy[real_like_count]">
                                    <option value="">无</option>
                                    <option value="desc">降序</option>
                                    <option value="asc">升序</option>
                                </select>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">金币</label>
                            <div class="layui-input-block">
                                <?php echo Layui::between('coins') ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">创建时间</label>
                            <div class="layui-input-block">
                                <?php echo Layui::dateBetween('created_at') ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">添加</button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchAddCategory" data-pk="id" lay-form="batch-add-category">设置分类</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchAddTags" data-pk="id" lay-form="batch-add-tags">设置标签</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchAddPay" data-pk="id" lay-form="batch-add-pay">购买设置</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchAddHot" data-pk="id" lay-form="batch-add-hot">热门设置</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchAddShow" data-pk="id" lay-form="batch-add-show">显示设置</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchRefresh" data-pk="id" lay-form="batch-refresh">刷新</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a lay-event="edit" lay-form="user-edit-dialog" style="color: blue">修改</a> |
                        <a data-pk="{{=d.id}}" lay-event="del" style="color: red">删除</a> |
                        <a href="javascript:;" lay-event="refresh" data-id="{{d.id}}">刷新</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="1500" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <label class="layui-form-label">标题：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="标题" name="name"
                       value="{{=d.name }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">分类：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('category_id', $cat_list, ['data-value' => '{{=d.category_id}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-form-item">
                <label class="layui-form-label">标签：</label>
                <div class="layui-input-block">
                    <div id="adminrole_div_tags" class="xtree_contianer" style="margin-bottom: 10px"></div>

                </div>

            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面：</label>
                <div class="layui-input-block">
                    <?php echo Layui::uploadPos('thumb_all', 'thumb') ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">图片：</label>
            <div class="layui-input-block">
                {{# layui.each(new Array(9), function(index, item){ }}
                <div class="layui-form-item">
                    <label class="layui-form-label">资源图{{index+1||0}}：</label>
                    <div class="layui-input-block">
                        <img src="{{d.imgs ? d.imgs[index]['media_url']:''}}" id="img-img_url_{{index}}" width="50" height="50">
                        <button type="button" class="but-upload-img layui-btn"
                                data-img="#img-img_url_{{index}}" data-input="#input-img_url_{{index}}"><i class="layui-icon">&#xe67c;</i>上传
                        </button>
                        <input placeholder="删除资源可以清空文本框保存" class="layui-input" name="img_url[]" id="input-img_url_{{index}}" value="{{ d.imgs ? d.imgs[index]['ori_media_url']:'' }}">
                    </div>
                </div>
                {{# }); }}
            </div>
        </div>

        <div class="layui-form-item">
            <input lay-verify="required" type="hidden" placeholder="IP" name="ipstr" value="{{d.ipstr||'127.0.0.1' }}" class="layui-input">
            <input lay-verify="required" type="hidden" placeholder="定位城市" name="cityname" value="{{d.cityname||'火星' }}" class="layui-input">
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">解锁类型：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('type', PornGameModel::TYPE_TIPS, ['data-value' => '{{=d.type}}']) ?>
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">解锁金币：</label>
                <div class="layui-input-inline">
                    <input placeholder="解锁金币" name="coins" value="{{d.coins || 0 }}"
                           class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('status', PornGameModel::STATUS_TIPS, ['data-value' => '{{=d.status}}']) ?>
                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">排序：</label>
                <div class="layui-input-inline">
                    <input placeholder="排序" name="sort" value="{{d.sort||0}}"
                           class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">假浏览：</label>
                <div class="layui-input-inline">
                    <input placeholder="假浏览" name="view_count" value="{{d.view_count || 0 }}"
                           class="layui-input">
                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">假赞：</label>
                <div class="layui-input-inline">
                    <input placeholder="假赞" name="like_count" value="{{d.like_count || 0 }}"
                           class="layui-input">
                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">假解锁：</label>
                <div class="layui-input-inline">
                    <input placeholder="假解锁" name="buy_fake" value="{{d.buy_fake || 0 }}"
                           class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">游戏简介：</label>
            <div class="layui-input-block">
                <textarea rows="10" name="intro" class="layui-textarea">{{d.intro || '' }}</textarea>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label"><span style="color: red">下载地址及密码：</span></label>
            <div class="layui-input-block">
                <textarea rows="10" name="content" class="layui-textarea">{{d.content || '' }}</textarea>
            </div>
            <span style="color:red;margin-left: 110px">格式说明(前面是单"|"分隔,所有|都是英文状态,多条数据换行)</span><br>
            <span style="color:red;margin-left: 110px">电脑<span style="color: black">|</span>https://mhscloud.xyz/game/6000-7000/6580</span><br>
            <span style="color:red;margin-left: 110px">android<span style="color: black">|</span>https://mhscloud.xyz/game/6000-7000/6580</span><br>
            <span style="color:red;margin-left: 110px">提取码<span style="color: black">|</span>opeq</span><br>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">游戏玩法：</label>
            <div class="layui-input-block">
                <textarea rows="10" name="play_intro" class="layui-textarea">{{d.play_intro || '' }}</textarea>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">游戏说明：</label>
            <div class="layui-input-block">
                <textarea rows="10" name="desc" class="layui-textarea">{{d.desc || '' }}</textarea>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script type="text/html" class="data-dialog" id="batch-add-category" data-h="600" data-w="700" layer-dialog="确认,取消"
        data-option="{title:'设置分类',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">设置分类</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">分类：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('category_id', $cat_list, ['data-value' => '{{=d.category_id}}']) ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="porn_ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchCategory"></button>
        </div>
    </form>
</script>

<script type="text/html" class="data-dialog" id="batch-add-tags" data-h="700" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'设置标签',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">设置标签</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">标签：</label>
            <div class="layui-input-block">
                <div id="adminrole_div_tags" class="xtree_contianer" style="margin-bottom: 30px"></div>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="porn_ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchTags"></button>
        </div>
    </form>
</script>

<script type="text/html" class="data-dialog" id="batch-add-pay" data-h="500" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'购买设置',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">购买设置</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">解锁类型</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('type', PornGameModel::TYPE_TIPS) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">金币</label>
            <div class="layui-input-inline">
                <input name="coins" value="" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="porn_ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchPay"></button>
        </div>
    </form>
</script>

<script type="text/html" class="data-dialog" id="batch-add-hot" data-h="500" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'热门设置',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">热门设置</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">热门</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('is_hot', PornGameModel::HOT_TIPS) ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="porn_ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchHot"></button>
        </div>
    </form>
</script>


<script type="text/html" class="data-dialog" id="batch-add-show" data-h="500" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'显示设置',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">显示设置</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">是否显示</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('status', PornGameModel::STATUS_TIPS) ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="porn_ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchShow"></button>
        </div>
    </form>
</script>
<script type="text/html" id="a2">
    <span style="color:blue">标题:{{d.name}}</span>&nbsp;&nbsp;<span style="color: darkgreen"></span>
    <hr/>
    <h4 style="white-space: pre-wrap;color: red">分类(*):{{d.category_title}}</h4>
    <hr/>
    <h4 style="white-space: pre-wrap;color: red">标签:{{d.tags}}</h4>
</script>
<script type="text/html" id="a11">
    <h4 style="white-space: pre-wrap;">游戏简介:<br>{{d.intro}}</h4>
    <hr/>
    <h4 style="white-space: pre-wrap;">游戏玩法:<br>{{d.play_intro}}</h4>
    <hr/>
    <h4 style="white-space: pre-wrap;">游戏说明:<br>{{d.desc}}</h4>
</script>
<script type="text/html" id="a12">
    {{# layui.each(d.links, function(index, item){ }}
        <div class="copy-item" data-copy="{{item || '' }}" onclick="copyText(this)">{{item || '' }}</div>
        <br/>
    {{# }); }}
</script>
<script type="text/html" id="a5">
    <span style="color: red">解锁类型：{{d.type_str}}</span><br>
    <span style="color: red">金币：{{d.coins}}</span><br>
    次数：{{d.buy_num}}  <br>
    金币数：{{d.buy_coins}}
</script>
<script type="text/html" id="a3">
    点赞：{{d.real_like_count}} &nbsp;|&nbsp;
    评论：{{d.comment_count}} <br>
    浏览：{{d.real_view_count}} |
    收藏：{{d.real_like_count}}<br>
    创建:{{d.created_at}}<br>
    涮新:{{d.refresh_at}}
</script>
<script type="text/html" id="attr3-xx">
    <div style="line-height: normal">
        封面:
        <img style="display: inline-block;width: 25px;height: 25px;margin-bottom: 3px;" onclick="clickShowImage(this)" src="{{=d.thumb_all}}">
    </div>
    <div style="line-height: normal">
        图片:
        {{# layui.each(d.show_imgs, function(index, item){ }}
        <img style="display: inline-block;width: 25px;height: 25px;margin-bottom: 3px;" onclick="clickShowImage(this)" src="{{=item.media_url}}">
        {{# }); }}
    </div>
</script>
<script src="<?php echo LAY_UI_STATIC ?>layuiadmin/layui-xtree.js?t=<?php echo time(); ?>"></script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id',sort:true,width:60}
            , {field: 'content', title: '标题',templet:'#a2',width:300}
            , {field: 'content', title: '内容',templet:'#a11',width:300}
            , {field: 'address', title: '下载地址',templet:'#a12',width:300}
            , {field: 'coins', title: '解锁设置',templet:'#a5',width:150}
            , {field: 'media', title: '资源',templet:'#attr3-xx',width:300}
            , {field: 'source', title: '属性',templet:'#a3',width:200}
            , {field: 'status', title: '状态',type:"switch",value: "1|0", edit: true}
            , {field: 'is_hot', title: '热门',type:"switch",value: "1|0", edit: true}
            , {field: 'sort', title: '排序',sort:true,edit:true, width: 80}
            // , {field: 'real_view_num', title: '浏览',sort:true, width: 80}
            // , {field: 'favorite_num', title: '收藏',sort:true, width: 80}
            // , {field: 'like_num', title: '点赞',sort:true, width: 80}
            // , {field: 'comment_num', title: '评论',sort:true, width: 80}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        "done": function (table, data, from, ajax, tpl, $) {
            ajax.get("<?php echo url_backend('porncategoryconf/list')?>")
                .then(function (json) {
                    return json.data;
                })
                .then(function (data) {
                    xx.use({"menu": data})
                });
            ajax.get("<?php echo url_backend('porntags/list')?>")
                .then(function (json) {
                    return json.data;
                })
                .then(function (data) {
                    xx.use({"menu_tags": data})
                });
        },
        event:{
            search: function (ajax, laytpl, where) {
                ajax.get("<?php echo url_backend('total')?>&" + xx.queryEncode(where)).then(function (json) {
                    if (json.code == '0') {
                        let data = json.data, $ = layui.$;
                        $('#total-id').html(laytpl($('#search-total').html()).render(data));
                    }
                });
            },
            'toolbar': {
                addUser: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn();
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn);
                    xx.config('event.renderTreeTags', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn);
                },
                batchAddCategory: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');
                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                        form.val("form-save", {
                            "porn_ids": pkValAry.join(','),
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchCategory')?>", form, ajax, 'addBatchCategory', function (json) {
                            layer.closeAll()
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                batchAddTags: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');
                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        xx.config('event.renderTreeTags', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                        form.val("form-save", {
                            "porn_ids": pkValAry.join(','),
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchTags')?>", form, ajax, 'addBatchTags', function (json) {
                            layer.closeAll()
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                batchAddPay: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');
                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        form.val("form-save", {
                            "porn_ids": pkValAry.join(',')
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchPay')?>", form, ajax, 'addBatchPay', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                batchAddHot: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');
                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        form.val("form-save", {
                            "porn_ids": pkValAry.join(',')
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchHot')?>", form, ajax, 'addBatchHot', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                batchAddShow: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');
                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        form.val("form-save", {
                            "porn_ids": pkValAry.join(',')
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchShow')?>", form, ajax, 'addBatchShow', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                batchRefresh: function (obj, table, ajax, laytpl, layerEle, form, $) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');

                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    ajax.post("<?php echo url_backend('addBatchRefresh')?>", {"ids": pkValAry.join(',')})
                        .then(function (json) {
                            if (json.code) {
                                Util.msgErr(json.msg);
                            } else {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            }
                        })
                },
            },
            operate:{
                edit: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn();
                    xx.config('event.renderTreeTags', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn);
                },
                refresh: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    ajax.post("<?php echo url_backend('refresh')?>", {"id": $this.data('id')})
                        .then(function (json) {
                            Util.msgOk(json.msg);return;
                            if (json.code) {
                                Util.msgErr(json.msg);
                            } else {
                                Util.msgOk(json.msg,function () {
                                    table.reload("gridTab");
                                });
                            }
                        })
                },
            },
            "renderTreeTags": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                let ruleArray = [] , menudata = xx.config('menu_tags'), treeJson = [];

                if (typeof(obj.data) !=="undefined"){
                    ruleArray = obj.data.tags
                }
                $.each(menudata, function (i, item, data) {
                    data = {
                        "inputname": 'tags[]',
                        "title": item,
                        "value": item,
                        "checked": in_array(item, ruleArray),
                        "data": [],
                    };
                    treeJson.push(data);
                });
                Util.renderSelect(obj.data , $,form);
                new layuiXtree({
                    elem: 'adminrole_div_tags'
                    , form: form
                    , data: treeJson
                });
            },
        }
    });

    layui.use(['form', 'jquery', 'laytpl'], function () {
        let form = layui.form;
        let $ = layui.jquery;
        let laytpl = layui.laytpl;
        let data = form.val('order-search');
        //console.log('order-search'+xx.queryEncode(data))
        $.ajax({
            url: "<?php echo url_backend('total')?>&" + xx.queryEncode(data),
            dataType: 'json',
            success: function (json) {
                //console.log(json.code)
                if (json.code == '0') {
                    let response = json.data;
                    $('#total-id').html(laytpl($('#search-total').html()).render(response));
                }
            }
        });
    })
</script>
<script>
    // Function to copy text to clipboard
    function copyText(element) {
        var text = element.getAttribute('data-copy')
        // Create a temporary textarea element
        var textarea = document.createElement('textarea');
        textarea.value = text;
        document.body.appendChild(textarea);

        // Select the text inside the textarea
        textarea.select();
        textarea.setSelectionRange(0, 99999); // For mobile devices

        // Copy the text to the clipboard
        document.execCommand('copy');

        // Remove the textarea
        document.body.removeChild(textarea);

        // Show success message
        showSuccessMessage();
    }

    function showSuccessMessage() {
        var alertBox = document.createElement('div');
        alertBox.className = 'alert show';
        alertBox.textContent = '复制成功!';
        document.body.appendChild(alertBox);

        // Hide the alert after 0.5 seconds
        setTimeout(function() {
            alertBox.classList.remove('show');
            // Remove the alert from DOM after transition ends
            setTimeout(function() {
                document.body.removeChild(alertBox);
            }, 300); // Match the duration of the transition
        }, 500); // Duration to display the message
    }
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>