<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">代理ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[agent_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">渠道</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[channel]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[type]',
                                    merge_array(['' => '不限'], AgentSettlementModel::TYPES)) ?>

                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">展示</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_show]',
                                    merge_array(['' => '不限'], AgentSettlementModel::SHOW)) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>

                            <button class="layui-btn layui-btn-disabled"><span style="color: orangered;font-weight: bolder">备注：删除的信息没有操作权限，并且渠道不可见</span></button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>

                        {{#  if(d.is_delete == 0){ }}
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                        {{#  } }}

                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">代理ID：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="代理ID" name="agent_id"
                       value="{{=d.agent_id }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">渠道：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="渠道" name="channel"
                       value="{{=d.channel }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">类型：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('type', AgentSettlementModel::TYPES,
                    ['data-value' => '{{=d.type}}']) ?>
            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">结算开始时间：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="结算开始时间 eg: 2019-01-01" name="start"
                       value="{{=d.start }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">结算截止时间：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="结算截止时间 eg: 2019-01-31" name="end"
                       value="{{=d.end }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">比例(%)：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="比例" name="rate"
                       value="{{=d.rate }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">结算总额(元)：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="结算总额" name="total_amount"
                       value="{{=d.total_amount }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">应到总额(元)：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="应到总额" name="real_amount"
                       value="{{=d.real_amount }}" class="layui-input">

            </div>

        </div>

        <div class="layui-form-item">

            <label class="layui-form-label">备注：</label>
            <div class="layui-input-block">
                    <textarea  style="color: orangered;width: 85%;height: 100px;"   class="layui-input" name="description" lay-verify="required" placeholder="电话号码 + 银行卡及关键信息备注 不能为空">{{=d.description }}</textarea>


            </div>

        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">代理是否可见：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('is_show', AgentSettlementModel::SHOW,
                        ['data-value' => '{{=d.is_show}}']) ?>

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>详细信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">

            <label class="layui-form-label">编号：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.id }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">代理ID：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.agent_id }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">渠道：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.channel }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">类型：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('type', AgentSettlementModel::TYPES,
                    ['data-value' => '{{=d.type}}', 'disabled'=>'disabled']) ?>

            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">结算开始：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.start }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">结算截止：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.end }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">比例：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.rate }}%" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">结算总额：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.total_amount }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">应到总额：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.real_amount }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">创建日期：</label>
            <div class="layui-input-block">
                <input disabled value="{{=d.add_time }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">备注：</label>
            <div class="layui-input-block" >

                <textarea style="color: orangered;width: 85%;height: 100px;" class="layui-input" disabled placeholder="电话号码 + 银行卡及关键信息备注 不能为空">{{=d.description }}</textarea>
            </div>

        </div>
        <div class="layui-form-item">

            <label class="layui-form-label">可见性：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('is_show', AgentSettlementModel::SHOW,
                    ['data-value' => '{{=d.is_show}}', 'disabled'=>'disabled']) ?>
            </div>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            /*{type: 'checkbox', fixed: 'left'}*/
            {field: 'id', title: 'id'}
            , {field: 'agent_id', title: '代理ID'}
            , {field: 'channel', title: '渠道'}
            , {field: 'type', title: '类型', type: "enum", value:<?php echo json_encode(AgentSettlementModel::TYPES) ?>}
            , {field: 'start', title: '结算开始'}
            , {field: 'end', title: '结算截止'}
            , {field: 'rate', title: '比例（%）'}
            , {field: 'total_amount', title: '结算总额'}
            , {field: 'real_amount', title: '实到总额'}
            , {field: 'add_time', title: '创建时间'}
            /*, {field: 'description', title: '备注'}*/

            , {field: 'is_show', title: '展示', type: "switch", "value": "1|0", edit: true}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<script type="text/javascript" src="<?php echo LAY_UI_STATIC ?>/data-list.js"></script>
<?php importView("fooler.phtml"); ?>