<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">资源类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[resource_type]', PrivilegeModel::RESOURCE_TYPE) ?>

                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">权限类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[privilege_type]', PrivilegeModel::PRIVILEGE_TYPE) ?>

                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" data-h="700" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">资源类型：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('resource_type', PrivilegeModel::RESOURCE_TYPE,
                    ['data-value' => '{{=d.resource_type}}']) ?>


            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">权限类型：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('privilege_type', PrivilegeModel::PRIVILEGE_TYPE,
                    ['data-value' => '{{=d.privilege_type}}']) ?>


            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">总数值：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="数值" name="value"
                       value="{{=d.value }}" class="layui-input">

            </div>

        </div>

        <div class="layui-form-item">

            <label class="layui-form-label">每日数值：</label>
            <div class="layui-input-block">

                <input placeholder="数值" name="day_value"
                       value="{{=d.day_value }}" class="layui-input">

            </div>

        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">排序：</label>
            <div class="layui-input-block">
                <input placeholder="排序" name="sort" value="{{=d.sort }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="created_at" value="<?php echo time() ?>">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id', sort: true, width: 100}
            , {field: 'resource_type', title: '资源ID', width: 90, sort: true}
            , {field: 'privilege_type', title: '权限ID', width: 90, sort: true}
            , {field: 'resource_type_str', title: '资源'}
            , {field: 'privilege_type_str', title: '权限'}
            , {field: 'value', title: '数值'}
            , {field: 'day_value', title: '每日数值'}
            , {field: 'sort', title: '排序', edit:true, sort: true}
            //, {field: 'created_at', title: 'created_at'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>