<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理<span class="layui-inline" style="color: orangered" id="total-id"></span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="like[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">金币</label>
                            <div class="layui-input-block">
                                <?php echo Layui::between("coins") ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">推荐</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[recommend]', PictureModel::RECOMMEND); ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">上架</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[status]', PictureModel::STATUS); ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">标签</label>
                            <div class="layui-input-block">
                                <input type="text" name="like[tags]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <!--  <div class="layui-btn-container">
                              <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                  添加
                              </button>
                              <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                          </div>-->
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <!--<a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>-->
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn  layui-btn-xs" data-pk="{{=d.id}}" lay-event="refresh">涮新</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">标题：</label>
            <div class="layui-input-block">
                <input placeholder="标题" name="title"
                       value="{{=d.title }}" class="layui-input">

            </div>
        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">描述：</label>
            <div class="layui-input-block">

                <input placeholder="描述" name="description"
                       value="{{=d.description }}" class="layui-input">

            </div>
        </div> <div class="layui-form-item">

            <label class="layui-form-label">标签：</label>
            <div class="layui-input-block">

                <input placeholder="标签" name="tags"
                       value="{{=d.tags }}" class="layui-input">

            </div>
        </div>

        <!-- <div class="layui-form-item">
            <label class="layui-form-label">系列分类：</label>
            <div class="layui-input-block">
                <?php /*echo Layui::select('category_id', ComicsCategoryModel::getCategoryName(),
                    ['data-value' => '{{=d.category_id }}']) */?>
            </div>
        </div>-->


        <div class="layui-form-item">

            <label class="layui-form-label">图片：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadPos('thumb_full', 'thumb', 40, 40, 'ads') ?>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">观币：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="观币" name="coins"
                           value="{{d.coins||0 }}" class="layui-input">

                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">更新：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="更新" name="update_time"
                           value="{{=d.update_time }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">推荐：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('recommend', PictureModel::RECOMMEND,
                        ['data-value' => "{{=d.recommend}}"]) ?>
                </div>
            </div>

            <div class="layui-inline">
                <label class="layui-form-label">上架：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('status', PictureModel::STATUS, ['data-value' => "{{=d.status}}"]) ?>

                </div>
            </div>

        </div>


        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" id="search-total">
    <p style="font-size: medium">
        找到：{{=d.count}}，条数据,收费内容：{{=d.count_fee}}，条,收费占比：{{=d.rate_fee}}%
    </p>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id', sort: true, width: 100},
            {field: 'p_id', title: '来源',  width: 100}
            , {field: 'title', title: '标题'}
            , {field: 'tags', title: '标签',edit:true ,width: 220}

            , {
                field: 'thumb', title: '新封面图', width: 180, templet: function (d) {
                    if (d.thumb) {
                        return '<img src="' + d.thumb_full + '" style="width: 100px;height: 80px;" onclick="show_img(\'' + d.thumb_full + '\')">';
                    } else {
                        return '--';
                    }
                }
            }
            , {field: 'total', title: '图片数',sort:true}
            , {field: 'coins', title: '扣币', edit: true}
            , {field: 'favorites', title: '收藏人数',sort:true}
            , {field: 'status', title: '上架', type: "switch", "value": "1|0", edit: true, width: 100}
            , {field: 'refresh_at', title: '刷新时间', sort: true}
            , {field: 'recommend', title: '推荐', type: "switch", "value": "1|0", edit: true}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event: {
            'search': function (ajax, laytpl, where) {
                ajax.get("<?php echo url_backend('total')?>&" + xx.queryEncode(where)).then(function (json) {
                    if (json.code == '0') {
                        let data = json.data, $ = layui.$;
                        $('#total-id').html(laytpl($('#search-total').html()).render(data));
                    }
                });
            },
            //event.operate->refuse
            "operate": {

                refresh: function (event, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    let $this = $(this),
                        data = {"id": $this.data('pk')};
                    ajax.post('<?php echo url_backend('refresh')?>', data)
                        .then(function (json) {
                            Util.msgOk('操作成功');
                        })
                },

            }

        }
    });

    layui.use(['form', 'jquery', 'laytpl'], function () {
        let form = layui.form;
        let $ = layui.jquery;
        let laytpl = layui.laytpl;
        let data = form.val('search-form');
        //console.log('search-form'+xx.queryEncode(data))
        $.ajax({
            url: "<?php echo url_backend('total')?>&" + xx.queryEncode(data),
            dataType: 'json',
            success: function (json) {
                //console.log(json.code)
                if (json.code == '0') {
                    let response = json.data;
                    $('#total-id').html(laytpl($('#search-total').html()).render(response));
                }
            }
        });
    })
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>