<!DOCTYPE html>
<!-- saved from url=(0049)http://91av.hyys.info/d.php?mod=static&code=index -->
<html>
<!-- Mirrored from www.zi-han.net/theme/hplus/table_basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:20:01 GMT -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>统计控制台</title>
    <link rel="shortcut icon" href="http://91av.hyys.info/favicon.ico">
    <link href="/static/admin/other/bootstrap.min14ed.css" rel="stylesheet">
    <link href="/static/admin/other/font-awesome.min93e3.css" rel="stylesheet">
    <link href="/static/admin/other/custom.css" rel="stylesheet">
    <link href="/static/admin/other/animate.min.css" rel="stylesheet">
    <link href="/static/admin/other/style.min862f.css" rel="stylesheet">
    <link href="/static/admin/other/admin.css" rel="stylesheet">

    <script src="/static/admin/other/jquery.min.js"></script>

    <script src="/static/admin/other/bootstrap.min.js"></script>
    <script src="/static/admin/other/jquery.peity.min.js"></script>
    <script src="/static/admin/other/icheck.min.js"></script>
    <link id="layuicss-skincodecss" rel="stylesheet" href="/static/admin/other/code.css" media="all">
    <link href="/static/admin/js/plugins/css/layui.css" rel="stylesheet">
</head>
<style>
    <?php

       $color = '#f8f8f8';
       $t = date("G");
       if($t>20 || $t<4){
           $color = 'lightgray';
       }

      ?>

    .layadmin-backlog  {
        display: block;
        background-color: <?php echo $color ?>;
        color: #999;
    }
    .layadmin-backlog-body{
        padding-top: 5px;
        border: 1px solid white;
        text-align: center;
    }
    .layadmin-backlog-body h3 {
        font-size: 12px;
    }

    .layadmin-backlog-body p cite{
        display: block;
        font-weight: bolder;
        color: #009688;
        font-size: x-large;
    }
</style>
<body>
<div class="wrapper wrapper-content animated fadeInRight">
    <script type="text/javascript" src="/static/admin/other/echarts.min.js" charset="utf-8"></script>
    <!--<script type="text/javascript" src="/static/admin/js/echarts-gl.min.js" charset="utf-8"></script>-->
    <span style="color: orangered">面板6分钟缓存</span>
    <div id="panelData" class="row col-sm-12 layadmin-backlog">
        <div class="layui-col-xs2 layadmin-backlog-body">

                <h3>今日活跃</h3>
                <p><cite>1000</cite></p>

        </div>
        <div class="layui-col-xs2 layadmin-backlog-body">
                <h3>今日新增 </h3>
                <p><cite>100 </cite></p>

        </div>
        <div class="layui-col-xs2 layadmin-backlog-body">

                <h3>官方来源</h3>
                <p><cite>2000</cite></p>

        </div>
        <div class="layui-col-xs2 layadmin-backlog-body">

                <h3>用户邀请 | 邀请成功</h3>
                <p><cite>1000 | 8000 </cite></p>

        </div>

    </div>
    <div class="row col-sm-12">
        <br/>
        <span style="color: orangered">曲线每半日缓存</span>
        <div style="width: 100%; height:280px;background-color: <?php echo $color ?>;" id="LAY-index-dataview">
            <!--KS-DATA-V-->
        </div>
        <hr size="2">
        <?php
        $chann = getChannelList();
        echo Layui::select('channel-d', merge_array(['' => '全部渠道'], array_combine($chann, $chann)),
            ['id' => 'channel-d']) ?>
        <div style="width: 100%; height:260px;background-color: <?php echo $color ?>;" id="LAY-index-dataview-agent">
            <!--KS-DATA-V-->
        </div>
    </div>
    <script type="text/javascript">

        function executeChart(legendData, category, seriesData, id, title) {
            echart_config = {
                title: {
                    text: title,
                    color: '##FF5722',
                    fontStyle: "italic"
                },
                legend: {
                    data: legendData
                },
                tooltip: {trigger: "axis"},
                xAxis: [{
                    type: "category",
                    data: category
                }],
                yAxis: [{type: "value"}],
                toolbox: {
                    feature: {
                        saveAsImage: {
                            name: "XBlue-DATA"
                        }
                    }
                },
                series: seriesData
            };

            var chart = echarts.init(document.getElementById(id));
            chart.setOption(echart_config);
        }

        function getPanelDataAjax() {
            $.ajax({
                url: '/d.php?mod=index&code=panelAjax',
                type: 'GET',
                success: function (res) {
                    if (res) {
                        $('#panelData').html(res).fadeIn(500);
                    }
                }
            });
        }

        function getChartAjax() {
            $.ajax({
                url: '/d.php?mod=index&code=chartAjax',
                type: 'GET',
                success: function (res) {
                    if (res.status == 1) {
                        let data = res.data
                        executeChart(data.legendData, data.category, data.seriesData, 'LAY-index-dataview', 'XBlue-Main');
                    }
                }
            });
        }

        function getChartAgentAjax(c) {
            $.ajax({
                url: '/d.php?mod=index&code=agentChartAjax&c=' + c,
                type: 'GET',
                success: function (res) {
                    if (res.status == 1) {
                        let data = res.data
                        executeChart(data.legendData, data.category, data.seriesData, 'LAY-index-dataview-agent', 'XBlue-Agent');
                    }
                }
            });
        }

        $(function () {
            setTimeout("getPanelDataAjax()", 1000); //delay 1s req
            setTimeout("getChartAjax()", 2000); //delay 3s req
            setTimeout("getChartAgentAjax('')", 3000); //delay 3s req
            $('#channel-d').bind('change', function () {
                let channel = $(this).val();
                getChartAgentAjax(channel);
            })
        })

    </script>
</div>
<script>
    $(document).ready(function () {
        $(".i-checks").iCheck({checkboxClass: "icheckbox_square-green", radioClass: "iradio_square-green",})
    });
</script>

</body>
</html>