<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>管理后台</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="<?php echo LAY_UI_STATIC ?>layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="<?php echo LAY_UI_STATIC ?>layuiadmin/style/admin.css" media="all">
</head>
<body>

<div class="layui-row layui-col-space5">
    <div class="layui-col-md12">
        <div class="layui-card">
            <div class="layui-card-header">数据统计&nbsp;<span
                        style="color: #029789;font-size: 12px;font-weight: bolder">实时数据</span></div>
            <div class="layui-card-body">

                <div class="layadmin-backlog">
                    <div carousel-item>
                        <ul id="pannel_ul" class="layui-row layui-col-space5">
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>视频总量</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>小视频量</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>精选视频量</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>用户总量</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>今日用户新增</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>7day用户新增</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>30day用户新增</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>

                            <li class="layui-col-xs2">
                                <a l class="layadmin-backlog-body">
                                    <h3>今日充值</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>累计充值</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>今日金币花费</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                            <li class="layui-col-xs2">
                                <a class="layadmin-backlog-body">
                                    <h3>今日提现</h3>
                                    <p><cite></cite></p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-col-md12">
        <div class="layui-card-header">
            数据概览&nbsp;<span style="color: #029789;font-size: 12px;font-weight: bolder">实时数据</span>
        </div>


        <div style="width: 100%; height:450px;background:#ffffff;padding: 30px" id="LAY-index-dataview">
            <div><i class="layui-icon layui-icon-loading1 layadmin-loading"></i></div>
        </div>
    </div>

<!--    <div class="layui-col-md12">-->
<!--        <div class="layui-card-header">渠道概览&nbsp;<span-->
<!--                    style="color: #029789;font-size: 12px;font-weight: bolder">实时数据6分钟缓存</span>&nbsp;<span>--><?php
//                $chann = AgentsUserModel::getChanDataList();
//                echo Layui::select('channel-d', merge_array(['' => '全部渠道'], array_combine($chann, $chann)),
//                    ['id' => 'channel-d']) ?><!--</span></div>-->
<!---->
<!---->
<!--        <div style="width: 100%; height:250px;" id="LAY-agent-dataview">-->
<!--            <div><i class="layui-icon layui-icon-loading1 layadmin-loading"></i></div>-->
<!--        </div>-->
<!---->
<!---->
<!--    </div>-->
</div>


<script src="<?php echo LAY_UI_STATIC ?>/layuiadmin/layui/layui.js"></script>
<script type="text/javascript" src="/static/admin/other/echarts.min.js" charset="utf-8"></script>
<script type="text/javascript" src="/static/admin/js/jquery.min.js" charset="utf-8"></script>

<script>


    function executeChart(legendData, category, seriesData, id, title) {
        echart_config = {
            title: {
                text: title,
                color: '##FF5722',
                fontStyle: "italic"
            },
            legend: {
                data: legendData
            },
            tooltip: {trigger: "axis"},
            xAxis: [{
                type: "category",
                data: category
            }],
            yAxis: [{type: "value"}],
            toolbox: {
                feature: {
                    saveAsImage: {
                        name: "KS-DATA-V"
                    }
                }
            },
            series: seriesData
        };

        var chart = echarts.init(document.getElementById(id));
        console.log(chart);
        chart.setOption(echart_config);
    }

    function getChartAjax() {
        $.ajax({
            url: '/d.php?mod=homestat&code=chartAJax',
            type: 'GET',
            dataType: 'json',
            success: function (res) {
                if (res.code === 0) {
                    let data = res.data;
                    executeChart(data.legendData, data.category, data.seriesData, 'LAY-index-dataview', data.title);
                }
            }
        });
    }

    //function getChartAgentAjax(c = '') {
    //    $.ajax({
    //        url: '<?php //echo url('homeStat/agentChartAjax') ?>//' + '?c=' + c,
    //        type: 'GET',
    //        dataType: 'json',
    //        success: function (res) {
    //            if (res.code == 0) {
    //                let data = res.data;
    //                executeChart(data.legendData, data.category, data.seriesData, 'LAY-agent-dataview', 'T-Agent-V');
    //            }
    //        }
    //    });
    //}

    function getPannelTotal() {
        $.ajax({
            url: '/d.php?mod=homestat&code=ajaxConsoleTotal',
            success: function (data) {
                if (data) {
                    $('#pannel_ul').html(data).fadeIn(500);
                }
            }
        });
    }

    // $('#channel-d').bind('change', function () {
    //     let channel = $(this).val();
    //     getChartAgentAjax(channel);
    // });

    $(function () {

        getPannelTotal();
        getChartAjax();
        // getChartAgentAjax();
        // setTimeout("getPannelTotal()", 1000);
        // setTimeout("getChartAjax()", 2000);
        // setTimeout("getChartAgentAjax()", 3000);
    });


</script>


</body>
</html>