<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">aff</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[aff]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">产品ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[product_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">权限ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[privilege_id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">资源类型</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[resource_type]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">权限类型</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[privilege_type]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                           <!-- <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>-->
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">

                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">aff：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="aff" name="aff"
                           value="{{=d.aff }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">product_id：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="product_id" name="product_id"
                           value="{{=d.product_id }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">privilege_id：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="privilege_id" name="privilege_id"
                           value="{{=d.privilege_id }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">resource_type：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="resource_type" name="resource_type"
                           value="{{=d.resource_type }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">privilege_type：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="privilege_type" name="privilege_type"
                           value="{{=d.privilege_type }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">value：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="value" name="value"
                           value="{{=d.value }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">status：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="status" name="status"
                           value="{{=d.status }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">expired_time：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="expired_time" name="expired_time"
                           value="{{=d.expired_time }}" class="layui-input">

                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">created_at：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="created_at" name="created_at"
                           value="{{=d.created_at }}" class="layui-input">

                </div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">aff：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.aff }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">product_id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.product_id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">privilege_id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.privilege_id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">resource_type：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.resource_type }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">privilege_type：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.privilege_type }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">value：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.value }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">status：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.status }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">expired_time：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.expired_time }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">created_at：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.created_at }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id'}
            , {field: 'aff', title: 'aff'}
            , {field: 'product_id', title: '产品ID'}
            , {field: 'privilege_id', title: '权限ID'}
            , {field: 'resource_type_str', title: '资源类型'}
            , {field: 'privilege_type_str', title: '权限类型'}
            , {field: 'value', title: '总数值'}
            , {field: 'day_value', title: '每日数值'}
            , {field: 'day_remain', title: '今日剩余数值'}
            //, {field: 'status', title: 'status'}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true, width: 90}
            //, {field: 'expired_time', title: 'expired_time'}
            , {field: 'created_at', title: '创建时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>