<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">分组</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[group]',
                                    merge_array(['' => '全选'], ShangwuModel::groupData())) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]',
                                    merge_array(['' => '全选'], ShangwuModel::STATUS)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>

                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="800" data-h="600" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">分组：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('group', ShangwuModel::groupData(), ['data-value' => '{{=d.group}}']) ?>
            </div>
            <label class="layui-form-label">标题：</label>
            <div class="layui-input-inline">

                <input lay-verify="required" placeholder="标题" name="title"
                       value="{{=d.title }}" class="layui-input">

            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">描述：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="描述" name="text"
                       value="{{=d.text }}" class="layui-input">

            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">图标：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('icon_full', 'icon', 40, 40) ?>
                </div>
            </div>
        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">联系方式：</label>
            <div class="layui-input-inline">

                <input lay-verify="required" placeholder="联系方式" name="url"
                       value="{{=d.url }}" class="layui-input">

            </div>

            <label class="layui-form-label">状态：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('status', ShangwuModel::STATUS, ['data-value' => '{{=d.status}}']) ?>

            </div>

        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[

            {field: 'id', title: 'id', sort: true, width: 80}
            , {field: 'title', title: '标题', width: 100}
            //, {field: 'icon', title: '图标'}
            , {
                field: 'icon', width: 100, title: '图标', align: 'center', templet: function (d) {
                    if(d.icon){
                        return '<div onclick="show_img(\''+d.icon_full+'\')" ><img width="50" src="' + d.icon_full + '" /></div>';
                    }
                    return '';
                }
            }
            , {field: 'text', title: '描述'}
            , {field: 'url', title: '联系方式'}
            , {
                field: 'group', title: '分组标识', type: 'enum',
                'value':<?php echo json_encode(ShangwuModel::groupData())?>}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>