### 用户个人中心
POST {{host}}/api/users/followedInfo
Content-Type: application/json

{
  "type": "all",
  "total": true
}

### 用户个人中心
POST {{host}}/api/users/following
Content-Type: application/json

{
  "to_uid": "5624082",
  "channel": "",
  "oauth_type": "android",
  "oauth_id": "114d7daffe70738210cdb08b40e97f75",
  "version": "1.0.5",
  "token": ""
}

###

