<?php use service\TopicService;

importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 5px
    }
    .layui-form-item .layui-inline{
        margin-right: 0px
    }
</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space1">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入ID" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[title]" placeholder="请输入影片标题" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">标签</label>
                            <div class="layui-input-block">
                                <input type="text" name="like[tags]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">来源</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[via]', merge_array(['' => '请选着AV来源'], MvModel::VIA)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">推荐</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_recommend]', merge_array(['' => '请选着推荐'], MvModel::RECOMMEND)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">精选</label>
                            <div class="layui-input-block">
                                <?php echo Layui::search('where[is_feature]', MvModel::IS_FEATURE) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">展示</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[is_hide]', merge_array(['' => '请选着展示'], MvModel::IS_HIDE)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-add-dialog">
                                添加
                            </button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-add-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <!--<a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>-->
                        {{# if (d.status==1) { }}
                        <a class="layui-btn layui-btn-xs" lay-event="recommend" data-pk="{{=d.id}}">
                            <i class="layui-icon layui-icon-home"></i>
                            {{# if (d.is_recommend==0) { }}
                            上推
                            {{#  } else  { }}
                            下推
                            {{#  } }}
                        </a>
                        <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="addTopic" lay-form="topic-dialog" data-pk="{{=d.id}}">
                            加合集
                        </a>
                        <br/>
<!--                        {{# if ( d.is_feature == 0 ) { }}-->
<!--                        <a class="layui-btn layui-btn-xs" lay-event="upFeature" data-pk="{{=d.id}}">-->
<!--                            上精选</a>-->
<!--                        </a>-->
<!--                        {{#  } else { }}-->
<!--                        <a class="layui-btn layui-btn-xs" lay-event="downFeature" data-pk="{{=d.id}}">-->
<!--                            下精选</a>-->
<!--                        </a>-->
<!--                        {{#  }  }}-->
                        {{#  } }}
                        {{# if (d.status==0) { }}
                        <a class="layui-btn layui-btn-xs" lay-event="refuse" data-pk="{{=d.id}}" lay-form="user-refuse-dialog">
                            <i class="layui-icon layui-icon-edit"></i>拒绝</a>
                        </a>
                        <a class="layui-btn layui-btn-xs layui-btn-primary" data-pk="{{=d.id}}" lay-event="approved">
                            <i class="layui-icon layui-icon-edit"></i>通过审核</a>
                        </a>
                        {{#  } else if(d.status==3) { }}
<!--                        <a class="layui-btn layui-btn-xs layui-btn-primary" data-pk="{{=d.id}}" lay-event="retryslice">-->
<!--                            <i class="layui-icon layui-icon-edit"></i>再次回调</a>-->
<!--                        </a>-->
                        {{#  } else if(d.coins>0) { }}
<!--                        <a class="layui-btn layui-btn-xs layui-btn-primary" data-pk="{{=d.id}}" lay-event="avslice">-->
<!--                            <i class="layui-icon layui-icon-edit"></i>再次回调</a>-->
<!--                        </a>-->
                        {{#  } }}

                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" class="data-dialog" id="user-add-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <label class="layui-form-label">影片标题：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="影片标题" name="title"
                       value="{{=d.title }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户id：</label>
                <div class="layui-input-inline">
                    <input placeholder="用户id" name="uid" value="{{d.uid||4888000 }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">影片标签：</label>
            <div class="layui-input-block">
                <div id="adminrole_div" class="xtree_contianer" style="margin-bottom: 10px"></div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">竖版封面：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('y_cover_url', 'y_cover', 40, 40, 'xiao') ?>
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面小图：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('img_thumb', 'cover_thumb', 40, 40, 'xiao') ?>
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面宽：</label>
                <div class="layui-input-inline">
                    <input placeholder="封面宽" name="thumb_width" value="{{d.thumb_width||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">封面高：</label>
                <div class="layui-input-inline">
                    <input placeholder="封面高" name="thumb_height" value="{{d.thumb_height||0 }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面动图：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::uploadPos('img_gif_thumb', 'gif_thumb', 40, 40, 'xiao') ?>
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">动图宽：</label>
                <div class="layui-input-inline">
                    <input placeholder="动图宽" name="thumb_width" value="{{d.gif_width||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">动图高：</label>
                <div class="layui-input-inline">
                    <input placeholder="动图高" name="thumb_height" value="{{d.gif_height||0 }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">预览资源：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadFile(url_backend('upload/uploadMp4'),'m3u8') ?>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">完整资源：</label>
            <div class="layui-input-block">
                <?php echo Layui::uploadFile(url_backend('upload/uploadMp4'),'full_m3u8') ?>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">影片时长：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="时长，秒" name="duration" value="{{=d.duration }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">定价：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="定价" name="coins" value="{{d.coins||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">会员价：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="定价" name="vip_coins" value="{{d.vip_coins||-1 }}" class="layui-input">
                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">评论数：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="评论数" name="comment" value="{{d.comment||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">喜欢数：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="喜欢点击数" name="like" value="{{d.like||0 }}" class="layui-input">
                </div>
            </div>
        </div>



        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">是否限免：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="是否限免 0 收费 1 限免" name="is_free"
                           value="{{d.is_free||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">隐藏：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="0显示1隐藏" name="is_hide" value="{{d.is_hide||0 }}" class="layui-input">
                </div>
            </div>
        </div>


        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">点击数：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="总历史点击数" name="rating" value="{{d.rating||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">状态：</label>
                <div class="layui-input-inline">
                    <?php echo Layui::select('status', MvModel::STAT,['data-value' => '{{=d.status}}']) ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">精彩时长：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="精彩时长：秒" name="thumb_duration"
                           value="{{d.thumb_duration||0 }}" class="layui-input">
                </div>
            </div>
            <div class="layui-inline">
                <label class="layui-form-label">开始时间：</label>
                <div class="layui-input-inline">
                    <input lay-verify="required" placeholder="精彩片段开始时间" name="thumb_start_time"
                           value="{{d.thumb_start_time||0 }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">影片标题：</label>
            <div class="layui-input-block">
                <input lay-verify="required" placeholder="影片标题" name="title" value="{{=d.title }}" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">影片标签：</label>
            <div class="layui-input-block">
                <div id="adminrole_div" class="xtree_contianer" style="margin-bottom: 30px"></div>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">演员：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.actors }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">分类：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.category }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">定价：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.coins }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">评论数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.comment }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面小图：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.cover_thumb }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">创建时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.created_at }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">导演：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.directors }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">时长，秒：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.duration }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">是否限免 0 收费 1 限免：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.is_free }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">0显示1隐藏：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.is_hide }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">喜欢点击数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.like }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">影片资源1：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.m3u8 }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">音乐id：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.music_id }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">影片上映时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.onshelf_tm }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">总历史点击数：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.rating }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">刷新时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.refresh_at }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">0未审核1审核通过：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.status }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">影片标签：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.tags }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">精彩时长：秒：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.thumb_duration }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面高：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.thumb_height }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">精彩片段开始时间：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.thumb_start_time }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">封面宽：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.thumb_width }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">影片标题：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.title }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">用户UUID：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.uid }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">视频格式类型：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.v_ext }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">来源：</label>
                <div class="layui-input-inline">
                    <input disabled value="{{=d.via }}" class="layui-input">
                </div>
            </div>
        </div>
    </form>
</script>
<script type="text/html" class="data-dialog" id="user-refuse-dialog" data-h="480" data-w="700" layer-dialog="确认,取消"
        data-option="{title:'拒绝申请',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">选择拒绝的理由：</label>
            <div class="layui-input-block">
                <select name="refused" class="refused layui-select" id="refused" data-id="{{d.id}}">
                    <option value="">选择拒绝理由</option>
                    <option value="您上传的视频含有水印，语音，道具植入等广告或联系方式。">1.您上传的视频含有水印，语音，道具植入等广告或联系方式。</option>
                    <option value="您上传的视频可能是重复的，如果是原创请加上手势或小卡片再次上传">2.您上传的视频可能是重复的，如果是原创请加上手势或小卡片再次上传。</option>
                    <option value="您上传的视频质量、清晰度还不够好，建议在丰富一下内容再次上传">3.您上传的视频质量、清晰度还不够好，建议在丰富一下内容再次上传</option>
                    <option value="您上传的视频过短，看不到内容/没有声音/主题，请上传新的内容。">4.您上传的视频过短，看不到内容或者没有声音或者是主题，请上传新的内容。</option>
                    <option value="您上传的视频的内容标题和主题不符，请修改后上传。">5.您上传的视频的内容标题和主题不符，请修改后上传。</option>
                    <option value="您上传的视频不适用成人搜同片，请更换内容重新上传">6.您上传的视频不适用成人搜同片，请更换内容重新上传</option>
                    <option value="您上传的视频,标签与视频内容不符">7.您上传的视频,标签与视频内容不符</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <input type="hidden" name="status" value="<?php echo MvModel::STAT_REFUSE ?>">
            <button class="layui-btn submit" lay-submit="" lay-filter="refuseUserUpload"></button>
        </div>
    </form>
</script>
    <script type="text/html" class="data-dialog" id="topic-dialog" data-h="480" data-w="700" layer-dialog="确认,取消"
            data-option="{title:'合集MV设置',closeBtn:false,shadeClose:true,anim:3}">
        <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
            <legend style="color: orangered">合集列表信息</legend>
        </fieldset>
        <form class="layui-form form-dialog" action="" lay-filter="form-save">
            <div class="layui-form-item">
                <label class="layui-form-label"></label>
                <div class="layui-input-block">
                    <?php echo Layui::checkbox('topic_id[]',TopicService::getSearchTopicList())  ?>
                </div>
            </div>
            <div class="layui-form-item layui-hide">
                <input type="hidden" name="_pk" value="{{=d.id}}">
                <button class="layui-btn submit" lay-submit="" lay-filter="topicAddSave"></button>
            </div>
        </form>
    </script>



    <style>
    .layui-table-cell {
        height: 50px;
        line-height: 50px
    }

    .layui-table-fixed .layui-table-cell, .layui-table-col-special .layui-table-cell {
        line-height: 25px
    }

    .layui-xtree-item {
        display: inline-block;
        width: 80px;
    }
</style>
<script src="<?php echo LAY_UI_STATIC ?>layuiadmin/layui-xtree.js"></script>
    <script type="text/html" id="cover-title">
        <div style="width: 150px">
            <div style="width: 150px" class="clearfix">
                <img style="float:left;width: 40px; display: block;background: #cccccc" src="{{d.cover_thumb_url}}" width="40px"  onclick="url_cover_show('{{=d.cover_thumb_url}}')"/>
                <p style="white-space: pre-wrap;float:left;margin-left: 5px;max-width: 100px">
                    {{=d.title}}
                </p>
            </div>
            <hr>
            <p class="clearfix" style="white-space: pre-wrap"><span style="color: red">标签：</span>{{d.tagsname}}</p>
        </div>
    </script>
    <script type="text/html" id="attr-text">
        免费：{{d.is_free}}&nbsp;&nbsp;
        点赞：{{d.like}}<br>
        <span style="font-weight: bolder;color:orangered">销量：{{d.buy_num}}</span>&nbsp;&nbsp;
        播放：{{d.rating}}<br>
        创建：{{d.created_at}}
    </script>
    <script type="text/html" id="user-text">
        <span style="color: green">#{{d.uid}}</span><br>
        <span style="white-space: pre-wrap">{{d.nickname}}</span>
    </script>
<script>
    <?php
    $ajaxUrl = url_backend('listAjax', ['is_gov' =>1]);
    ?>
    xx.use({
        url: '<?php echo $ajaxUrl ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'ID',width: 100}
           /* , {
                field: 'y_cover_url', title: '竖版封面', width: 130, templet: function (d) {
                    if(d.y_cover_url) {
                        return '<img src="' + d.y_cover_url + '" style="width: 100px;height: 80px;" onclick="show_img(\'' + d.y_cover_url + '\')">';
                    }else{
                        return '--';
                    }
                }
            }*/
            , {field: 'title', title: '标题' , width: 180,templet:"#cover-title"}
            , {
                field: 'href', title: '播放源', width: 90, templet: function (d) {
                    let statusStr = d.status == 1 ? 'Pre' : 'MP4';
                    let html = "<a class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.href + "')\"><i class='layui-icon layui-icon-play'></i>" + statusStr + "-1</a><br><br>"
                    return html;
                }
            }, {
                field: 'full_href', title: '播放源', width: 90, templet: function (d) {
                    let statusStr = d.status == 1 ? 'Full' : 'MP4';
                    let html = "<a class='layui-btn layui-btn-sm layui-btn-xs' onclick=\"previewVideo('" + d.full_href + "')\"><i class='layui-icon layui-icon-play'></i>" + statusStr + "-1</a><br><br>"
                    return html;
                }
            }
            , {field: 'uid', title: '上传用户',templet:'#user-text'}
          /*  , {field: 'uid', title: '用户'}*/
            // , {
            //     field: 'cover_thumb_url', title: '封面图', width: 130, templet: function (d) {
            //         return '<img src="' + d.cover_thumb_url + '" style="width: 100px;height: 80px;" onclick="show_img(\'' + d.cover_thumb_url + '\')">';
            //     }
            // }

            // , {field: 'tagsname', title: '标签'}
            , {
                field: 'coins', title: '钻石', width: 80,edit:true,templet: function (d) {

                    return '<span style="font-weight: bolder;font-size: x-large;color: red">' + d.coins + '</span>';
                }
            }, {
                field: 'vip_coins', title: '会员钻', width: 80,edit:true,templet: function (d) {

                    return '<span style="font-weight: bolder;font-size: x-large;color: yellowgreen">' + d.vip_coins + '</span>';
                }
            }
            , { title: '属性', width: 165, templet:"#attr-text"}
           /* , {
                field: 'category', title: '评论数', width: 80,templet: function (d) {

                    return '<a title="点我查看" style="font-weight: bolder;font-size: x-large;color: red" onclick="layerOpen(\'d.php?mod=comment&code=index&mv_id=' + d.id + '\',\'评论列表\')">' + d.comment + '</a>';
                }
            }*/
            // , {field: 'rating', title: '播放量','sort':true}
            // , {field: 'buy_num', title: '购买数',width: 80,templet: function (d) {
            //         return '<span style="font-weight: bolder;font-size: x-large;color:blue">' + d.buy_num + '</span>';
            //     }
            // }
            , {field: 'statusname', title: '状态',width: 80}
            , {field: 'is_recommend',width: 80, title: '推荐', 'type': 'enum', 'value':<?php echo json_encode(MvModel::RECOMMEND)?>}
            , {field: 'is_hide',width: 100,  title: '展示',type: "switch", value: "0|1", edit: true}
            , {field: 'refresh_at',width: 120, title: '更新時間',sort:true}
            , {fixed: 'right', width: 250, title: '操作', align: 'left', toolbar: '#operate-toolbar'}
        ]],
        "done": function (table, data, from, ajax, tpl, $) {
            ajax.get("<?php echo url_backend('tagsList')?>")
                .then(function (json) {
                    return json.data;
                })
                .then(function (data) {
                    xx.use({"menu": data})
                })
        },
        event: {
            'toolbar':{
                addUser: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                }
            },
            //event.operate->refuse
            "operate": {
                edit: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    xx.config('event.renderTree', xx.emptyFn()).call(this, obj, table, ajax, laytpl, layerEle, form, $, nextFn)
                },
                upFeature: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('您确认需要上精选?', function (index2) {
                        ajax.post("<?php echo url_backend('save')?>", {"_pk": $this.data('pk'), 'is_feature': 1})
                            .then(function (json) {
                                layer.close(index2);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, function () {
                                        obj.del();
                                    });
                                }
                            })
                    });
                },
                downFeature: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('您确认需要下精选?', function (index2) {
                        ajax.post("<?php echo url_backend('save')?>", {"_pk": $this.data('pk'), 'is_feature': 0})
                            .then(function (json) {
                                layer.close(index2);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg, function () {
                                        obj.del();
                                    });
                                }
                            })
                    });
                },
                refuse: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn(undefined , function (layerIndex) {
                        Util.formSubmit("<?php echo url_backend('refuseUserUpload')?>", form, ajax, 'refuseUserUpload',function (json) {
                            layer.close(layerIndex);
                            Util.msgOk(json.msg,function () {
                                obj.del();
                            });
                        });
                    });
                },
                addTopic :function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    nextFn(undefined , function (layerIndex) {
                        Util.formSubmit("<?php echo url_backend('addTopic')?>", form, ajax, 'topicAddSave',function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    obj.del();
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                approved: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('您确认要通过审核吗?', function (index2) {
                        ajax.post("<?php echo url_backend('approvedUserUpload')?>", {"_pk": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index2);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg,function () {
                                        obj.del();
                                    });
                                }
                            })
                    });
                },
                recommend: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    ajax.post("<?php echo url_backend('switchRecommend')?>", {"_pk": $this.data('pk')})
                        .then(function (json) {
                            if (json.code) {
                                Util.msgErr(json.msg);
                            } else {
                                Util.msgOk(json.msg,function () {
                                    obj.del();
                                });
                            }
                        })
                },
                retryslice: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('重试切片?', function (index2) {
                        ajax.post("<?php echo url_backend('retryslice')?>", {"_pk": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index2);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg,function () {
                                        obj.del();
                                    });
                                }
                            })
                    });
                },
                avslice: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var $this = $(this);
                    layer.confirm('AV重试切片?', function (index2) {
                        ajax.post("<?php echo url_backend('avslice')?>", {"_pk": $this.data('pk')})
                            .then(function (json) {
                                layer.close(index2);
                                if (json.code) {
                                    Util.msgErr(json.msg);
                                } else {
                                    Util.msgOk(json.msg,function () {
                                        obj.del();
                                    });
                                }
                            })
                    });
                }
            }
            , "renderTree": function (obj, table, ajax, tpl, layerEle, form, $, nextFn) {
                console.log(obj.data);
                let ruleArray = [] , menudata = xx.config('menu'), treeJson = [];
                if (typeof(obj.data) !=="undefined"){
                    ruleArray = obj.data.tags
                }
                $.each(menudata, function (i, item, data) {
                    data = {
                        "inputname": 'tags[]',
                        "title": item,
                        "value": item,
                        "checked": in_array(item, ruleArray),
                        "data": [],
                    };
                    treeJson.push(data);
                });
                nextFn();
                new layuiXtree({
                    elem: 'adminrole_div'
                    , form: form
                    , data: treeJson
                });
            },
        }
    });
</script>
<?php echo Layui::renderJs(); ?>
<?php importView("fooler.phtml"); ?>