<?php include __DIR__ . "/../layout/header.phtml"; ?>
<div class="col-sm-12">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <form id="mvEdit" class="form-horizontal" enctype="multipart/form-data">
                <input type="hidden"  name="data[id]" value="<?php echo $data['id']?>">
                <div class="form-group">
                    <label class="col-sm-3 control-label">标题：</label>
                    <div class="col-sm-8">
                        <input type="text" name="data[title]" class="form-control" id="title" value="<?php echo $data['title']?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">标签：</label>
                    <div class="col-sm-8">
                       <?php foreach ($tagData as $tag){ ?>
                        <label style="margin-left: 5px;color: #029789">
                            <input name="data[tags][]" class="sel" value="<?php echo $tag;?>"  <?php if(in_array($tag,$data['tags'])){ ?> checked <?php } ?> type="checkbox"><?php echo $tag;?>
                        </label>
                        <?php } ?>

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-sm btn-white" type="button" onclick="handleEdit()">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function handleEdit() {
        var data = new FormData($('#mvEdit')[0]);
        $.ajax({
            url: 'd.php?mod=mv&code=doEdit',
            data: data,
            type: 'POST',
            processData: false,
            contentType: false,
            cache: false,
            success: function (res) {
                var icon = 1;
                if (res.status != 1) {
                    icon = 5;
                }
                layer.msg(res.data, {icon: icon,time:2000},function () {
                    parent.window.location.reload();
                })
            }
        })
    }

</script>
<?php include __DIR__ . "/../layout/footer.phtml";?>
