<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">id</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">素材标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="like[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">分类</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[cate_id]', merge_array(['' => '全部'], $face_cate)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">类型</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[type]', merge_array(['' => '全部'], FaceMaterialModel::TYPE_TIPS)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]', merge_array(['' => '全部'], FaceMaterialModel::STATUS_TIPS)) ?>
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchAddPay" data-pk="id" lay-form="batch-add-pay">付费设置</button>
                            <button class="layui-btn layui-btn-sm" lay-event="batchAddCate" data-pk="id" lay-form="batch-add-cate">分类设置</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">素材标题：</label>
                <div class="layui-input-inline">

                    <input lay-verify="required" placeholder="素材标题" name="title"
                           value="{{=d.title }}" class="layui-input">

                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">分类：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('cate_id', $face_cate,['data-value' => '{{=d.cate_id}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">素材图片：</label>
                <div class="layui-input-block">
                    <?php echo Layui::uploadPos('thumb', 'thumb') ?>
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">类型：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('type', FaceMaterialModel::TYPE_TIPS,['data-value' => '{{=d.type}}']) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">金币：</label>
                <div class="layui-input-inline">
                    <input placeholder="金币" name="coins" value="{{=d.coins }}" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">sort：</label>
                <div class="layui-input-inline">

                    <input placeholder="sort" name="sort"
                           value="{{=d.sort }}" class="layui-input">

                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">状态：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('status', FaceMaterialModel::STATUS_TIPS,['data-value' => '{{=d.status}}']) ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script type="text/html" id="a1">
    <div style="display: inline-block;flex-direction: row;align-items:center;">
        <img style="width: 50px;height:50px;" title="素材图片"  alt="素材图片" src="{{d.thumb}}" onclick="show_img('{{d.thumb}}')">
    </div>
</script>

<script type="text/html" class="data-dialog" id="batch-add-pay" data-h="500" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'付费设置',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">付费设置</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">类型</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('type', FaceMaterialModel::TYPE_TIPS) ?>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">金币</label>
            <div class="layui-input-inline">
                <input name="coins" value="" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="face_ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchPay"></button>
        </div>
    </form>
</script>

<script type="text/html" class="data-dialog" id="batch-add-cate" data-h="500" data-w="800" layer-dialog="确认,取消"
        data-option="{title:'分类设置',closeBtn:false,shadeClose:true,anim:3}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend style="color: orangered">分类设置</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">分类</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('cate_id', $face_cate) ?>
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="face_ids">
            <button class="layui-btn submit" lay-submit="" lay-filter="addBatchCate"></button>
        </div>
    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delAllUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
            , {field: 'id', title: 'id'}
            , {field: 'title', title: '素材标题'}
            , {field: 'cate_name', title: '分类'}
            , {field: 'thumb', title: '素材图片',templet:'#a1',width:200}
            , {field: 'type', title: '类型', type: "switch", edit: true, text: "次数/金币|金币", value: "1|0" ,width:120}
            , {field: 'coins', title: '金币', edit: true}
            , {field: 'status', title: '状态', type: "switch", value: "1|0", edit: true}
            , {field: 'sort', title: '排序', edit: true, sort:true}
            , {field: 'use_ct', title: '使用数'}
            , {field: 'created_at', title: '创建时间'}
            , {field: 'updated_at', title: '更新时间'}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]],
        event:{
            'toolbar': {
                batchAddPay: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');
                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        form.val("form-save", {
                            "face_ids": pkValAry.join(',')
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchPay')?>", form, ajax, 'addBatchPay', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
                batchAddCate: function (obj, table, ajax, laytpl, layerEle, form, $, nextFn) {
                    var checkStatus = table.checkStatus(obj.config.id), data = checkStatus.data,
                        pkValAry = [],
                        pkName = $(this).data('pk');
                    for (var i = 0; i < data.length; i++) {
                        if (typeof (data[i][pkName]) !== "undefined") {
                            pkValAry.push(data[i][pkName])
                        }
                    }
                    if (pkValAry.length === 0) {
                        return Util.msgErr('请先选择行');
                    }
                    nextFn(undefined, function (layerIndex) {
                        form.val("form-save", {
                            "face_ids": pkValAry.join(',')
                        });
                        form.render(null, 'form-save');
                        Util.formSubmit("<?php echo url_backend('addBatchCate')?>", form, ajax, 'addBatchCate', function (json) {
                            layer.close(layerIndex);
                            if (json.code == '0') {
                                Util.msgOk(json.msg, function () {
                                    table.reload("gridTab");
                                });
                            } else {
                                Util.msgErr(json.msg);
                            }
                        });
                    });
                },
            },
            operate:{
            },
        }
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>